// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: egress.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const admitEIPDeletion = `-- name: AdmitEIPDeletion :one
UPDATE network_eips SET state='deleting',reason='',last_operation_id=$1,version=version+1,updated_at=clock_timestamp()
WHERE tenant_id=$2 AND eip_id=$3 AND version=$4 RETURNING tenant_id, eip_id, cluster_id, namespace, name, description, pool_id, pool_revision, address, state, reason, version, created_at, updated_at, observed_at, last_operation_id, scope, managed_by, system_owner_vpc
`

type AdmitEIPDeletionParams struct {
	OperationID string
	TenantID    string
	EipID       string
	Version     int64
}

func (q *Queries) AdmitEIPDeletion(ctx context.Context, arg AdmitEIPDeletionParams) (NetworkEip, error) {
	row := q.db.QueryRow(ctx, admitEIPDeletion,
		arg.OperationID,
		arg.TenantID,
		arg.EipID,
		arg.Version,
	)
	var i NetworkEip
	err := row.Scan(
		&i.TenantID,
		&i.EipID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.PoolID,
		&i.PoolRevision,
		&i.Address,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Scope,
		&i.ManagedBy,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const admitSnatDeletion = `-- name: AdmitSnatDeletion :one
UPDATE network_snat_bindings SET state='deleting',reason='',applied_enabled=NULL,last_operation_id=$1,version=version+1,updated_at=clock_timestamp()
WHERE tenant_id=$2 AND snat_id=$3 AND version=$4 RETURNING tenant_id, snat_id, cluster_id, namespace, name, description, vpc_id, eip_id, desired_enabled, applied_enabled, target_generation, state, reason, version, created_at, updated_at, observed_at, last_operation_id, purpose, system_owner_vpc
`

type AdmitSnatDeletionParams struct {
	OperationID string
	TenantID    string
	SnatID      string
	Version     int64
}

func (q *Queries) AdmitSnatDeletion(ctx context.Context, arg AdmitSnatDeletionParams) (NetworkSnatBinding, error) {
	row := q.db.QueryRow(ctx, admitSnatDeletion,
		arg.OperationID,
		arg.TenantID,
		arg.SnatID,
		arg.Version,
	)
	var i NetworkSnatBinding
	err := row.Scan(
		&i.TenantID,
		&i.SnatID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.VpcID,
		&i.EipID,
		&i.DesiredEnabled,
		&i.AppliedEnabled,
		&i.TargetGeneration,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Purpose,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const advanceEIP = `-- name: AdvanceEIP :one
UPDATE network_eips SET state=$1,reason=$2,version=version+1,updated_at=clock_timestamp(),
 address=CASE WHEN $3::text<>'' THEN $3 ELSE address END,
 observed_at=CASE WHEN $4::boolean THEN $5::timestamptz ELSE observed_at END
WHERE tenant_id=$6 AND eip_id=$7 AND version=$8 RETURNING tenant_id, eip_id, cluster_id, namespace, name, description, pool_id, pool_revision, address, state, reason, version, created_at, updated_at, observed_at, last_operation_id, scope, managed_by, system_owner_vpc
`

type AdvanceEIPParams struct {
	State      string
	Reason     string
	Address    string
	Observed   bool
	ObservedAt *time.Time
	TenantID   string
	EipID      string
	Version    int64
}

func (q *Queries) AdvanceEIP(ctx context.Context, arg AdvanceEIPParams) (NetworkEip, error) {
	row := q.db.QueryRow(ctx, advanceEIP,
		arg.State,
		arg.Reason,
		arg.Address,
		arg.Observed,
		arg.ObservedAt,
		arg.TenantID,
		arg.EipID,
		arg.Version,
	)
	var i NetworkEip
	err := row.Scan(
		&i.TenantID,
		&i.EipID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.PoolID,
		&i.PoolRevision,
		&i.Address,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Scope,
		&i.ManagedBy,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const advanceSnat = `-- name: AdvanceSnat :one
UPDATE network_snat_bindings SET state=$1,reason=$2,version=version+1,updated_at=clock_timestamp(),
 applied_enabled=$3::boolean,
 target_generation=greatest(target_generation,$4::bigint),
 observed_at=CASE WHEN $5::boolean THEN $6::timestamptz ELSE observed_at END
WHERE tenant_id=$7 AND snat_id=$8 AND version=$9 RETURNING tenant_id, snat_id, cluster_id, namespace, name, description, vpc_id, eip_id, desired_enabled, applied_enabled, target_generation, state, reason, version, created_at, updated_at, observed_at, last_operation_id, purpose, system_owner_vpc
`

type AdvanceSnatParams struct {
	State            string
	Reason           string
	AppliedEnabled   pgtype.Bool
	TargetGeneration int64
	Observed         bool
	ObservedAt       *time.Time
	TenantID         string
	SnatID           string
	Version          int64
}

func (q *Queries) AdvanceSnat(ctx context.Context, arg AdvanceSnatParams) (NetworkSnatBinding, error) {
	row := q.db.QueryRow(ctx, advanceSnat,
		arg.State,
		arg.Reason,
		arg.AppliedEnabled,
		arg.TargetGeneration,
		arg.Observed,
		arg.ObservedAt,
		arg.TenantID,
		arg.SnatID,
		arg.Version,
	)
	var i NetworkSnatBinding
	err := row.Scan(
		&i.TenantID,
		&i.SnatID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.VpcID,
		&i.EipID,
		&i.DesiredEnabled,
		&i.AppliedEnabled,
		&i.TargetGeneration,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Purpose,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const blockingSnatForEIP = `-- name: BlockingSnatForEIP :one
SELECT count(*)::bigint FROM network_eip_claims WHERE tenant_id=$1 AND eip_id=$2 AND released_at IS NULL
`

type BlockingSnatForEIPParams struct {
	TenantID string
	EipID    string
}

func (q *Queries) BlockingSnatForEIP(ctx context.Context, arg BlockingSnatForEIPParams) (int64, error) {
	row := q.db.QueryRow(ctx, blockingSnatForEIP, arg.TenantID, arg.EipID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const blockingSnatForVPC = `-- name: BlockingSnatForVPC :one
SELECT count(*)::bigint FROM network_snat_bindings WHERE tenant_id=$1 AND vpc_id=$2 AND purpose='public' AND state<>'deleted'
`

type BlockingSnatForVPCParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) BlockingSnatForVPC(ctx context.Context, arg BlockingSnatForVPCParams) (int64, error) {
	row := q.db.QueryRow(ctx, blockingSnatForVPC, arg.TenantID, arg.VpcID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const claimEIPForSnat = `-- name: ClaimEIPForSnat :execrows
INSERT INTO network_eip_claims(tenant_id,eip_id,cluster_id,namespace,target_kind,snat_id,state,created_at)
VALUES($1,$2,$3,$4,'vpc_snat',$5::text,'reserved',$6)
ON CONFLICT DO NOTHING
`

type ClaimEIPForSnatParams struct {
	TenantID  string
	EipID     string
	ClusterID string
	Namespace string
	SnatID    string
	CreatedAt time.Time
}

// The target foreign key and the active EIP index arbitrate SNAT/LB admission.
func (q *Queries) ClaimEIPForSnat(ctx context.Context, arg ClaimEIPForSnatParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimEIPForSnat,
		arg.TenantID,
		arg.EipID,
		arg.ClusterID,
		arg.Namespace,
		arg.SnatID,
		arg.CreatedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countEIPs = `-- name: CountEIPs :one
SELECT count(*) FROM network_eips e WHERE e.tenant_id=$1 AND e.scope='public' AND e.managed_by='tenant'
 AND ($2::text='' OR e.name=$2)
 AND (($3::text='' AND e.state<>'deleted') OR e.state=$3)
`

type CountEIPsParams struct {
	TenantID    string
	NameFilter  string
	StateFilter string
}

func (q *Queries) CountEIPs(ctx context.Context, arg CountEIPsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countEIPs, arg.TenantID, arg.NameFilter, arg.StateFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const dueResourceCandidates = `-- name: DueResourceCandidates :many
SELECT r.tenant_id,coalesce(r.vpc_id,r.subnet_id,r.eip_id,r.snat_id,r.lb_id)::text AS resource_id,b.resource_kind,
 coalesce(r.vpc_id,s.vpc_id,sn.vpc_id,e.system_owner_vpc,lb.vpc_id,'')::text AS parent_vpc_id,coalesce(r.eip_id,sn.eip_id,'')::text AS parent_eip_id,
 r.next_run_at AS due_at
FROM network_reconciliations r JOIN network_provider_bindings b ON b.tenant_id=r.tenant_id
 AND coalesce(b.vpc_id,b.subnet_id,b.eip_id,b.snat_id,b.lb_id)=coalesce(r.vpc_id,r.subnet_id,r.eip_id,r.snat_id,r.lb_id)
LEFT JOIN network_subnets s ON s.tenant_id=r.tenant_id AND s.subnet_id=r.subnet_id
LEFT JOIN network_snat_bindings sn ON sn.tenant_id=r.tenant_id AND sn.snat_id=r.snat_id
LEFT JOIN network_eips e ON e.tenant_id=r.tenant_id AND e.eip_id=r.eip_id
LEFT JOIN network_load_balancers lb ON lb.tenant_id=r.tenant_id AND lb.lb_id=r.lb_id
WHERE NOT r.retired AND r.next_run_at<=clock_timestamp() AND (r.lease_until IS NULL OR r.lease_until<=clock_timestamp())
ORDER BY r.next_run_at,coalesce(r.vpc_id,r.subnet_id,r.eip_id,r.snat_id,r.lb_id) LIMIT 32
`

type DueResourceCandidatesRow struct {
	TenantID     string
	ResourceID   string
	ResourceKind string
	ParentVpcID  string
	ParentEipID  string
	DueAt        time.Time
}

// Global scheduling inventory is worker-only. Admission and completion always
// recover explicit tenant/parent locks and fence the claimed resource version.
func (q *Queries) DueResourceCandidates(ctx context.Context) ([]DueResourceCandidatesRow, error) {
	rows, err := q.db.Query(ctx, dueResourceCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DueResourceCandidatesRow{}
	for rows.Next() {
		var i DueResourceCandidatesRow
		if err := rows.Scan(
			&i.TenantID,
			&i.ResourceID,
			&i.ResourceKind,
			&i.ParentVpcID,
			&i.ParentEipID,
			&i.DueAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEIP = `-- name: GetEIP :one
SELECT e.tenant_id, e.eip_id, e.cluster_id, e.namespace, e.name, e.description, e.pool_id, e.pool_revision, e.address, e.state, e.reason, e.version, e.created_at, e.updated_at, e.observed_at, e.last_operation_id, e.scope, e.managed_by, e.system_owner_vpc,coalesce(c.snat_id,'')::text AS binding_id,
 coalesce(c.state,'unbound')::text AS binding_state,
 coalesce(c.target_kind,'')::text AS binding_target_kind,
 coalesce(c.snat_id,c.lb_id,'')::text AS binding_target_id
FROM network_eips e LEFT JOIN network_eip_claims c
 ON c.tenant_id=e.tenant_id AND c.eip_id=e.eip_id AND c.released_at IS NULL
WHERE e.tenant_id=$1 AND e.eip_id=$2 AND e.scope='public' AND e.managed_by='tenant'
`

type GetEIPParams struct {
	TenantID string
	EipID    string
}

type GetEIPRow struct {
	NetworkEip        NetworkEip
	BindingID         string
	BindingState      string
	BindingTargetKind string
	BindingTargetID   string
}

func (q *Queries) GetEIP(ctx context.Context, arg GetEIPParams) (GetEIPRow, error) {
	row := q.db.QueryRow(ctx, getEIP, arg.TenantID, arg.EipID)
	var i GetEIPRow
	err := row.Scan(
		&i.NetworkEip.TenantID,
		&i.NetworkEip.EipID,
		&i.NetworkEip.ClusterID,
		&i.NetworkEip.Namespace,
		&i.NetworkEip.Name,
		&i.NetworkEip.Description,
		&i.NetworkEip.PoolID,
		&i.NetworkEip.PoolRevision,
		&i.NetworkEip.Address,
		&i.NetworkEip.State,
		&i.NetworkEip.Reason,
		&i.NetworkEip.Version,
		&i.NetworkEip.CreatedAt,
		&i.NetworkEip.UpdatedAt,
		&i.NetworkEip.ObservedAt,
		&i.NetworkEip.LastOperationID,
		&i.NetworkEip.Scope,
		&i.NetworkEip.ManagedBy,
		&i.NetworkEip.SystemOwnerVpc,
		&i.BindingID,
		&i.BindingState,
		&i.BindingTargetKind,
		&i.BindingTargetID,
	)
	return i, err
}

const getEIPClaim = `-- name: GetEIPClaim :one
SELECT e.tenant_id, e.eip_id, e.cluster_id, e.namespace, e.name, e.description, e.pool_id, e.pool_revision, e.address, e.state, e.reason, e.version, e.created_at, e.updated_at, e.observed_at, e.last_operation_id, e.scope, e.managed_by, e.system_owner_vpc,coalesce(c.snat_id,'')::text AS binding_id,
 coalesce(c.state,'unbound')::text AS binding_state,
 coalesce(c.target_kind,'')::text AS binding_target_kind,
 coalesce(c.snat_id,c.lb_id,'')::text AS binding_target_id
FROM network_eips e LEFT JOIN network_eip_claims c
 ON c.tenant_id=e.tenant_id AND c.eip_id=e.eip_id AND c.released_at IS NULL
WHERE e.tenant_id=$1 AND e.eip_id=$2
`

type GetEIPClaimParams struct {
	TenantID string
	EipID    string
}

type GetEIPClaimRow struct {
	NetworkEip        NetworkEip
	BindingID         string
	BindingState      string
	BindingTargetKind string
	BindingTargetID   string
}

// Worker-only lookup includes system addresses and uses the same claim projection.
func (q *Queries) GetEIPClaim(ctx context.Context, arg GetEIPClaimParams) (GetEIPClaimRow, error) {
	row := q.db.QueryRow(ctx, getEIPClaim, arg.TenantID, arg.EipID)
	var i GetEIPClaimRow
	err := row.Scan(
		&i.NetworkEip.TenantID,
		&i.NetworkEip.EipID,
		&i.NetworkEip.ClusterID,
		&i.NetworkEip.Namespace,
		&i.NetworkEip.Name,
		&i.NetworkEip.Description,
		&i.NetworkEip.PoolID,
		&i.NetworkEip.PoolRevision,
		&i.NetworkEip.Address,
		&i.NetworkEip.State,
		&i.NetworkEip.Reason,
		&i.NetworkEip.Version,
		&i.NetworkEip.CreatedAt,
		&i.NetworkEip.UpdatedAt,
		&i.NetworkEip.ObservedAt,
		&i.NetworkEip.LastOperationID,
		&i.NetworkEip.Scope,
		&i.NetworkEip.ManagedBy,
		&i.NetworkEip.SystemOwnerVpc,
		&i.BindingID,
		&i.BindingState,
		&i.BindingTargetKind,
		&i.BindingTargetID,
	)
	return i, err
}

const getEIPInternal = `-- name: GetEIPInternal :one
SELECT tenant_id, eip_id, cluster_id, namespace, name, description, pool_id, pool_revision, address, state, reason, version, created_at, updated_at, observed_at, last_operation_id, scope, managed_by, system_owner_vpc FROM network_eips WHERE tenant_id=$1 AND eip_id=$2
`

type GetEIPInternalParams struct {
	TenantID string
	EipID    string
}

func (q *Queries) GetEIPInternal(ctx context.Context, arg GetEIPInternalParams) (NetworkEip, error) {
	row := q.db.QueryRow(ctx, getEIPInternal, arg.TenantID, arg.EipID)
	var i NetworkEip
	err := row.Scan(
		&i.TenantID,
		&i.EipID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.PoolID,
		&i.PoolRevision,
		&i.Address,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Scope,
		&i.ManagedBy,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const getEgressIdempotency = `-- name: GetEgressIdempotency :one
SELECT tenant_id, operation_kind, idempotency_key, fingerprint, fingerprint_version, vpc_id, operation_id, response, created_at, subnet_id, eip_id, snat_id, lb_id FROM network_idempotency WHERE tenant_id=$1 AND operation_kind=$2 AND idempotency_key=$3
`

type GetEgressIdempotencyParams struct {
	TenantID       string
	OperationKind  string
	IdempotencyKey string
}

func (q *Queries) GetEgressIdempotency(ctx context.Context, arg GetEgressIdempotencyParams) (NetworkIdempotency, error) {
	row := q.db.QueryRow(ctx, getEgressIdempotency, arg.TenantID, arg.OperationKind, arg.IdempotencyKey)
	var i NetworkIdempotency
	err := row.Scan(
		&i.TenantID,
		&i.OperationKind,
		&i.IdempotencyKey,
		&i.Fingerprint,
		&i.FingerprintVersion,
		&i.VpcID,
		&i.OperationID,
		&i.Response,
		&i.CreatedAt,
		&i.SubnetID,
		&i.EipID,
		&i.SnatID,
		&i.LbID,
	)
	return i, err
}

const getSnat = `-- name: GetSnat :one
SELECT s.tenant_id, s.snat_id, s.cluster_id, s.namespace, s.name, s.description, s.vpc_id, s.eip_id, s.desired_enabled, s.applied_enabled, s.target_generation, s.state, s.reason, s.version, s.created_at, s.updated_at, s.observed_at, s.last_operation_id, s.purpose, s.system_owner_vpc,e.address FROM network_snat_bindings s
JOIN network_eips e ON e.tenant_id=s.tenant_id AND e.eip_id=s.eip_id
WHERE s.tenant_id=$1 AND s.purpose='public' AND e.scope='public' AND e.managed_by='tenant' AND
 ((NOT $2::boolean AND s.snat_id=$3::text) OR
 ($2::boolean AND s.vpc_id=$3::text AND s.state<>'deleted'))
`

type GetSnatParams struct {
	TenantID string
	ByVpc    bool
	ID       string
}

type GetSnatRow struct {
	NetworkSnatBinding NetworkSnatBinding
	Address            string
}

func (q *Queries) GetSnat(ctx context.Context, arg GetSnatParams) (GetSnatRow, error) {
	row := q.db.QueryRow(ctx, getSnat, arg.TenantID, arg.ByVpc, arg.ID)
	var i GetSnatRow
	err := row.Scan(
		&i.NetworkSnatBinding.TenantID,
		&i.NetworkSnatBinding.SnatID,
		&i.NetworkSnatBinding.ClusterID,
		&i.NetworkSnatBinding.Namespace,
		&i.NetworkSnatBinding.Name,
		&i.NetworkSnatBinding.Description,
		&i.NetworkSnatBinding.VpcID,
		&i.NetworkSnatBinding.EipID,
		&i.NetworkSnatBinding.DesiredEnabled,
		&i.NetworkSnatBinding.AppliedEnabled,
		&i.NetworkSnatBinding.TargetGeneration,
		&i.NetworkSnatBinding.State,
		&i.NetworkSnatBinding.Reason,
		&i.NetworkSnatBinding.Version,
		&i.NetworkSnatBinding.CreatedAt,
		&i.NetworkSnatBinding.UpdatedAt,
		&i.NetworkSnatBinding.ObservedAt,
		&i.NetworkSnatBinding.LastOperationID,
		&i.NetworkSnatBinding.Purpose,
		&i.NetworkSnatBinding.SystemOwnerVpc,
		&i.Address,
	)
	return i, err
}

const getSnatInternal = `-- name: GetSnatInternal :one
SELECT tenant_id, snat_id, cluster_id, namespace, name, description, vpc_id, eip_id, desired_enabled, applied_enabled, target_generation, state, reason, version, created_at, updated_at, observed_at, last_operation_id, purpose, system_owner_vpc FROM network_snat_bindings WHERE tenant_id=$1 AND snat_id=$2
`

type GetSnatInternalParams struct {
	TenantID string
	SnatID   string
}

func (q *Queries) GetSnatInternal(ctx context.Context, arg GetSnatInternalParams) (NetworkSnatBinding, error) {
	row := q.db.QueryRow(ctx, getSnatInternal, arg.TenantID, arg.SnatID)
	var i NetworkSnatBinding
	err := row.Scan(
		&i.TenantID,
		&i.SnatID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.VpcID,
		&i.EipID,
		&i.DesiredEnabled,
		&i.AppliedEnabled,
		&i.TargetGeneration,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Purpose,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const insertEIP = `-- name: InsertEIP :one
INSERT INTO network_eips(tenant_id,eip_id,cluster_id,namespace,name,description,pool_id,pool_revision,scope,managed_by,state,created_at,updated_at,last_operation_id)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,'public','tenant','provisioning',$9,$9,$10) RETURNING tenant_id, eip_id, cluster_id, namespace, name, description, pool_id, pool_revision, address, state, reason, version, created_at, updated_at, observed_at, last_operation_id, scope, managed_by, system_owner_vpc
`

type InsertEIPParams struct {
	TenantID        string
	EipID           string
	ClusterID       string
	Namespace       string
	Name            string
	Description     string
	PoolID          string
	PoolRevision    int64
	CreatedAt       time.Time
	LastOperationID string
}

func (q *Queries) InsertEIP(ctx context.Context, arg InsertEIPParams) (NetworkEip, error) {
	row := q.db.QueryRow(ctx, insertEIP,
		arg.TenantID,
		arg.EipID,
		arg.ClusterID,
		arg.Namespace,
		arg.Name,
		arg.Description,
		arg.PoolID,
		arg.PoolRevision,
		arg.CreatedAt,
		arg.LastOperationID,
	)
	var i NetworkEip
	err := row.Scan(
		&i.TenantID,
		&i.EipID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.PoolID,
		&i.PoolRevision,
		&i.Address,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Scope,
		&i.ManagedBy,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const insertEgressIdempotency = `-- name: InsertEgressIdempotency :exec
INSERT INTO network_idempotency(tenant_id,operation_kind,idempotency_key,fingerprint,fingerprint_version,eip_id,snat_id,operation_id,response,created_at)
VALUES($1,$2,$3,$4,1,NULLIF($5::text,''),NULLIF($6::text,''),$7,$8,$9)
`

type InsertEgressIdempotencyParams struct {
	TenantID       string
	OperationKind  string
	IdempotencyKey string
	Fingerprint    string
	EipID          string
	SnatID         string
	OperationID    string
	Response       []byte
	CreatedAt      time.Time
}

func (q *Queries) InsertEgressIdempotency(ctx context.Context, arg InsertEgressIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertEgressIdempotency,
		arg.TenantID,
		arg.OperationKind,
		arg.IdempotencyKey,
		arg.Fingerprint,
		arg.EipID,
		arg.SnatID,
		arg.OperationID,
		arg.Response,
		arg.CreatedAt,
	)
	return err
}

const insertSnat = `-- name: InsertSnat :one
INSERT INTO network_snat_bindings(tenant_id,snat_id,cluster_id,namespace,name,description,vpc_id,eip_id,purpose,desired_enabled,state,created_at,updated_at,last_operation_id)
VALUES($1,$2,$3,$4,'VPC SNAT','',$5,$6,'public',true,'provisioning',$7,$7,$8) RETURNING tenant_id, snat_id, cluster_id, namespace, name, description, vpc_id, eip_id, desired_enabled, applied_enabled, target_generation, state, reason, version, created_at, updated_at, observed_at, last_operation_id, purpose, system_owner_vpc
`

type InsertSnatParams struct {
	TenantID        string
	SnatID          string
	ClusterID       string
	Namespace       string
	VpcID           string
	EipID           string
	CreatedAt       time.Time
	LastOperationID string
}

func (q *Queries) InsertSnat(ctx context.Context, arg InsertSnatParams) (NetworkSnatBinding, error) {
	row := q.db.QueryRow(ctx, insertSnat,
		arg.TenantID,
		arg.SnatID,
		arg.ClusterID,
		arg.Namespace,
		arg.VpcID,
		arg.EipID,
		arg.CreatedAt,
		arg.LastOperationID,
	)
	var i NetworkSnatBinding
	err := row.Scan(
		&i.TenantID,
		&i.SnatID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.VpcID,
		&i.EipID,
		&i.DesiredEnabled,
		&i.AppliedEnabled,
		&i.TargetGeneration,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Purpose,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const listEIPs = `-- name: ListEIPs :many
SELECT e.tenant_id, e.eip_id, e.cluster_id, e.namespace, e.name, e.description, e.pool_id, e.pool_revision, e.address, e.state, e.reason, e.version, e.created_at, e.updated_at, e.observed_at, e.last_operation_id, e.scope, e.managed_by, e.system_owner_vpc,coalesce(c.snat_id,'')::text AS binding_id,
 coalesce(c.state,'unbound')::text AS binding_state,
 coalesce(c.target_kind,'')::text AS binding_target_kind,
 coalesce(c.snat_id,c.lb_id,'')::text AS binding_target_id
FROM network_eips e LEFT JOIN network_eip_claims c
 ON c.tenant_id=e.tenant_id AND c.eip_id=e.eip_id AND c.released_at IS NULL
WHERE e.tenant_id=$1 AND e.scope='public' AND e.managed_by='tenant'
 AND ($2::text='' OR e.name=$2)
 AND (($3::text='' AND e.state<>'deleted') OR e.state=$3)
 AND ($4::text='' OR (e.created_at,e.eip_id)<($5::timestamptz,$4::text))
ORDER BY e.created_at DESC,e.eip_id DESC LIMIT $6::integer
`

type ListEIPsParams struct {
	TenantID       string
	NameFilter     string
	StateFilter    string
	AfterID        string
	AfterCreatedAt time.Time
	MaxResults     int32
}

type ListEIPsRow struct {
	NetworkEip        NetworkEip
	BindingID         string
	BindingState      string
	BindingTargetKind string
	BindingTargetID   string
}

func (q *Queries) ListEIPs(ctx context.Context, arg ListEIPsParams) ([]ListEIPsRow, error) {
	rows, err := q.db.Query(ctx, listEIPs,
		arg.TenantID,
		arg.NameFilter,
		arg.StateFilter,
		arg.AfterID,
		arg.AfterCreatedAt,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEIPsRow{}
	for rows.Next() {
		var i ListEIPsRow
		if err := rows.Scan(
			&i.NetworkEip.TenantID,
			&i.NetworkEip.EipID,
			&i.NetworkEip.ClusterID,
			&i.NetworkEip.Namespace,
			&i.NetworkEip.Name,
			&i.NetworkEip.Description,
			&i.NetworkEip.PoolID,
			&i.NetworkEip.PoolRevision,
			&i.NetworkEip.Address,
			&i.NetworkEip.State,
			&i.NetworkEip.Reason,
			&i.NetworkEip.Version,
			&i.NetworkEip.CreatedAt,
			&i.NetworkEip.UpdatedAt,
			&i.NetworkEip.ObservedAt,
			&i.NetworkEip.LastOperationID,
			&i.NetworkEip.Scope,
			&i.NetworkEip.ManagedBy,
			&i.NetworkEip.SystemOwnerVpc,
			&i.BindingID,
			&i.BindingState,
			&i.BindingTargetKind,
			&i.BindingTargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEIP = `-- name: LockEIP :one
SELECT tenant_id, eip_id, cluster_id, namespace, name, description, pool_id, pool_revision, address, state, reason, version, created_at, updated_at, observed_at, last_operation_id, scope, managed_by, system_owner_vpc FROM network_eips WHERE tenant_id=$1 AND eip_id=$2 FOR UPDATE
`

type LockEIPParams struct {
	TenantID string
	EipID    string
}

func (q *Queries) LockEIP(ctx context.Context, arg LockEIPParams) (NetworkEip, error) {
	row := q.db.QueryRow(ctx, lockEIP, arg.TenantID, arg.EipID)
	var i NetworkEip
	err := row.Scan(
		&i.TenantID,
		&i.EipID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.PoolID,
		&i.PoolRevision,
		&i.Address,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Scope,
		&i.ManagedBy,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const lockEgressKey = `-- name: LockEgressKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text||':'||$2::text||':'||$3::text,0))
`

type LockEgressKeyParams struct {
	TenantID       string
	OperationKind  string
	IdempotencyKey string
}

// Tenant commands share permanent idempotency, operations and reconciliation.
func (q *Queries) LockEgressKey(ctx context.Context, arg LockEgressKeyParams) error {
	_, err := q.db.Exec(ctx, lockEgressKey, arg.TenantID, arg.OperationKind, arg.IdempotencyKey)
	return err
}

const lockSnat = `-- name: LockSnat :one
SELECT tenant_id, snat_id, cluster_id, namespace, name, description, vpc_id, eip_id, desired_enabled, applied_enabled, target_generation, state, reason, version, created_at, updated_at, observed_at, last_operation_id, purpose, system_owner_vpc FROM network_snat_bindings WHERE tenant_id=$1 AND snat_id=$2 FOR UPDATE
`

type LockSnatParams struct {
	TenantID string
	SnatID   string
}

func (q *Queries) LockSnat(ctx context.Context, arg LockSnatParams) (NetworkSnatBinding, error) {
	row := q.db.QueryRow(ctx, lockSnat, arg.TenantID, arg.SnatID)
	var i NetworkSnatBinding
	err := row.Scan(
		&i.TenantID,
		&i.SnatID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.VpcID,
		&i.EipID,
		&i.DesiredEnabled,
		&i.AppliedEnabled,
		&i.TargetGeneration,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Purpose,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const setSnatIntent = `-- name: SetSnatIntent :one
UPDATE network_snat_bindings SET desired_enabled=$1,applied_enabled=NULL,state='provisioning',reason='',
 last_operation_id=$2,version=version+1,updated_at=clock_timestamp()
WHERE tenant_id=$3 AND snat_id=$4 AND version=$5 RETURNING tenant_id, snat_id, cluster_id, namespace, name, description, vpc_id, eip_id, desired_enabled, applied_enabled, target_generation, state, reason, version, created_at, updated_at, observed_at, last_operation_id, purpose, system_owner_vpc
`

type SetSnatIntentParams struct {
	Enabled     bool
	OperationID string
	TenantID    string
	SnatID      string
	Version     int64
}

func (q *Queries) SetSnatIntent(ctx context.Context, arg SetSnatIntentParams) (NetworkSnatBinding, error) {
	row := q.db.QueryRow(ctx, setSnatIntent,
		arg.Enabled,
		arg.OperationID,
		arg.TenantID,
		arg.SnatID,
		arg.Version,
	)
	var i NetworkSnatBinding
	err := row.Scan(
		&i.TenantID,
		&i.SnatID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.VpcID,
		&i.EipID,
		&i.DesiredEnabled,
		&i.AppliedEnabled,
		&i.TargetGeneration,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Purpose,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const tryLockWorkEIP = `-- name: TryLockWorkEIP :one
SELECT tenant_id, eip_id, cluster_id, namespace, name, description, pool_id, pool_revision, address, state, reason, version, created_at, updated_at, observed_at, last_operation_id, scope, managed_by, system_owner_vpc FROM network_eips WHERE tenant_id=$1 AND eip_id=$2 FOR UPDATE SKIP LOCKED
`

type TryLockWorkEIPParams struct {
	TenantID string
	EipID    string
}

func (q *Queries) TryLockWorkEIP(ctx context.Context, arg TryLockWorkEIPParams) (NetworkEip, error) {
	row := q.db.QueryRow(ctx, tryLockWorkEIP, arg.TenantID, arg.EipID)
	var i NetworkEip
	err := row.Scan(
		&i.TenantID,
		&i.EipID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.PoolID,
		&i.PoolRevision,
		&i.Address,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Scope,
		&i.ManagedBy,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const tryLockWorkSnat = `-- name: TryLockWorkSnat :one
SELECT tenant_id, snat_id, cluster_id, namespace, name, description, vpc_id, eip_id, desired_enabled, applied_enabled, target_generation, state, reason, version, created_at, updated_at, observed_at, last_operation_id, purpose, system_owner_vpc FROM network_snat_bindings WHERE tenant_id=$1 AND snat_id=$2 FOR UPDATE SKIP LOCKED
`

type TryLockWorkSnatParams struct {
	TenantID string
	SnatID   string
}

func (q *Queries) TryLockWorkSnat(ctx context.Context, arg TryLockWorkSnatParams) (NetworkSnatBinding, error) {
	row := q.db.QueryRow(ctx, tryLockWorkSnat, arg.TenantID, arg.SnatID)
	var i NetworkSnatBinding
	err := row.Scan(
		&i.TenantID,
		&i.SnatID,
		&i.ClusterID,
		&i.Namespace,
		&i.Name,
		&i.Description,
		&i.VpcID,
		&i.EipID,
		&i.DesiredEnabled,
		&i.AppliedEnabled,
		&i.TargetGeneration,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.Purpose,
		&i.SystemOwnerVpc,
	)
	return i, err
}

const tryLockWorkVPC = `-- name: TryLockWorkVPC :one
SELECT tenant_id, vpc_id, name, description, cidr, state, reason, version, created_at, updated_at, observed_at, last_operation_id, base_connectivity_required FROM network_vpcs WHERE tenant_id=$1 AND vpc_id=$2 FOR UPDATE SKIP LOCKED
`

type TryLockWorkVPCParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) TryLockWorkVPC(ctx context.Context, arg TryLockWorkVPCParams) (NetworkVpc, error) {
	row := q.db.QueryRow(ctx, tryLockWorkVPC, arg.TenantID, arg.VpcID)
	var i NetworkVpc
	err := row.Scan(
		&i.TenantID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.BaseConnectivityRequired,
	)
	return i, err
}
