// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type NetworkAttachment struct {
	TenantID            string
	AttachmentID        string
	VpcID               string
	SubnetID            string
	BindingID           string
	InstanceID          string
	Slot                string
	RequestKey          string
	SubmissionID        string
	Generation          int64
	Fingerprint         string
	ClusterID           string
	Namespace           string
	BindingRevision     string
	Plan                []byte
	State               string
	Reason              string
	ProtocolBlocked     bool
	Version             int64
	PodName             string
	PodUid              string
	ConfirmUid          string
	FinalizationID      *string
	ProviderRelations   []byte
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ObservedAt          *time.Time
	ReleasedAt          *time.Time
	NextCheckAt         time.Time
	LeaseOwner          *string
	LeaseUntil          *time.Time
	Epoch               int64
	RequestedGeneration int64
	ProcessedGeneration int64
	RetryNotBefore      time.Time
	EvidenceHash        string
	EvidenceAppliedAt   time.Time
}

type NetworkAttachmentHistory struct {
	TenantID       string
	HistoryID      string
	AttachmentID   string
	Version        int64
	Event          string
	State          string
	Reason         string
	PodUid         string
	FinalizationID *string
	CreatedAt      time.Time
}

type NetworkBaseBackfillCandidate struct {
	TenantID           string
	RunID              string
	ClusterID          string
	VpcID              string
	AcceptedVpcVersion int64
	State              string
	Reason             string
	OperationID        *string
	Namespace          *string
	BindingID          *string
	ProviderName       string
	ProviderUid        string
	InitialState       string
	InitialReason      string
}

type NetworkBaseBackfillRun struct {
	RunID           string
	ClusterID       string
	PoolID          string
	PoolRevision    int64
	Scope           string
	Paused          bool
	IntervalMs      int64
	NextAdmissionAt time.Time
	CreatedAt       time.Time
	PlanSha256      string
	ReviewedAt      *time.Time
}

type NetworkConnectivityRollout struct {
	ClusterID                string
	NewVpcsEnabled           bool
	LegacyAggregationEnabled bool
	UpdatedAt                time.Time
}

type NetworkDefaultIntranetPool struct {
	ClusterID string
	PoolID    string
	Scope     string
	Version   int64
}

type NetworkDefaultPublicPool struct {
	ClusterID string
	PoolID    string
	Version   int64
	Scope     string
}

type NetworkDeviceAdoption struct {
	ResourceID           string
	ClusterID            string
	Kind                 string
	DeviceName           string
	InventoryFingerprint string
	NodeInventory        []byte
	NodeProgress         []byte
}

type NetworkEgressGateway struct {
	ResourceID string
	ClusterID  string
	Kind       string
}

type NetworkEip struct {
	TenantID        string
	EipID           string
	ClusterID       string
	Namespace       string
	Name            string
	Description     string
	PoolID          string
	PoolRevision    int64
	Address         string
	State           string
	Reason          string
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ObservedAt      *time.Time
	LastOperationID string
	Scope           string
	ManagedBy       string
	SystemOwnerVpc  *string
}

type NetworkEipClaim struct {
	TenantID   string
	ClaimID    string
	ClusterID  string
	Namespace  string
	EipID      string
	TargetKind string
	SnatID     *string
	LbID       *string
	State      string
	CreatedAt  time.Time
	ReleasedAt *time.Time
}

type NetworkIdempotency struct {
	TenantID           string
	OperationKind      string
	IdempotencyKey     string
	Fingerprint        string
	FingerprintVersion int32
	VpcID              *string
	OperationID        string
	Response           []byte
	CreatedAt          time.Time
	SubnetID           *string
	EipID              *string
	SnatID             *string
	LbID               *string
}

type NetworkLbCapability struct {
	ClusterID      string
	Ready          bool
	Reason         string
	ObservedAt     time.Time
	Fingerprint    string
	ProviderImages []string
}

type NetworkLbComponent struct {
	TenantID             string
	ClusterID            string
	Namespace            string
	LbID                 string
	ComponentID          string
	Kind                 string
	MemberID             *string
	ProviderName         string
	ProviderUid          string
	CreateDispatched     bool
	PendingAction        string
	PendingSince         *time.Time
	TargetVersion        int64
	AppliedVersion       int64
	AppliedConfigVersion pgtype.Int8
	DeletedAt            *time.Time
	ListenerID           *string
}

type NetworkLbConfiguration struct {
	TenantID           string
	ClusterID          string
	Namespace          string
	LbID               string
	ConfigVersion      int64
	Name               string
	Description        string
	IntervalSeconds    int64
	TimeoutSeconds     int64
	UnhealthyThreshold int64
	HealthyThreshold   int64
	CreatedAt          time.Time
	HealthCheckPort    int32
}

type NetworkLbConfigurationListener struct {
	TenantID           string
	ClusterID          string
	Namespace          string
	LbID               string
	ConfigVersion      int64
	ListenerID         string
	Protocol           string
	Port               int32
	IntervalSeconds    int64
	TimeoutSeconds     int64
	UnhealthyThreshold int64
	HealthyThreshold   int64
	HealthCheckPort    int32
}

type NetworkLbConfigurationMember struct {
	TenantID      string
	ClusterID     string
	Namespace     string
	LbID          string
	ConfigVersion int64
	MemberID      string
	Weight        int32
}

type NetworkLbGeneratedResource struct {
	TenantID     string
	ClusterID    string
	Namespace    string
	LbID         string
	Kind         string
	ProviderName string
	ProviderUid  string
	GatewayUid   string
	ObservedAt   time.Time
	ReleasedAt   *time.Time
}

type NetworkLbListener struct {
	TenantID   string
	ClusterID  string
	Namespace  string
	LbID       string
	ListenerID string
	Protocol   string
	Port       int32
	Name       string
}

type NetworkLbListenerMember struct {
	TenantID      string
	LbID          string
	ConfigVersion int64
	ListenerID    string
	MemberID      string
	Weight        int32
}

type NetworkLbMember struct {
	TenantID     string
	ClusterID    string
	Namespace    string
	LbID         string
	MemberID     string
	VpcID        string
	SubnetID     string
	AttachmentID string
	Address      string
	Port         int32
	PodUid       string
	VnicName     string
	VnicUid      string
	VnicipName   string
	VnicipUid    string
	State        string
	Reason       string
	ObservedAt   *time.Time
}

type NetworkLbSubnetRef struct {
	TenantID   string
	ClusterID  string
	Namespace  string
	LbID       string
	VpcID      string
	SubnetID   string
	ReleasedAt *time.Time
}

type NetworkLbVipIntent struct {
	TenantID   string
	LbID       string
	ClusterID  string
	Namespace  string
	VpcID      string
	SubnetID   string
	Address    string
	ReleasedAt *time.Time
}

type NetworkLoadBalancer struct {
	TenantID              string
	LbID                  string
	ClusterID             string
	Namespace             string
	VpcID                 string
	SubnetID              string
	Exposure              string
	PublicEipID           *string
	PublicScope           string
	PrivateIp             *string
	State                 string
	Version               int64
	CreatedAt             time.Time
	Name                  string
	Description           string
	Flavor                string
	Reason                string
	UpdatedAt             time.Time
	ObservedAt            *time.Time
	VipOccupiedRevision   string
	VipAbsenceRevision    string
	LastOperationID       *string
	DesiredVersion        int64
	AppliedVersion        int64
	ConfigurationState    string
	DataPlaneState        string
	DataPlaneObservedAt   *time.Time
	AcceptedConfigVersion pgtype.Int8
	AppliedConfigVersion  pgtype.Int8
}

type NetworkOperation struct {
	TenantID       string
	OperationID    string
	VpcID          *string
	Kind           string
	State          string
	Reason         string
	Attempt        int32
	ExecutionEpoch int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    *time.Time
	NextAttemptAt  *time.Time
	SubnetID       *string
	EipID          *string
	SnatID         *string
	LbID           *string
}

type NetworkPlatformHistory struct {
	HistoryID      string
	ResourceID     string
	OperationID    *string
	Event          string
	ResourceState  string
	OperationState string
	Reason         string
	ActorRef       string
	CallerRef      string
	CreatedAt      time.Time
}

type NetworkPlatformIdempotency struct {
	ClusterID          string
	OperationKind      string
	IdempotencyKey     string
	Fingerprint        string
	FingerprintVersion int32
	ResourceID         string
	OperationID        string
	Response           []byte
	CreatedAt          time.Time
}

type NetworkPlatformOperation struct {
	OperationID    string
	ResourceID     string
	Kind           string
	State          string
	Reason         string
	Attempt        int32
	ExecutionEpoch int64
	CreatedAt      time.Time
	UpdatedAt      time.Time
	CompletedAt    *time.Time
	NextAttemptAt  *time.Time
}

type NetworkPlatformReconciliation struct {
	ResourceID          string
	NextRunAt           time.Time
	LeaseOwner          *string
	LeaseUntil          *time.Time
	LeaseEpoch          int64
	RequestedGeneration int64
	ProcessedGeneration int64
	RetryNotBefore      time.Time
	EvidenceHash        string
	EvidenceAppliedAt   time.Time
}

type NetworkPlatformResource struct {
	ResourceID      string
	Kind            string
	ClusterID       string
	Name            string
	Description     string
	State           string
	Reason          string
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ObservedAt      *time.Time
	LastOperationID string
	ProviderName    string
	ProviderUid     string
	ProviderImages  []string
	BindingID       string
	PendingAction   string
	PendingSince    *time.Time
}

type NetworkProviderBinding struct {
	TenantID         string
	VpcID            *string
	BindingID        string
	ClusterID        string
	Namespace        string
	ProviderName     string
	ProviderUid      string
	PendingAction    string
	PendingSince     *time.Time
	SubnetID         *string
	ResourceKind     string
	EipID            *string
	SnatID           *string
	CreateDispatched bool
	LbID             *string
}

type NetworkPublicPool struct {
	ResourceID            string
	ClusterID             string
	Kind                  string
	Mode                  string
	GatewayID             *string
	Cidr                  string
	OvnGatewayIp          string
	ExcludedIps           []string
	VlanNetworkID         *string
	UpstreamGatewayIp     *string
	AllocationEnabled     bool
	ConfigRevision        int64
	Verification          []byte
	VerificationExpiresAt *time.Time
	Retired               bool
	Scope                 string
	DefaultVpcName        string
	DefaultVpcUid         string
	IntranetNetworks      []string
}

type NetworkReconciliation struct {
	TenantID            string
	VpcID               *string
	NextRunAt           time.Time
	LeaseOwner          *string
	LeaseUntil          *time.Time
	LeaseEpoch          int64
	SubnetID            *string
	ReconciliationID    string
	RequestedGeneration int64
	ProcessedGeneration int64
	RetryNotBefore      time.Time
	EvidenceHash        string
	EvidenceAppliedAt   time.Time
	EipID               *string
	SnatID              *string
	Retired             bool
	LbID                *string
}

type NetworkResourceHistory struct {
	TenantID         string
	HistoryID        string
	VpcID            *string
	OperationID      *string
	Event            string
	ResourceState    string
	OperationState   string
	Reason           string
	ActorRef         string
	CallerRef        string
	CorrelationID    string
	IdentityVerified bool
	CreatedAt        time.Time
	SubnetID         *string
	EipID            *string
	SnatID           *string
	LbID             *string
}

type NetworkSnatBinding struct {
	TenantID         string
	SnatID           string
	ClusterID        string
	Namespace        string
	Name             string
	Description      string
	VpcID            string
	EipID            string
	DesiredEnabled   bool
	AppliedEnabled   pgtype.Bool
	TargetGeneration int64
	State            string
	Reason           string
	Version          int64
	CreatedAt        time.Time
	UpdatedAt        time.Time
	ObservedAt       *time.Time
	LastOperationID  string
	Purpose          string
	SystemOwnerVpc   *string
}

type NetworkSubnet struct {
	TenantID        string
	SubnetID        string
	VpcID           string
	Name            string
	Description     string
	Cidr            string
	Gateway         string
	State           string
	Reason          string
	Version         int64
	CreatedAt       time.Time
	UpdatedAt       time.Time
	ObservedAt      *time.Time
	LastOperationID string
}

type NetworkTenantNamespace struct {
	TenantID  string
	ClusterID string
	Namespace string
}

type NetworkVlanNetwork struct {
	ResourceID string
	ClusterID  string
	Kind       string
	DeviceID   string
	VlanID     int32
	Retired    bool
}

type NetworkVpc struct {
	TenantID                 string
	VpcID                    string
	Name                     string
	Description              string
	Cidr                     string
	State                    string
	Reason                   string
	Version                  int64
	CreatedAt                time.Time
	UpdatedAt                time.Time
	ObservedAt               *time.Time
	LastOperationID          string
	BaseConnectivityRequired bool
}

type NetworkVpcBaseConnectivity struct {
	TenantID           string
	VpcID              string
	ClusterID          string
	Namespace          string
	PoolID             string
	PoolRevision       int64
	Purpose            string
	EipID              string
	SnatID             string
	OperationID        string
	State              string
	Reason             string
	ProviderReady      bool
	ProviderObservedAt *time.Time
	ObservedAt         *time.Time
	Terminating        bool
	Version            int64
	CreatedAt          time.Time
}
