// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"
)

const acquirePlatformLease = `-- name: AcquirePlatformLease :one
UPDATE network_platform_reconciliations SET lease_owner=$1::uuid,lease_epoch=lease_epoch+1,
 lease_until=clock_timestamp()+$2::bigint*interval '1 microsecond'
WHERE resource_id=$3 AND (lease_until IS NULL OR lease_until<=clock_timestamp()) RETURNING resource_id, next_run_at, lease_owner, lease_until, lease_epoch, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at
`

type AcquirePlatformLeaseParams struct {
	Owner       string
	LeaseMicros int64
	ResourceID  string
}

func (q *Queries) AcquirePlatformLease(ctx context.Context, arg AcquirePlatformLeaseParams) (NetworkPlatformReconciliation, error) {
	row := q.db.QueryRow(ctx, acquirePlatformLease, arg.Owner, arg.LeaseMicros, arg.ResourceID)
	var i NetworkPlatformReconciliation
	err := row.Scan(
		&i.ResourceID,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LeaseEpoch,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
	)
	return i, err
}

const advancePlatform = `-- name: AdvancePlatform :one
UPDATE network_platform_resources SET state=$1,reason=$2,version=version+1,updated_at=clock_timestamp(),
 provider_uid=CASE WHEN provider_uid='' THEN $3::text ELSE provider_uid END,
 observed_at=CASE WHEN $4::boolean THEN $5::timestamptz ELSE observed_at END,
 pending_action=CASE WHEN $6::boolean THEN '' ELSE pending_action END,
 pending_since=CASE WHEN $6::boolean THEN NULL ELSE pending_since END
WHERE resource_id=$7 AND version=$8 AND (provider_uid='' OR provider_uid=$3) RETURNING resource_id, kind, cluster_id, name, description, state, reason, version, created_at, updated_at, observed_at, last_operation_id, provider_name, provider_uid, provider_images, binding_id, pending_action, pending_since
`

type AdvancePlatformParams struct {
	State        string
	Reason       string
	Identity     string
	Observed     bool
	ObservedAt   *time.Time
	ClearPending bool
	ResourceID   string
	Version      int64
}

func (q *Queries) AdvancePlatform(ctx context.Context, arg AdvancePlatformParams) (NetworkPlatformResource, error) {
	row := q.db.QueryRow(ctx, advancePlatform,
		arg.State,
		arg.Reason,
		arg.Identity,
		arg.Observed,
		arg.ObservedAt,
		arg.ClearPending,
		arg.ResourceID,
		arg.Version,
	)
	var i NetworkPlatformResource
	err := row.Scan(
		&i.ResourceID,
		&i.Kind,
		&i.ClusterID,
		&i.Name,
		&i.Description,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.ProviderName,
		&i.ProviderUid,
		&i.ProviderImages,
		&i.BindingID,
		&i.PendingAction,
		&i.PendingSince,
	)
	return i, err
}

const beginPlatformMutation = `-- name: BeginPlatformMutation :execrows
UPDATE network_platform_resources SET pending_action=$1,pending_since=clock_timestamp(),
 provider_uid=CASE WHEN provider_uid='' THEN $2::text ELSE provider_uid END
WHERE resource_id=$3 AND binding_id=$4 AND (provider_uid='' OR provider_uid=$2)
 AND (($1::text='create' AND pending_action='') OR
 ($1='delete' AND (pending_action IN ('','delete') OR $2::text<>'')))
`

type BeginPlatformMutationParams struct {
	Action     string
	Identity   string
	ResourceID string
	BindingID  string
}

func (q *Queries) BeginPlatformMutation(ctx context.Context, arg BeginPlatformMutationParams) (int64, error) {
	result, err := q.db.Exec(ctx, beginPlatformMutation,
		arg.Action,
		arg.Identity,
		arg.ResourceID,
		arg.BindingID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const checkPlatformLease = `-- name: CheckPlatformLease :one
SELECT resource_id, next_run_at, lease_owner, lease_until, lease_epoch, requested_generation, processed_generation, retry_not_before, evidence_hash, evidence_applied_at FROM network_platform_reconciliations WHERE resource_id=$1 AND lease_owner=$2::uuid
 AND lease_epoch=$3 AND lease_until>clock_timestamp() FOR UPDATE
`

type CheckPlatformLeaseParams struct {
	ResourceID string
	Owner      string
	Epoch      int64
}

func (q *Queries) CheckPlatformLease(ctx context.Context, arg CheckPlatformLeaseParams) (NetworkPlatformReconciliation, error) {
	row := q.db.QueryRow(ctx, checkPlatformLease, arg.ResourceID, arg.Owner, arg.Epoch)
	var i NetworkPlatformReconciliation
	err := row.Scan(
		&i.ResourceID,
		&i.NextRunAt,
		&i.LeaseOwner,
		&i.LeaseUntil,
		&i.LeaseEpoch,
		&i.RequestedGeneration,
		&i.ProcessedGeneration,
		&i.RetryNotBefore,
		&i.EvidenceHash,
		&i.EvidenceAppliedAt,
	)
	return i, err
}

const completePlatformAttempt = `-- name: CompletePlatformAttempt :execrows
UPDATE network_platform_operations SET state=$1,reason=$2,updated_at=clock_timestamp(),
 completed_at=CASE WHEN $1::text IN ('succeeded','failed') THEN clock_timestamp() ELSE NULL END,
 next_attempt_at=CASE WHEN $1::text IN ('succeeded','failed') THEN NULL ELSE clock_timestamp()+$3::bigint*interval '1 microsecond' END
WHERE operation_id=$4 AND resource_id=$5 AND execution_epoch=$6 AND completed_at IS NULL
`

type CompletePlatformAttemptParams struct {
	State       string
	Reason      string
	DelayMicros int64
	OperationID string
	ResourceID  string
	Epoch       int64
}

func (q *Queries) CompletePlatformAttempt(ctx context.Context, arg CompletePlatformAttemptParams) (int64, error) {
	result, err := q.db.Exec(ctx, completePlatformAttempt,
		arg.State,
		arg.Reason,
		arg.DelayMicros,
		arg.OperationID,
		arg.ResourceID,
		arg.Epoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countGatewayPools = `-- name: CountGatewayPools :one
SELECT count(*)::bigint FROM network_public_pools p JOIN network_platform_resources r ON r.cluster_id=p.cluster_id AND r.resource_id=p.resource_id
WHERE p.cluster_id=$1 AND p.gateway_id=$2 AND r.state<>'deleted'
`

type CountGatewayPoolsParams struct {
	ClusterID string
	GatewayID *string
}

func (q *Queries) CountGatewayPools(ctx context.Context, arg CountGatewayPoolsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countGatewayPools, arg.ClusterID, arg.GatewayID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countIntranetPools = `-- name: CountIntranetPools :one
SELECT count(*) FROM network_platform_resources r JOIN network_public_pools p ON p.cluster_id=r.cluster_id AND p.resource_id=r.resource_id WHERE r.cluster_id=$1 AND p.scope='intranet'
 AND ($2::text='' OR r.name=$2)
 AND (($3::text='' AND r.state<>'deleted') OR r.state=$3)
`

type CountIntranetPoolsParams struct {
	ClusterID   string
	NameFilter  string
	StateFilter string
}

func (q *Queries) CountIntranetPools(ctx context.Context, arg CountIntranetPoolsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countIntranetPools, arg.ClusterID, arg.NameFilter, arg.StateFilter)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPlatform = `-- name: CountPlatform :one
SELECT count(*) FROM network_platform_resources r WHERE r.cluster_id=$1 AND r.kind=$2
 AND (r.kind<>'public_pool' OR EXISTS (SELECT 1 FROM network_public_pools pool WHERE pool.cluster_id=r.cluster_id AND pool.resource_id=r.resource_id AND pool.scope='public'))
 AND ($3::text='' OR r.name=$3)
 AND (($4::text='' AND r.state<>'deleted') OR r.state=$4)
`

type CountPlatformParams struct {
	ClusterID   string
	Kind        string
	NameFilter  string
	StateFilter string
}

func (q *Queries) CountPlatform(ctx context.Context, arg CountPlatformParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPlatform,
		arg.ClusterID,
		arg.Kind,
		arg.NameFilter,
		arg.StateFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPoolEIPs = `-- name: CountPoolEIPs :one
SELECT count(*)::bigint FROM network_eips WHERE cluster_id=$1 AND pool_id=$2 AND state<>'deleted'
`

type CountPoolEIPsParams struct {
	ClusterID string
	PoolID    string
}

func (q *Queries) CountPoolEIPs(ctx context.Context, arg CountPoolEIPsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPoolEIPs, arg.ClusterID, arg.PoolID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countVlanPools = `-- name: CountVlanPools :one
SELECT count(*)::bigint FROM network_public_pools p JOIN network_platform_resources r ON r.cluster_id=p.cluster_id AND r.resource_id=p.resource_id
WHERE p.cluster_id=$1 AND p.vlan_network_id=$2 AND r.state<>'deleted'
`

type CountVlanPoolsParams struct {
	ClusterID     string
	VlanNetworkID *string
}

func (q *Queries) CountVlanPools(ctx context.Context, arg CountVlanPoolsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVlanPools, arg.ClusterID, arg.VlanNetworkID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const duePlatformCandidate = `-- name: DuePlatformCandidate :one
SELECT p.resource_id, p.kind, p.cluster_id, p.name, p.description, p.state, p.reason, p.version, p.created_at, p.updated_at, p.observed_at, p.last_operation_id, p.provider_name, p.provider_uid, p.provider_images, p.binding_id, p.pending_action, p.pending_since FROM network_platform_resources p JOIN network_platform_reconciliations r ON r.resource_id=p.resource_id
WHERE p.cluster_id=$1 AND r.next_run_at<=clock_timestamp() AND (r.lease_until IS NULL OR r.lease_until<=clock_timestamp())
ORDER BY r.next_run_at,p.resource_id LIMIT 1 FOR UPDATE OF p SKIP LOCKED
`

type DuePlatformCandidateParams struct {
	ClusterID string
}

// Shared worker's platform lane; this is not a second executor.
func (q *Queries) DuePlatformCandidate(ctx context.Context, arg DuePlatformCandidateParams) (NetworkPlatformResource, error) {
	row := q.db.QueryRow(ctx, duePlatformCandidate, arg.ClusterID)
	var i NetworkPlatformResource
	err := row.Scan(
		&i.ResourceID,
		&i.Kind,
		&i.ClusterID,
		&i.Name,
		&i.Description,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.ProviderName,
		&i.ProviderUid,
		&i.ProviderImages,
		&i.BindingID,
		&i.PendingAction,
		&i.PendingSince,
	)
	return i, err
}

const getDefaultIntranetPool = `-- name: GetDefaultIntranetPool :one
SELECT cluster_id, pool_id, scope, version FROM network_default_intranet_pools WHERE cluster_id=$1
`

type GetDefaultIntranetPoolParams struct {
	ClusterID string
}

func (q *Queries) GetDefaultIntranetPool(ctx context.Context, arg GetDefaultIntranetPoolParams) (NetworkDefaultIntranetPool, error) {
	row := q.db.QueryRow(ctx, getDefaultIntranetPool, arg.ClusterID)
	var i NetworkDefaultIntranetPool
	err := row.Scan(
		&i.ClusterID,
		&i.PoolID,
		&i.Scope,
		&i.Version,
	)
	return i, err
}

const getDefaultPublicPool = `-- name: GetDefaultPublicPool :one
SELECT cluster_id, pool_id, version, scope FROM network_default_public_pools WHERE cluster_id=$1
`

type GetDefaultPublicPoolParams struct {
	ClusterID string
}

func (q *Queries) GetDefaultPublicPool(ctx context.Context, arg GetDefaultPublicPoolParams) (NetworkDefaultPublicPool, error) {
	row := q.db.QueryRow(ctx, getDefaultPublicPool, arg.ClusterID)
	var i NetworkDefaultPublicPool
	err := row.Scan(
		&i.ClusterID,
		&i.PoolID,
		&i.Version,
		&i.Scope,
	)
	return i, err
}

const getDeviceAdoption = `-- name: GetDeviceAdoption :one
SELECT resource_id, cluster_id, kind, device_name, inventory_fingerprint, node_inventory, node_progress FROM network_device_adoptions WHERE cluster_id=$1 AND resource_id=$2
`

type GetDeviceAdoptionParams struct {
	ClusterID  string
	ResourceID string
}

func (q *Queries) GetDeviceAdoption(ctx context.Context, arg GetDeviceAdoptionParams) (NetworkDeviceAdoption, error) {
	row := q.db.QueryRow(ctx, getDeviceAdoption, arg.ClusterID, arg.ResourceID)
	var i NetworkDeviceAdoption
	err := row.Scan(
		&i.ResourceID,
		&i.ClusterID,
		&i.Kind,
		&i.DeviceName,
		&i.InventoryFingerprint,
		&i.NodeInventory,
		&i.NodeProgress,
	)
	return i, err
}

const getPlatform = `-- name: GetPlatform :one
SELECT resource_id, kind, cluster_id, name, description, state, reason, version, created_at, updated_at, observed_at, last_operation_id, provider_name, provider_uid, provider_images, binding_id, pending_action, pending_since FROM network_platform_resources WHERE cluster_id=$1 AND kind=$2 AND resource_id=$3
`

type GetPlatformParams struct {
	ClusterID  string
	Kind       string
	ResourceID string
}

// Platform tables do not carry a synthetic tenant. Cluster scope is mandatory.
func (q *Queries) GetPlatform(ctx context.Context, arg GetPlatformParams) (NetworkPlatformResource, error) {
	row := q.db.QueryRow(ctx, getPlatform, arg.ClusterID, arg.Kind, arg.ResourceID)
	var i NetworkPlatformResource
	err := row.Scan(
		&i.ResourceID,
		&i.Kind,
		&i.ClusterID,
		&i.Name,
		&i.Description,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.ProviderName,
		&i.ProviderUid,
		&i.ProviderImages,
		&i.BindingID,
		&i.PendingAction,
		&i.PendingSince,
	)
	return i, err
}

const getPlatformIdempotency = `-- name: GetPlatformIdempotency :one
SELECT cluster_id, operation_kind, idempotency_key, fingerprint, fingerprint_version, resource_id, operation_id, response, created_at FROM network_platform_idempotency WHERE cluster_id=$1 AND operation_kind=$2 AND idempotency_key=$3
`

type GetPlatformIdempotencyParams struct {
	ClusterID      string
	OperationKind  string
	IdempotencyKey string
}

func (q *Queries) GetPlatformIdempotency(ctx context.Context, arg GetPlatformIdempotencyParams) (NetworkPlatformIdempotency, error) {
	row := q.db.QueryRow(ctx, getPlatformIdempotency, arg.ClusterID, arg.OperationKind, arg.IdempotencyKey)
	var i NetworkPlatformIdempotency
	err := row.Scan(
		&i.ClusterID,
		&i.OperationKind,
		&i.IdempotencyKey,
		&i.Fingerprint,
		&i.FingerprintVersion,
		&i.ResourceID,
		&i.OperationID,
		&i.Response,
		&i.CreatedAt,
	)
	return i, err
}

const getPlatformOperation = `-- name: GetPlatformOperation :one
SELECT o.operation_id, o.resource_id, o.kind, o.state, o.reason, o.attempt, o.execution_epoch, o.created_at, o.updated_at, o.completed_at, o.next_attempt_at FROM network_platform_operations o JOIN network_platform_resources r ON r.resource_id=o.resource_id
WHERE r.cluster_id=$1 AND o.operation_id=$2
`

type GetPlatformOperationParams struct {
	ClusterID   string
	OperationID string
}

func (q *Queries) GetPlatformOperation(ctx context.Context, arg GetPlatformOperationParams) (NetworkPlatformOperation, error) {
	row := q.db.QueryRow(ctx, getPlatformOperation, arg.ClusterID, arg.OperationID)
	var i NetworkPlatformOperation
	err := row.Scan(
		&i.OperationID,
		&i.ResourceID,
		&i.Kind,
		&i.State,
		&i.Reason,
		&i.Attempt,
		&i.ExecutionEpoch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const getPublicPool = `-- name: GetPublicPool :one
SELECT resource_id, cluster_id, kind, mode, gateway_id, cidr, ovn_gateway_ip, excluded_ips, vlan_network_id, upstream_gateway_ip, allocation_enabled, config_revision, verification, verification_expires_at, retired, scope, default_vpc_name, default_vpc_uid, intranet_networks FROM network_public_pools WHERE cluster_id=$1 AND resource_id=$2
`

type GetPublicPoolParams struct {
	ClusterID  string
	ResourceID string
}

func (q *Queries) GetPublicPool(ctx context.Context, arg GetPublicPoolParams) (NetworkPublicPool, error) {
	row := q.db.QueryRow(ctx, getPublicPool, arg.ClusterID, arg.ResourceID)
	var i NetworkPublicPool
	err := row.Scan(
		&i.ResourceID,
		&i.ClusterID,
		&i.Kind,
		&i.Mode,
		&i.GatewayID,
		&i.Cidr,
		&i.OvnGatewayIp,
		&i.ExcludedIps,
		&i.VlanNetworkID,
		&i.UpstreamGatewayIp,
		&i.AllocationEnabled,
		&i.ConfigRevision,
		&i.Verification,
		&i.VerificationExpiresAt,
		&i.Retired,
		&i.Scope,
		&i.DefaultVpcName,
		&i.DefaultVpcUid,
		&i.IntranetNetworks,
	)
	return i, err
}

const getVlanNetwork = `-- name: GetVlanNetwork :one
SELECT resource_id, cluster_id, kind, device_id, vlan_id, retired FROM network_vlan_networks WHERE cluster_id=$1 AND resource_id=$2
`

type GetVlanNetworkParams struct {
	ClusterID  string
	ResourceID string
}

func (q *Queries) GetVlanNetwork(ctx context.Context, arg GetVlanNetworkParams) (NetworkVlanNetwork, error) {
	row := q.db.QueryRow(ctx, getVlanNetwork, arg.ClusterID, arg.ResourceID)
	var i NetworkVlanNetwork
	err := row.Scan(
		&i.ResourceID,
		&i.ClusterID,
		&i.Kind,
		&i.DeviceID,
		&i.VlanID,
		&i.Retired,
	)
	return i, err
}

const insertDeviceAdoption = `-- name: InsertDeviceAdoption :exec
INSERT INTO network_device_adoptions(resource_id,cluster_id,device_name,inventory_fingerprint,node_inventory) VALUES($1,$2,$3,$4,$5)
`

type InsertDeviceAdoptionParams struct {
	ResourceID           string
	ClusterID            string
	DeviceName           string
	InventoryFingerprint string
	NodeInventory        []byte
}

func (q *Queries) InsertDeviceAdoption(ctx context.Context, arg InsertDeviceAdoptionParams) error {
	_, err := q.db.Exec(ctx, insertDeviceAdoption,
		arg.ResourceID,
		arg.ClusterID,
		arg.DeviceName,
		arg.InventoryFingerprint,
		arg.NodeInventory,
	)
	return err
}

const insertEgressGateway = `-- name: InsertEgressGateway :exec
INSERT INTO network_egress_gateways(resource_id,cluster_id) VALUES($1,$2)
`

type InsertEgressGatewayParams struct {
	ResourceID string
	ClusterID  string
}

func (q *Queries) InsertEgressGateway(ctx context.Context, arg InsertEgressGatewayParams) error {
	_, err := q.db.Exec(ctx, insertEgressGateway, arg.ResourceID, arg.ClusterID)
	return err
}

const insertIntranetPool = `-- name: InsertIntranetPool :exec
INSERT INTO network_public_pools(resource_id,cluster_id,scope,mode,gateway_id,cidr,ovn_gateway_ip,excluded_ips,default_vpc_name,default_vpc_uid,intranet_networks)
VALUES($1,$2,'intranet','overlay',NULL,$3,$4,$5,$6,$7,$8)
`

type InsertIntranetPoolParams struct {
	ResourceID       string
	ClusterID        string
	Cidr             string
	OvnGatewayIp     string
	ExcludedIps      []string
	DefaultVpcName   string
	DefaultVpcUid    string
	IntranetNetworks []string
}

func (q *Queries) InsertIntranetPool(ctx context.Context, arg InsertIntranetPoolParams) error {
	_, err := q.db.Exec(ctx, insertIntranetPool,
		arg.ResourceID,
		arg.ClusterID,
		arg.Cidr,
		arg.OvnGatewayIp,
		arg.ExcludedIps,
		arg.DefaultVpcName,
		arg.DefaultVpcUid,
		arg.IntranetNetworks,
	)
	return err
}

const insertPlatformHistory = `-- name: InsertPlatformHistory :exec
INSERT INTO network_platform_history(history_id,resource_id,operation_id,event,resource_state,operation_state,reason,actor_ref,caller_ref,created_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10)
`

type InsertPlatformHistoryParams struct {
	HistoryID      string
	ResourceID     string
	OperationID    *string
	Event          string
	ResourceState  string
	OperationState string
	Reason         string
	ActorRef       string
	CallerRef      string
	CreatedAt      time.Time
}

func (q *Queries) InsertPlatformHistory(ctx context.Context, arg InsertPlatformHistoryParams) error {
	_, err := q.db.Exec(ctx, insertPlatformHistory,
		arg.HistoryID,
		arg.ResourceID,
		arg.OperationID,
		arg.Event,
		arg.ResourceState,
		arg.OperationState,
		arg.Reason,
		arg.ActorRef,
		arg.CallerRef,
		arg.CreatedAt,
	)
	return err
}

const insertPlatformIdempotency = `-- name: InsertPlatformIdempotency :exec
INSERT INTO network_platform_idempotency(cluster_id,operation_kind,idempotency_key,fingerprint,resource_id,operation_id,response,created_at)
VALUES($1,$2,$3,$4,$5,$6,$7,$8)
`

type InsertPlatformIdempotencyParams struct {
	ClusterID      string
	OperationKind  string
	IdempotencyKey string
	Fingerprint    string
	ResourceID     string
	OperationID    string
	Response       []byte
	CreatedAt      time.Time
}

func (q *Queries) InsertPlatformIdempotency(ctx context.Context, arg InsertPlatformIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertPlatformIdempotency,
		arg.ClusterID,
		arg.OperationKind,
		arg.IdempotencyKey,
		arg.Fingerprint,
		arg.ResourceID,
		arg.OperationID,
		arg.Response,
		arg.CreatedAt,
	)
	return err
}

const insertPlatformOperation = `-- name: InsertPlatformOperation :exec
INSERT INTO network_platform_operations(operation_id,resource_id,kind,state,created_at,updated_at,completed_at,next_attempt_at)
VALUES($1,$2,$3,$4,$5,$5,$6,$7)
`

type InsertPlatformOperationParams struct {
	OperationID   string
	ResourceID    string
	Kind          string
	State         string
	CreatedAt     time.Time
	CompletedAt   *time.Time
	NextAttemptAt *time.Time
}

func (q *Queries) InsertPlatformOperation(ctx context.Context, arg InsertPlatformOperationParams) error {
	_, err := q.db.Exec(ctx, insertPlatformOperation,
		arg.OperationID,
		arg.ResourceID,
		arg.Kind,
		arg.State,
		arg.CreatedAt,
		arg.CompletedAt,
		arg.NextAttemptAt,
	)
	return err
}

const insertPlatformReconciliation = `-- name: InsertPlatformReconciliation :exec
INSERT INTO network_platform_reconciliations(resource_id,next_run_at) VALUES($1,$2)
`

type InsertPlatformReconciliationParams struct {
	ResourceID string
	NextRunAt  time.Time
}

func (q *Queries) InsertPlatformReconciliation(ctx context.Context, arg InsertPlatformReconciliationParams) error {
	_, err := q.db.Exec(ctx, insertPlatformReconciliation, arg.ResourceID, arg.NextRunAt)
	return err
}

const insertPlatformResource = `-- name: InsertPlatformResource :one
INSERT INTO network_platform_resources(resource_id,kind,cluster_id,name,description,state,created_at,updated_at,last_operation_id,provider_name,binding_id)
VALUES($1,$2,$3,$4,$5,'provisioning',$6,$6,$7,$8,$9) RETURNING resource_id, kind, cluster_id, name, description, state, reason, version, created_at, updated_at, observed_at, last_operation_id, provider_name, provider_uid, provider_images, binding_id, pending_action, pending_since
`

type InsertPlatformResourceParams struct {
	ResourceID      string
	Kind            string
	ClusterID       string
	Name            string
	Description     string
	CreatedAt       time.Time
	LastOperationID string
	ProviderName    string
	BindingID       string
}

func (q *Queries) InsertPlatformResource(ctx context.Context, arg InsertPlatformResourceParams) (NetworkPlatformResource, error) {
	row := q.db.QueryRow(ctx, insertPlatformResource,
		arg.ResourceID,
		arg.Kind,
		arg.ClusterID,
		arg.Name,
		arg.Description,
		arg.CreatedAt,
		arg.LastOperationID,
		arg.ProviderName,
		arg.BindingID,
	)
	var i NetworkPlatformResource
	err := row.Scan(
		&i.ResourceID,
		&i.Kind,
		&i.ClusterID,
		&i.Name,
		&i.Description,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.ProviderName,
		&i.ProviderUid,
		&i.ProviderImages,
		&i.BindingID,
		&i.PendingAction,
		&i.PendingSince,
	)
	return i, err
}

const insertPublicPool = `-- name: InsertPublicPool :exec
INSERT INTO network_public_pools(resource_id,cluster_id,mode,gateway_id,cidr,ovn_gateway_ip,excluded_ips,vlan_network_id,upstream_gateway_ip)
VALUES($1,$2,$3,$4,$5,$6,$7,NULLIF($8::text,''),NULLIF($9::text,''))
`

type InsertPublicPoolParams struct {
	ResourceID        string
	ClusterID         string
	Mode              string
	GatewayID         *string
	Cidr              string
	OvnGatewayIp      string
	ExcludedIps       []string
	VlanNetworkID     string
	UpstreamGatewayIp string
}

func (q *Queries) InsertPublicPool(ctx context.Context, arg InsertPublicPoolParams) error {
	_, err := q.db.Exec(ctx, insertPublicPool,
		arg.ResourceID,
		arg.ClusterID,
		arg.Mode,
		arg.GatewayID,
		arg.Cidr,
		arg.OvnGatewayIp,
		arg.ExcludedIps,
		arg.VlanNetworkID,
		arg.UpstreamGatewayIp,
	)
	return err
}

const insertVlanNetwork = `-- name: InsertVlanNetwork :exec
INSERT INTO network_vlan_networks(resource_id,cluster_id,device_id,vlan_id) VALUES($1,$2,$3,$4)
`

type InsertVlanNetworkParams struct {
	ResourceID string
	ClusterID  string
	DeviceID   string
	VlanID     int32
}

func (q *Queries) InsertVlanNetwork(ctx context.Context, arg InsertVlanNetworkParams) error {
	_, err := q.db.Exec(ctx, insertVlanNetwork,
		arg.ResourceID,
		arg.ClusterID,
		arg.DeviceID,
		arg.VlanID,
	)
	return err
}

const listIntranetPools = `-- name: ListIntranetPools :many
SELECT r.resource_id, r.kind, r.cluster_id, r.name, r.description, r.state, r.reason, r.version, r.created_at, r.updated_at, r.observed_at, r.last_operation_id, r.provider_name, r.provider_uid, r.provider_images, r.binding_id, r.pending_action, r.pending_since FROM network_platform_resources r JOIN network_public_pools p ON p.cluster_id=r.cluster_id AND p.resource_id=r.resource_id
WHERE r.cluster_id=$1 AND p.scope='intranet'
 AND ($2::text='' OR r.name=$2)
 AND (($3::text='' AND r.state<>'deleted') OR r.state=$3)
 AND ($4::text='' OR (r.created_at,r.resource_id)<($5::timestamptz,$4::text))
ORDER BY r.created_at DESC,r.resource_id DESC LIMIT $6::integer
`

type ListIntranetPoolsParams struct {
	ClusterID      string
	NameFilter     string
	StateFilter    string
	AfterID        string
	AfterCreatedAt time.Time
	MaxResults     int32
}

func (q *Queries) ListIntranetPools(ctx context.Context, arg ListIntranetPoolsParams) ([]NetworkPlatformResource, error) {
	rows, err := q.db.Query(ctx, listIntranetPools,
		arg.ClusterID,
		arg.NameFilter,
		arg.StateFilter,
		arg.AfterID,
		arg.AfterCreatedAt,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetworkPlatformResource{}
	for rows.Next() {
		var i NetworkPlatformResource
		if err := rows.Scan(
			&i.ResourceID,
			&i.Kind,
			&i.ClusterID,
			&i.Name,
			&i.Description,
			&i.State,
			&i.Reason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ObservedAt,
			&i.LastOperationID,
			&i.ProviderName,
			&i.ProviderUid,
			&i.ProviderImages,
			&i.BindingID,
			&i.PendingAction,
			&i.PendingSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatform = `-- name: ListPlatform :many
SELECT r.resource_id, r.kind, r.cluster_id, r.name, r.description, r.state, r.reason, r.version, r.created_at, r.updated_at, r.observed_at, r.last_operation_id, r.provider_name, r.provider_uid, r.provider_images, r.binding_id, r.pending_action, r.pending_since FROM network_platform_resources r WHERE r.cluster_id=$1 AND r.kind=$2
 AND (r.kind<>'public_pool' OR EXISTS (SELECT 1 FROM network_public_pools pool WHERE pool.cluster_id=r.cluster_id AND pool.resource_id=r.resource_id AND pool.scope='public'))
 AND ($3::text='' OR r.name=$3)
 AND (($4::text='' AND r.state<>'deleted') OR r.state=$4)
 AND ($5::text='' OR (r.created_at,r.resource_id)<($6::timestamptz,$5::text))
ORDER BY r.created_at DESC,r.resource_id DESC LIMIT $7::integer
`

type ListPlatformParams struct {
	ClusterID      string
	Kind           string
	NameFilter     string
	StateFilter    string
	AfterID        string
	AfterCreatedAt time.Time
	MaxResults     int32
}

func (q *Queries) ListPlatform(ctx context.Context, arg ListPlatformParams) ([]NetworkPlatformResource, error) {
	rows, err := q.db.Query(ctx, listPlatform,
		arg.ClusterID,
		arg.Kind,
		arg.NameFilter,
		arg.StateFilter,
		arg.AfterID,
		arg.AfterCreatedAt,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetworkPlatformResource{}
	for rows.Next() {
		var i NetworkPlatformResource
		if err := rows.Scan(
			&i.ResourceID,
			&i.Kind,
			&i.ClusterID,
			&i.Name,
			&i.Description,
			&i.State,
			&i.Reason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ObservedAt,
			&i.LastOperationID,
			&i.ProviderName,
			&i.ProviderUid,
			&i.ProviderImages,
			&i.BindingID,
			&i.PendingAction,
			&i.PendingSince,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockPlatform = `-- name: LockPlatform :one
SELECT resource_id, kind, cluster_id, name, description, state, reason, version, created_at, updated_at, observed_at, last_operation_id, provider_name, provider_uid, provider_images, binding_id, pending_action, pending_since FROM network_platform_resources WHERE cluster_id=$1 AND kind=$2 AND resource_id=$3 FOR UPDATE
`

type LockPlatformParams struct {
	ClusterID  string
	Kind       string
	ResourceID string
}

func (q *Queries) LockPlatform(ctx context.Context, arg LockPlatformParams) (NetworkPlatformResource, error) {
	row := q.db.QueryRow(ctx, lockPlatform, arg.ClusterID, arg.Kind, arg.ResourceID)
	var i NetworkPlatformResource
	err := row.Scan(
		&i.ResourceID,
		&i.Kind,
		&i.ClusterID,
		&i.Name,
		&i.Description,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.ProviderName,
		&i.ProviderUid,
		&i.ProviderImages,
		&i.BindingID,
		&i.PendingAction,
		&i.PendingSince,
	)
	return i, err
}

const lockPlatformCluster = `-- name: LockPlatformCluster :exec
SELECT pg_advisory_xact_lock(hashtextextended('platform-cluster:'||$1::text,0))
`

type LockPlatformClusterParams struct {
	ClusterID string
}

func (q *Queries) LockPlatformCluster(ctx context.Context, arg LockPlatformClusterParams) error {
	_, err := q.db.Exec(ctx, lockPlatformCluster, arg.ClusterID)
	return err
}

const lockPlatformKey = `-- name: LockPlatformKey :exec
SELECT pg_advisory_xact_lock(hashtextextended('platform:'||$1::text||':'||$2::text||':'||$3::text,0))
`

type LockPlatformKeyParams struct {
	ClusterID      string
	OperationKind  string
	IdempotencyKey string
}

func (q *Queries) LockPlatformKey(ctx context.Context, arg LockPlatformKeyParams) error {
	_, err := q.db.Exec(ctx, lockPlatformKey, arg.ClusterID, arg.OperationKind, arg.IdempotencyKey)
	return err
}

const lockPublicPool = `-- name: LockPublicPool :one
SELECT resource_id, cluster_id, kind, mode, gateway_id, cidr, ovn_gateway_ip, excluded_ips, vlan_network_id, upstream_gateway_ip, allocation_enabled, config_revision, verification, verification_expires_at, retired, scope, default_vpc_name, default_vpc_uid, intranet_networks FROM network_public_pools WHERE cluster_id=$1 AND resource_id=$2 FOR UPDATE
`

type LockPublicPoolParams struct {
	ClusterID  string
	ResourceID string
}

func (q *Queries) LockPublicPool(ctx context.Context, arg LockPublicPoolParams) (NetworkPublicPool, error) {
	row := q.db.QueryRow(ctx, lockPublicPool, arg.ClusterID, arg.ResourceID)
	var i NetworkPublicPool
	err := row.Scan(
		&i.ResourceID,
		&i.ClusterID,
		&i.Kind,
		&i.Mode,
		&i.GatewayID,
		&i.Cidr,
		&i.OvnGatewayIp,
		&i.ExcludedIps,
		&i.VlanNetworkID,
		&i.UpstreamGatewayIp,
		&i.AllocationEnabled,
		&i.ConfigRevision,
		&i.Verification,
		&i.VerificationExpiresAt,
		&i.Retired,
		&i.Scope,
		&i.DefaultVpcName,
		&i.DefaultVpcUid,
		&i.IntranetNetworks,
	)
	return i, err
}

const notifyPlatform = `-- name: NotifyPlatform :execrows
UPDATE network_platform_reconciliations SET requested_generation=requested_generation+1,
 next_run_at=greatest(retry_not_before,least(next_run_at,clock_timestamp())) WHERE resource_id=$1
`

type NotifyPlatformParams struct {
	ResourceID string
}

func (q *Queries) NotifyPlatform(ctx context.Context, arg NotifyPlatformParams) (int64, error) {
	result, err := q.db.Exec(ctx, notifyPlatform, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const observationPlatformResources = `-- name: ObservationPlatformResources :many
SELECT p.resource_id, p.kind, p.cluster_id, p.name, p.description, p.state, p.reason, p.version, p.created_at, p.updated_at, p.observed_at, p.last_operation_id, p.provider_name, p.provider_uid, p.provider_images, p.binding_id, p.pending_action, p.pending_since,r.requested_generation FROM network_platform_resources p JOIN network_platform_reconciliations r ON r.resource_id=p.resource_id WHERE p.cluster_id=$1
`

type ObservationPlatformResourcesParams struct {
	ClusterID string
}

type ObservationPlatformResourcesRow struct {
	ResourceID          string
	Kind                string
	ClusterID           string
	Name                string
	Description         string
	State               string
	Reason              string
	Version             int64
	CreatedAt           time.Time
	UpdatedAt           time.Time
	ObservedAt          *time.Time
	LastOperationID     string
	ProviderName        string
	ProviderUid         string
	ProviderImages      []string
	BindingID           string
	PendingAction       string
	PendingSince        *time.Time
	RequestedGeneration int64
}

func (q *Queries) ObservationPlatformResources(ctx context.Context, arg ObservationPlatformResourcesParams) ([]ObservationPlatformResourcesRow, error) {
	rows, err := q.db.Query(ctx, observationPlatformResources, arg.ClusterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ObservationPlatformResourcesRow{}
	for rows.Next() {
		var i ObservationPlatformResourcesRow
		if err := rows.Scan(
			&i.ResourceID,
			&i.Kind,
			&i.ClusterID,
			&i.Name,
			&i.Description,
			&i.State,
			&i.Reason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ObservedAt,
			&i.LastOperationID,
			&i.ProviderName,
			&i.ProviderUid,
			&i.ProviderImages,
			&i.BindingID,
			&i.PendingAction,
			&i.PendingSince,
			&i.RequestedGeneration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const platformPoolVPCOverlaps = `-- name: PlatformPoolVPCOverlaps :one
SELECT count(*)::bigint FROM network_vpcs v JOIN network_provider_bindings b ON b.tenant_id=v.tenant_id AND b.vpc_id=v.vpc_id AND b.resource_kind='vpc'
WHERE b.cluster_id=$1 AND v.state<>'deleted' AND v.cidr::cidr && $2::cidr
`

type PlatformPoolVPCOverlapsParams struct {
	ClusterID string
	Cidr      netip.Prefix
}

func (q *Queries) PlatformPoolVPCOverlaps(ctx context.Context, arg PlatformPoolVPCOverlapsParams) (int64, error) {
	row := q.db.QueryRow(ctx, platformPoolVPCOverlaps, arg.ClusterID, arg.Cidr)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const publicPoolOverlaps = `-- name: PublicPoolOverlaps :one
SELECT count(*)::bigint FROM network_public_pools p JOIN network_platform_resources r ON r.cluster_id=p.cluster_id AND r.resource_id=p.resource_id
WHERE p.cluster_id=$1 AND r.state<>'deleted' AND p.cidr::cidr && $2::cidr
`

type PublicPoolOverlapsParams struct {
	ClusterID string
	Cidr      netip.Prefix
}

func (q *Queries) PublicPoolOverlaps(ctx context.Context, arg PublicPoolOverlapsParams) (int64, error) {
	row := q.db.QueryRow(ctx, publicPoolOverlaps, arg.ClusterID, arg.Cidr)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const publicPoolTopology = `-- name: PublicPoolTopology :one
SELECT p.resource_id,p.cluster_id,p.config_revision,p.mode,p.gateway_id,p.cidr,p.ovn_gateway_ip,p.excluded_ips,p.vlan_network_id,p.upstream_gateway_ip,
 r.provider_uid AS pool_uid,r.provider_images,COALESCE(g.provider_uid,'')::text AS gateway_uid,COALESCE(v.provider_uid,'')::text AS vlan_uid,
 COALESCE(d.provider_uid,'')::text AS device_config_uid
FROM network_public_pools p
JOIN network_platform_resources r ON r.cluster_id=p.cluster_id AND r.resource_id=p.resource_id
LEFT JOIN network_platform_resources g ON g.cluster_id=p.cluster_id AND g.resource_id=p.gateway_id
LEFT JOIN network_platform_resources v ON v.cluster_id=p.cluster_id AND v.resource_id=p.vlan_network_id
LEFT JOIN network_vlan_networks vl ON vl.cluster_id=p.cluster_id AND vl.resource_id=p.vlan_network_id
LEFT JOIN network_platform_resources d ON d.cluster_id=vl.cluster_id AND d.resource_id=vl.device_id
WHERE p.cluster_id=$1 AND p.resource_id=$2
`

type PublicPoolTopologyParams struct {
	ClusterID  string
	ResourceID string
}

type PublicPoolTopologyRow struct {
	ResourceID        string
	ClusterID         string
	ConfigRevision    int64
	Mode              string
	GatewayID         *string
	Cidr              string
	OvnGatewayIp      string
	ExcludedIps       []string
	VlanNetworkID     *string
	UpstreamGatewayIp *string
	PoolUid           string
	ProviderImages    []string
	GatewayUid        string
	VlanUid           string
	DeviceConfigUid   string
}

func (q *Queries) PublicPoolTopology(ctx context.Context, arg PublicPoolTopologyParams) (PublicPoolTopologyRow, error) {
	row := q.db.QueryRow(ctx, publicPoolTopology, arg.ClusterID, arg.ResourceID)
	var i PublicPoolTopologyRow
	err := row.Scan(
		&i.ResourceID,
		&i.ClusterID,
		&i.ConfigRevision,
		&i.Mode,
		&i.GatewayID,
		&i.Cidr,
		&i.OvnGatewayIp,
		&i.ExcludedIps,
		&i.VlanNetworkID,
		&i.UpstreamGatewayIp,
		&i.PoolUid,
		&i.ProviderImages,
		&i.GatewayUid,
		&i.VlanUid,
		&i.DeviceConfigUid,
	)
	return i, err
}

const releasePlatformLease = `-- name: ReleasePlatformLease :execrows
UPDATE network_platform_reconciliations SET lease_owner=NULL,lease_until=NULL,
 processed_generation=greatest(processed_generation,$1::bigint),
 evidence_hash=CASE WHEN $2::boolean THEN $3::text ELSE evidence_hash END,
 evidence_applied_at=CASE WHEN $2::boolean THEN clock_timestamp() ELSE evidence_applied_at END,
 retry_not_before=CASE WHEN $4::boolean THEN clock_timestamp()+$5::bigint*interval '1 microsecond' ELSE '1970-01-01 UTC'::timestamptz END,
 next_run_at=CASE WHEN requested_generation>$1::bigint AND NOT $4::boolean THEN clock_timestamp() ELSE clock_timestamp()+$5::bigint*interval '1 microsecond' END
WHERE resource_id=$6 AND lease_owner=$7::uuid AND lease_epoch=$8 AND lease_until>clock_timestamp()
`

type ReleasePlatformLeaseParams struct {
	CoveredGeneration int64
	Observed          bool
	EvidenceHash      string
	Backoff           bool
	DelayMicros       int64
	ResourceID        string
	Owner             string
	Epoch             int64
}

func (q *Queries) ReleasePlatformLease(ctx context.Context, arg ReleasePlatformLeaseParams) (int64, error) {
	result, err := q.db.Exec(ctx, releasePlatformLease,
		arg.CoveredGeneration,
		arg.Observed,
		arg.EvidenceHash,
		arg.Backoff,
		arg.DelayMicros,
		arg.ResourceID,
		arg.Owner,
		arg.Epoch,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retirePublicPoolSlot = `-- name: RetirePublicPoolSlot :execrows
UPDATE network_public_pools SET retired=true WHERE cluster_id=$1 AND resource_id=$2
`

type RetirePublicPoolSlotParams struct {
	ClusterID  string
	ResourceID string
}

func (q *Queries) RetirePublicPoolSlot(ctx context.Context, arg RetirePublicPoolSlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, retirePublicPoolSlot, arg.ClusterID, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const retireVlanSlot = `-- name: RetireVlanSlot :execrows
UPDATE network_vlan_networks SET retired=true WHERE cluster_id=$1 AND resource_id=$2
`

type RetireVlanSlotParams struct {
	ClusterID  string
	ResourceID string
}

func (q *Queries) RetireVlanSlot(ctx context.Context, arg RetireVlanSlotParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireVlanSlot, arg.ClusterID, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const runPlatformOperation = `-- name: RunPlatformOperation :one
UPDATE network_platform_operations SET state='running',attempt=attempt+1,execution_epoch=$1,updated_at=clock_timestamp()
WHERE operation_id=$2 AND resource_id=$3 AND completed_at IS NULL RETURNING operation_id, resource_id, kind, state, reason, attempt, execution_epoch, created_at, updated_at, completed_at, next_attempt_at
`

type RunPlatformOperationParams struct {
	Epoch       int64
	OperationID string
	ResourceID  string
}

func (q *Queries) RunPlatformOperation(ctx context.Context, arg RunPlatformOperationParams) (NetworkPlatformOperation, error) {
	row := q.db.QueryRow(ctx, runPlatformOperation, arg.Epoch, arg.OperationID, arg.ResourceID)
	var i NetworkPlatformOperation
	err := row.Scan(
		&i.OperationID,
		&i.ResourceID,
		&i.Kind,
		&i.State,
		&i.Reason,
		&i.Attempt,
		&i.ExecutionEpoch,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
		&i.NextAttemptAt,
	)
	return i, err
}

const saveDeviceProgress = `-- name: SaveDeviceProgress :execrows
UPDATE network_device_adoptions SET node_progress=$3 WHERE cluster_id=$1 AND resource_id=$2
`

type SaveDeviceProgressParams struct {
	ClusterID    string
	ResourceID   string
	NodeProgress []byte
}

func (q *Queries) SaveDeviceProgress(ctx context.Context, arg SaveDeviceProgressParams) (int64, error) {
	result, err := q.db.Exec(ctx, saveDeviceProgress, arg.ClusterID, arg.ResourceID, arg.NodeProgress)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const savePlatformImages = `-- name: SavePlatformImages :execrows
UPDATE network_platform_resources SET provider_images=$3 WHERE cluster_id=$1 AND resource_id=$2
`

type SavePlatformImagesParams struct {
	ClusterID      string
	ResourceID     string
	ProviderImages []string
}

func (q *Queries) SavePlatformImages(ctx context.Context, arg SavePlatformImagesParams) (int64, error) {
	result, err := q.db.Exec(ctx, savePlatformImages, arg.ClusterID, arg.ResourceID, arg.ProviderImages)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const savePoolVerification = `-- name: SavePoolVerification :execrows
UPDATE network_public_pools SET verification=$3,verification_expires_at=$4 WHERE cluster_id=$1 AND resource_id=$2
`

type SavePoolVerificationParams struct {
	ClusterID             string
	ResourceID            string
	Verification          []byte
	VerificationExpiresAt *time.Time
}

func (q *Queries) SavePoolVerification(ctx context.Context, arg SavePoolVerificationParams) (int64, error) {
	result, err := q.db.Exec(ctx, savePoolVerification,
		arg.ClusterID,
		arg.ResourceID,
		arg.Verification,
		arg.VerificationExpiresAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const schedulePlatform = `-- name: SchedulePlatform :execrows
UPDATE network_platform_reconciliations SET next_run_at=clock_timestamp(),lease_owner=NULL,lease_until=NULL,lease_epoch=lease_epoch+1 WHERE resource_id=$1
`

type SchedulePlatformParams struct {
	ResourceID string
}

func (q *Queries) SchedulePlatform(ctx context.Context, arg SchedulePlatformParams) (int64, error) {
	result, err := q.db.Exec(ctx, schedulePlatform, arg.ResourceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setDefaultIntranetPool = `-- name: SetDefaultIntranetPool :exec
INSERT INTO network_default_intranet_pools(cluster_id,pool_id) VALUES($1,$2)
ON CONFLICT(cluster_id) DO UPDATE SET pool_id=excluded.pool_id,version=network_default_intranet_pools.version+1
`

type SetDefaultIntranetPoolParams struct {
	ClusterID string
	PoolID    string
}

func (q *Queries) SetDefaultIntranetPool(ctx context.Context, arg SetDefaultIntranetPoolParams) error {
	_, err := q.db.Exec(ctx, setDefaultIntranetPool, arg.ClusterID, arg.PoolID)
	return err
}

const setDefaultPublicPool = `-- name: SetDefaultPublicPool :exec
INSERT INTO network_default_public_pools(cluster_id,pool_id) VALUES($1,$2)
ON CONFLICT(cluster_id) DO UPDATE SET pool_id=excluded.pool_id,version=network_default_public_pools.version+1
`

type SetDefaultPublicPoolParams struct {
	ClusterID string
	PoolID    string
}

func (q *Queries) SetDefaultPublicPool(ctx context.Context, arg SetDefaultPublicPoolParams) error {
	_, err := q.db.Exec(ctx, setDefaultPublicPool, arg.ClusterID, arg.PoolID)
	return err
}

const setPlatformIntent = `-- name: SetPlatformIntent :one
UPDATE network_platform_resources SET state=$1,reason='',last_operation_id=$2,version=version+1,updated_at=clock_timestamp()
WHERE cluster_id=$3 AND resource_id=$4 AND version=$5 RETURNING resource_id, kind, cluster_id, name, description, state, reason, version, created_at, updated_at, observed_at, last_operation_id, provider_name, provider_uid, provider_images, binding_id, pending_action, pending_since
`

type SetPlatformIntentParams struct {
	State       string
	OperationID string
	ClusterID   string
	ResourceID  string
	Version     int64
}

func (q *Queries) SetPlatformIntent(ctx context.Context, arg SetPlatformIntentParams) (NetworkPlatformResource, error) {
	row := q.db.QueryRow(ctx, setPlatformIntent,
		arg.State,
		arg.OperationID,
		arg.ClusterID,
		arg.ResourceID,
		arg.Version,
	)
	var i NetworkPlatformResource
	err := row.Scan(
		&i.ResourceID,
		&i.Kind,
		&i.ClusterID,
		&i.Name,
		&i.Description,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
		&i.ProviderName,
		&i.ProviderUid,
		&i.ProviderImages,
		&i.BindingID,
		&i.PendingAction,
		&i.PendingSince,
	)
	return i, err
}

const setPoolAllocation = `-- name: SetPoolAllocation :execrows
UPDATE network_public_pools SET allocation_enabled=$3 WHERE cluster_id=$1 AND resource_id=$2
`

type SetPoolAllocationParams struct {
	ClusterID         string
	ResourceID        string
	AllocationEnabled bool
}

func (q *Queries) SetPoolAllocation(ctx context.Context, arg SetPoolAllocationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setPoolAllocation, arg.ClusterID, arg.ResourceID, arg.AllocationEnabled)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
