// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: subnets.sql

package sqlcgen

import (
	"context"
	"net/netip"
	"time"
)

const admitSubnetDeletion = `-- name: AdmitSubnetDeletion :one
UPDATE network_subnets SET state='deleting',reason='',last_operation_id=$1,version=version+1,updated_at=clock_timestamp()
WHERE tenant_id=$2 AND subnet_id=$3 AND version=$4 RETURNING tenant_id, subnet_id, vpc_id, name, description, cidr, gateway, state, reason, version, created_at, updated_at, observed_at, last_operation_id
`

type AdmitSubnetDeletionParams struct {
	OperationID string
	TenantID    string
	SubnetID    string
	Version     int64
}

func (q *Queries) AdmitSubnetDeletion(ctx context.Context, arg AdmitSubnetDeletionParams) (NetworkSubnet, error) {
	row := q.db.QueryRow(ctx, admitSubnetDeletion,
		arg.OperationID,
		arg.TenantID,
		arg.SubnetID,
		arg.Version,
	)
	var i NetworkSubnet
	err := row.Scan(
		&i.TenantID,
		&i.SubnetID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.Gateway,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
	)
	return i, err
}

const advanceSubnet = `-- name: AdvanceSubnet :one
UPDATE network_subnets SET state=$1,reason=$2,version=version+1,updated_at=clock_timestamp(),
 observed_at=CASE WHEN $3::boolean THEN $4::timestamptz ELSE observed_at END
WHERE tenant_id=$5 AND subnet_id=$6 AND version=$7 RETURNING tenant_id, subnet_id, vpc_id, name, description, cidr, gateway, state, reason, version, created_at, updated_at, observed_at, last_operation_id
`

type AdvanceSubnetParams struct {
	State      string
	Reason     string
	Observed   bool
	ObservedAt *time.Time
	TenantID   string
	SubnetID   string
	Version    int64
}

func (q *Queries) AdvanceSubnet(ctx context.Context, arg AdvanceSubnetParams) (NetworkSubnet, error) {
	row := q.db.QueryRow(ctx, advanceSubnet,
		arg.State,
		arg.Reason,
		arg.Observed,
		arg.ObservedAt,
		arg.TenantID,
		arg.SubnetID,
		arg.Version,
	)
	var i NetworkSubnet
	err := row.Scan(
		&i.TenantID,
		&i.SubnetID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.Gateway,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
	)
	return i, err
}

const countBlockingSubnets = `-- name: CountBlockingSubnets :one
SELECT count(*)::bigint FROM network_subnets s WHERE s.tenant_id=$1 AND s.vpc_id=$2
 AND (s.state<>'deleted' OR EXISTS(SELECT 1 FROM network_attachments a WHERE a.tenant_id=s.tenant_id AND a.subnet_id=s.subnet_id AND (a.state<>'released' OR a.protocol_blocked)))
`

type CountBlockingSubnetsParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) CountBlockingSubnets(ctx context.Context, arg CountBlockingSubnetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countBlockingSubnets, arg.TenantID, arg.VpcID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countListedSubnets = `-- name: CountListedSubnets :one
SELECT count(*) FROM network_subnets WHERE tenant_id=$1
 AND ($2::text='' OR vpc_id=$2)
 AND ($3::text='' OR name=$3)
 AND (($4::text='' AND state<>'deleted') OR state=$4)
`

type CountListedSubnetsParams struct {
	TenantID    string
	VpcFilter   string
	NameFilter  string
	StateFilter string
}

func (q *Queries) CountListedSubnets(ctx context.Context, arg CountListedSubnetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countListedSubnets,
		arg.TenantID,
		arg.VpcFilter,
		arg.NameFilter,
		arg.StateFilter,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSubnets = `-- name: CountSubnets :one
SELECT count(*)::bigint FROM network_subnets WHERE tenant_id=$1 AND vpc_id=$2 AND state<>'deleted'
`

type CountSubnetsParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) CountSubnets(ctx context.Context, arg CountSubnetsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSubnets, arg.TenantID, arg.VpcID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getSubnet = `-- name: GetSubnet :one
SELECT tenant_id, subnet_id, vpc_id, name, description, cidr, gateway, state, reason, version, created_at, updated_at, observed_at, last_operation_id FROM network_subnets WHERE tenant_id=$1 AND subnet_id=$2
`

type GetSubnetParams struct {
	TenantID string
	SubnetID string
}

func (q *Queries) GetSubnet(ctx context.Context, arg GetSubnetParams) (NetworkSubnet, error) {
	row := q.db.QueryRow(ctx, getSubnet, arg.TenantID, arg.SubnetID)
	var i NetworkSubnet
	err := row.Scan(
		&i.TenantID,
		&i.SubnetID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.Gateway,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
	)
	return i, err
}

const getSubnetIdempotency = `-- name: GetSubnetIdempotency :one
SELECT tenant_id, operation_kind, idempotency_key, fingerprint, fingerprint_version, vpc_id, operation_id, response, created_at, subnet_id, eip_id, snat_id, lb_id FROM network_idempotency WHERE tenant_id=$1 AND operation_kind='create_subnet' AND idempotency_key=$2
`

type GetSubnetIdempotencyParams struct {
	TenantID       string
	IdempotencyKey string
}

func (q *Queries) GetSubnetIdempotency(ctx context.Context, arg GetSubnetIdempotencyParams) (NetworkIdempotency, error) {
	row := q.db.QueryRow(ctx, getSubnetIdempotency, arg.TenantID, arg.IdempotencyKey)
	var i NetworkIdempotency
	err := row.Scan(
		&i.TenantID,
		&i.OperationKind,
		&i.IdempotencyKey,
		&i.Fingerprint,
		&i.FingerprintVersion,
		&i.VpcID,
		&i.OperationID,
		&i.Response,
		&i.CreatedAt,
		&i.SubnetID,
		&i.EipID,
		&i.SnatID,
		&i.LbID,
	)
	return i, err
}

const insertSubnet = `-- name: InsertSubnet :one
INSERT INTO network_subnets (tenant_id,subnet_id,vpc_id,name,description,cidr,gateway,state,created_at,updated_at,last_operation_id)
VALUES ($1,$2,$3,$4,$5,$6,$7,'provisioning',$8,$8,$9) RETURNING tenant_id, subnet_id, vpc_id, name, description, cidr, gateway, state, reason, version, created_at, updated_at, observed_at, last_operation_id
`

type InsertSubnetParams struct {
	TenantID        string
	SubnetID        string
	VpcID           string
	Name            string
	Description     string
	Cidr            string
	Gateway         string
	CreatedAt       time.Time
	LastOperationID string
}

func (q *Queries) InsertSubnet(ctx context.Context, arg InsertSubnetParams) (NetworkSubnet, error) {
	row := q.db.QueryRow(ctx, insertSubnet,
		arg.TenantID,
		arg.SubnetID,
		arg.VpcID,
		arg.Name,
		arg.Description,
		arg.Cidr,
		arg.Gateway,
		arg.CreatedAt,
		arg.LastOperationID,
	)
	var i NetworkSubnet
	err := row.Scan(
		&i.TenantID,
		&i.SubnetID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.Gateway,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
	)
	return i, err
}

const insertSubnetIdempotency = `-- name: InsertSubnetIdempotency :exec
INSERT INTO network_idempotency (tenant_id,operation_kind,idempotency_key,fingerprint,fingerprint_version,subnet_id,operation_id,response,created_at)
VALUES ($1,'create_subnet',$2,$3,1,$4::text,$5,$6,$7)
`

type InsertSubnetIdempotencyParams struct {
	TenantID       string
	IdempotencyKey string
	Fingerprint    string
	SubnetID       string
	OperationID    string
	Response       []byte
	CreatedAt      time.Time
}

func (q *Queries) InsertSubnetIdempotency(ctx context.Context, arg InsertSubnetIdempotencyParams) error {
	_, err := q.db.Exec(ctx, insertSubnetIdempotency,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.Fingerprint,
		arg.SubnetID,
		arg.OperationID,
		arg.Response,
		arg.CreatedAt,
	)
	return err
}

const listSubnets = `-- name: ListSubnets :many
SELECT tenant_id, subnet_id, vpc_id, name, description, cidr, gateway, state, reason, version, created_at, updated_at, observed_at, last_operation_id FROM network_subnets WHERE tenant_id=$1
 AND ($2::text='' OR vpc_id=$2)
 AND ($3::text='' OR name=$3)
 AND (($4::text='' AND state<>'deleted') OR state=$4)
 AND ($5::text='' OR (created_at,subnet_id)<($6::timestamptz,$5::text))
ORDER BY created_at DESC,subnet_id DESC LIMIT $7::integer
`

type ListSubnetsParams struct {
	TenantID       string
	VpcFilter      string
	NameFilter     string
	StateFilter    string
	AfterID        string
	AfterCreatedAt time.Time
	MaxResults     int32
}

func (q *Queries) ListSubnets(ctx context.Context, arg ListSubnetsParams) ([]NetworkSubnet, error) {
	rows, err := q.db.Query(ctx, listSubnets,
		arg.TenantID,
		arg.VpcFilter,
		arg.NameFilter,
		arg.StateFilter,
		arg.AfterID,
		arg.AfterCreatedAt,
		arg.MaxResults,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NetworkSubnet{}
	for rows.Next() {
		var i NetworkSubnet
		if err := rows.Scan(
			&i.TenantID,
			&i.SubnetID,
			&i.VpcID,
			&i.Name,
			&i.Description,
			&i.Cidr,
			&i.Gateway,
			&i.State,
			&i.Reason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ObservedAt,
			&i.LastOperationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockDueSubnet = `-- name: LockDueSubnet :one
SELECT s.tenant_id, s.subnet_id, s.vpc_id, s.name, s.description, s.cidr, s.gateway, s.state, s.reason, s.version, s.created_at, s.updated_at, s.observed_at, s.last_operation_id FROM network_subnets s JOIN network_reconciliations r ON r.tenant_id=s.tenant_id AND r.subnet_id=s.subnet_id
WHERE s.tenant_id=$1 AND s.vpc_id=$2 AND r.next_run_at<=clock_timestamp()
 AND (r.lease_until IS NULL OR r.lease_until<=clock_timestamp())
ORDER BY r.next_run_at,s.subnet_id LIMIT 1 FOR UPDATE OF s SKIP LOCKED
`

type LockDueSubnetParams struct {
	TenantID string
	VpcID    string
}

func (q *Queries) LockDueSubnet(ctx context.Context, arg LockDueSubnetParams) (NetworkSubnet, error) {
	row := q.db.QueryRow(ctx, lockDueSubnet, arg.TenantID, arg.VpcID)
	var i NetworkSubnet
	err := row.Scan(
		&i.TenantID,
		&i.SubnetID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.Gateway,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
	)
	return i, err
}

const lockSubnet = `-- name: LockSubnet :one
SELECT tenant_id, subnet_id, vpc_id, name, description, cidr, gateway, state, reason, version, created_at, updated_at, observed_at, last_operation_id FROM network_subnets WHERE tenant_id=$1 AND subnet_id=$2 FOR UPDATE
`

type LockSubnetParams struct {
	TenantID string
	SubnetID string
}

func (q *Queries) LockSubnet(ctx context.Context, arg LockSubnetParams) (NetworkSubnet, error) {
	row := q.db.QueryRow(ctx, lockSubnet, arg.TenantID, arg.SubnetID)
	var i NetworkSubnet
	err := row.Scan(
		&i.TenantID,
		&i.SubnetID,
		&i.VpcID,
		&i.Name,
		&i.Description,
		&i.Cidr,
		&i.Gateway,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ObservedAt,
		&i.LastOperationID,
	)
	return i, err
}

const lockSubnetCreationKey = `-- name: LockSubnetCreationKey :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text || ':create_subnet:' || $2::text,0))
`

type LockSubnetCreationKeyParams struct {
	TenantID       string
	IdempotencyKey string
}

func (q *Queries) LockSubnetCreationKey(ctx context.Context, arg LockSubnetCreationKeyParams) error {
	_, err := q.db.Exec(ctx, lockSubnetCreationKey, arg.TenantID, arg.IdempotencyKey)
	return err
}

const subnetOverlaps = `-- name: SubnetOverlaps :one
SELECT EXISTS(SELECT 1 FROM network_subnets s WHERE s.tenant_id=$1 AND s.vpc_id=$2
 AND (s.state<>'deleted' OR EXISTS(SELECT 1 FROM network_attachments a WHERE a.tenant_id=s.tenant_id AND a.subnet_id=s.subnet_id AND (a.state<>'released' OR a.protocol_blocked)))
 AND s.cidr::cidr && $3::cidr)::boolean
`

type SubnetOverlapsParams struct {
	TenantID string
	VpcID    string
	Cidr     netip.Prefix
}

func (q *Queries) SubnetOverlaps(ctx context.Context, arg SubnetOverlapsParams) (bool, error) {
	row := q.db.QueryRow(ctx, subnetOverlaps, arg.TenantID, arg.VpcID, arg.Cidr)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}
