// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: conf/v1/conf.proto

package conf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Bootstrap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Network       *Network               `protobuf:"bytes,2,opt,name=network,proto3" json:"network,omitempty"`
	Image         *Image                 `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Bootstrap) Reset() {
	*x = Bootstrap{}
	mi := &file_conf_v1_conf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Bootstrap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Bootstrap) ProtoMessage() {}

func (x *Bootstrap) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Bootstrap.ProtoReflect.Descriptor instead.
func (*Bootstrap) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{0}
}

func (x *Bootstrap) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

func (x *Bootstrap) GetNetwork() *Network {
	if x != nil {
		return x.Network
	}
	return nil
}

func (x *Bootstrap) GetImage() *Image {
	if x != nil {
		return x.Image
	}
	return nil
}

// Independent Image connections and private secret files. Disabled Image has
// no new startup dependency. The existing Network fields and tags are stable.
type Image struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Enabled              bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	DatabaseDsnFile      string                 `protobuf:"bytes,2,opt,name=database_dsn_file,json=databaseDsnFile,proto3" json:"database_dsn_file,omitempty"`
	InstallationId       string                 `protobuf:"bytes,3,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	HarborUrl            string                 `protobuf:"bytes,4,opt,name=harbor_url,json=harborUrl,proto3" json:"harbor_url,omitempty"`
	HarborCaFile         string                 `protobuf:"bytes,5,opt,name=harbor_ca_file,json=harborCaFile,proto3" json:"harbor_ca_file,omitempty"`
	HarborUsername       string                 `protobuf:"bytes,6,opt,name=harbor_username,json=harborUsername,proto3" json:"harbor_username,omitempty"`
	HarborPasswordFile   string                 `protobuf:"bytes,7,opt,name=harbor_password_file,json=harborPasswordFile,proto3" json:"harbor_password_file,omitempty"`
	RobotNamePrefix      string                 `protobuf:"bytes,8,opt,name=robot_name_prefix,json=robotNamePrefix,proto3" json:"robot_name_prefix,omitempty"`
	PlatformProject      string                 `protobuf:"bytes,9,opt,name=platform_project,json=platformProject,proto3" json:"platform_project,omitempty"`
	EncryptionKeysFile   string                 `protobuf:"bytes,10,opt,name=encryption_keys_file,json=encryptionKeysFile,proto3" json:"encryption_keys_file,omitempty"`
	CursorSigningKeyFile string                 `protobuf:"bytes,11,opt,name=cursor_signing_key_file,json=cursorSigningKeyFile,proto3" json:"cursor_signing_key_file,omitempty"`
	RequestTimeout       *durationpb.Duration   `protobuf:"bytes,12,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	PublisherDays        int64                  `protobuf:"varint,13,opt,name=publisher_days,json=publisherDays,proto3" json:"publisher_days,omitempty"`
	PullDays             int64                  `protobuf:"varint,14,opt,name=pull_days,json=pullDays,proto3" json:"pull_days,omitempty"`
	AllowNeverExpires    bool                   `protobuf:"varint,15,opt,name=allow_never_expires,json=allowNeverExpires,proto3" json:"allow_never_expires,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Image) Reset() {
	*x = Image{}
	mi := &file_conf_v1_conf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Image) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Image) ProtoMessage() {}

func (x *Image) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Image.ProtoReflect.Descriptor instead.
func (*Image) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{1}
}

func (x *Image) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *Image) GetDatabaseDsnFile() string {
	if x != nil {
		return x.DatabaseDsnFile
	}
	return ""
}

func (x *Image) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *Image) GetHarborUrl() string {
	if x != nil {
		return x.HarborUrl
	}
	return ""
}

func (x *Image) GetHarborCaFile() string {
	if x != nil {
		return x.HarborCaFile
	}
	return ""
}

func (x *Image) GetHarborUsername() string {
	if x != nil {
		return x.HarborUsername
	}
	return ""
}

func (x *Image) GetHarborPasswordFile() string {
	if x != nil {
		return x.HarborPasswordFile
	}
	return ""
}

func (x *Image) GetRobotNamePrefix() string {
	if x != nil {
		return x.RobotNamePrefix
	}
	return ""
}

func (x *Image) GetPlatformProject() string {
	if x != nil {
		return x.PlatformProject
	}
	return ""
}

func (x *Image) GetEncryptionKeysFile() string {
	if x != nil {
		return x.EncryptionKeysFile
	}
	return ""
}

func (x *Image) GetCursorSigningKeyFile() string {
	if x != nil {
		return x.CursorSigningKeyFile
	}
	return ""
}

func (x *Image) GetRequestTimeout() *durationpb.Duration {
	if x != nil {
		return x.RequestTimeout
	}
	return nil
}

func (x *Image) GetPublisherDays() int64 {
	if x != nil {
		return x.PublisherDays
	}
	return 0
}

func (x *Image) GetPullDays() int64 {
	if x != nil {
		return x.PullDays
	}
	return 0
}

func (x *Image) GetAllowNeverExpires() bool {
	if x != nil {
		return x.AllowNeverExpires
	}
	return false
}

type Network struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	DatabaseDsn string                 `protobuf:"bytes,1,opt,name=database_dsn,json=databaseDsn,proto3" json:"database_dsn,omitempty"`
	// Empty uses Kubernetes in-cluster service account credentials.
	Kubeconfig      string `protobuf:"bytes,2,opt,name=kubeconfig,proto3" json:"kubeconfig,omitempty"`
	ClusterId       string `protobuf:"bytes,3,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NamespacePrefix string `protobuf:"bytes,4,opt,name=namespace_prefix,json=namespacePrefix,proto3" json:"namespace_prefix,omitempty"`
	// Base64 encoded secret, at least 32 bytes, shared by service replicas.
	CursorSigningKey string  `protobuf:"bytes,5,opt,name=cursor_signing_key,json=cursorSigningKey,proto3" json:"cursor_signing_key,omitempty"`
	Worker           *Worker `protobuf:"bytes,6,opt,name=worker,proto3" json:"worker,omitempty"`
	// Fixed instance owner RPC target. Empty keeps attachments conservatively occupied.
	InstanceConsumerEndpoint string       `protobuf:"bytes,7,opt,name=instance_consumer_endpoint,json=instanceConsumerEndpoint,proto3" json:"instance_consumer_endpoint,omitempty"`
	Observation              *Observation `protobuf:"bytes,8,opt,name=observation,proto3" json:"observation,omitempty"`
	// The isolated acceptance instance only. Runtime recovery stays enabled
	// for accepted LB tasks even when this RPC admission switch is closed.
	LoadBalancer *LoadBalancer `protobuf:"bytes,9,opt,name=load_balancer,json=loadBalancer,proto3" json:"load_balancer,omitempty"`
	// Restart applies changes. Empty rejects first acceptance of new VPCs.
	VpcCidrPresets []string `protobuf:"bytes,10,rep,name=vpc_cidr_presets,json=vpcCidrPresets,proto3" json:"vpc_cidr_presets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Network) Reset() {
	*x = Network{}
	mi := &file_conf_v1_conf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Network) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Network) ProtoMessage() {}

func (x *Network) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Network.ProtoReflect.Descriptor instead.
func (*Network) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{2}
}

func (x *Network) GetDatabaseDsn() string {
	if x != nil {
		return x.DatabaseDsn
	}
	return ""
}

func (x *Network) GetKubeconfig() string {
	if x != nil {
		return x.Kubeconfig
	}
	return ""
}

func (x *Network) GetClusterId() string {
	if x != nil {
		return x.ClusterId
	}
	return ""
}

func (x *Network) GetNamespacePrefix() string {
	if x != nil {
		return x.NamespacePrefix
	}
	return ""
}

func (x *Network) GetCursorSigningKey() string {
	if x != nil {
		return x.CursorSigningKey
	}
	return ""
}

func (x *Network) GetWorker() *Worker {
	if x != nil {
		return x.Worker
	}
	return nil
}

func (x *Network) GetInstanceConsumerEndpoint() string {
	if x != nil {
		return x.InstanceConsumerEndpoint
	}
	return ""
}

func (x *Network) GetObservation() *Observation {
	if x != nil {
		return x.Observation
	}
	return nil
}

func (x *Network) GetLoadBalancer() *LoadBalancer {
	if x != nil {
		return x.LoadBalancer
	}
	return nil
}

func (x *Network) GetVpcCidrPresets() []string {
	if x != nil {
		return x.VpcCidrPresets
	}
	return nil
}

type LoadBalancer struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	EnableIsolatedApi       bool                   `protobuf:"varint,1,opt,name=enable_isolated_api,json=enableIsolatedApi,proto3" json:"enable_isolated_api,omitempty"`
	InstallationFingerprint string                 `protobuf:"bytes,2,opt,name=installation_fingerprint,json=installationFingerprint,proto3" json:"installation_fingerprint,omitempty"`
	ControllerImageId       string                 `protobuf:"bytes,3,opt,name=controller_image_id,json=controllerImageId,proto3" json:"controller_image_id,omitempty"`
	EnvoyImageId            string                 `protobuf:"bytes,4,opt,name=envoy_image_id,json=envoyImageId,proto3" json:"envoy_image_id,omitempty"`
	ShutdownImageId         string                 `protobuf:"bytes,5,opt,name=shutdown_image_id,json=shutdownImageId,proto3" json:"shutdown_image_id,omitempty"`
	KcImageId               string                 `protobuf:"bytes,6,opt,name=kc_image_id,json=kcImageId,proto3" json:"kc_image_id,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *LoadBalancer) Reset() {
	*x = LoadBalancer{}
	mi := &file_conf_v1_conf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancer) ProtoMessage() {}

func (x *LoadBalancer) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancer.ProtoReflect.Descriptor instead.
func (*LoadBalancer) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{3}
}

func (x *LoadBalancer) GetEnableIsolatedApi() bool {
	if x != nil {
		return x.EnableIsolatedApi
	}
	return false
}

func (x *LoadBalancer) GetInstallationFingerprint() string {
	if x != nil {
		return x.InstallationFingerprint
	}
	return ""
}

func (x *LoadBalancer) GetControllerImageId() string {
	if x != nil {
		return x.ControllerImageId
	}
	return ""
}

func (x *LoadBalancer) GetEnvoyImageId() string {
	if x != nil {
		return x.EnvoyImageId
	}
	return ""
}

func (x *LoadBalancer) GetShutdownImageId() string {
	if x != nil {
		return x.ShutdownImageId
	}
	return ""
}

func (x *LoadBalancer) GetKcImageId() string {
	if x != nil {
		return x.KcImageId
	}
	return ""
}

type Observation struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	AuditInterval  *durationpb.Duration   `protobuf:"bytes,1,opt,name=audit_interval,json=auditInterval,proto3" json:"audit_interval,omitempty"`
	AuditJitter    *durationpb.Duration   `protobuf:"bytes,2,opt,name=audit_jitter,json=auditJitter,proto3" json:"audit_jitter,omitempty"`
	AuditTimeout   *durationpb.Duration   `protobuf:"bytes,3,opt,name=audit_timeout,json=auditTimeout,proto3" json:"audit_timeout,omitempty"`
	FlushInterval  *durationpb.Duration   `protobuf:"bytes,4,opt,name=flush_interval,json=flushInterval,proto3" json:"flush_interval,omitempty"`
	QueueCapacity  uint32                 `protobuf:"varint,5,opt,name=queue_capacity,json=queueCapacity,proto3" json:"queue_capacity,omitempty"`
	WorkersPerKind uint32                 `protobuf:"varint,6,opt,name=workers_per_kind,json=workersPerKind,proto3" json:"workers_per_kind,omitempty"`
	RequestQps     uint32                 `protobuf:"varint,7,opt,name=request_qps,json=requestQps,proto3" json:"request_qps,omitempty"`
	RequestBurst   uint32                 `protobuf:"varint,8,opt,name=request_burst,json=requestBurst,proto3" json:"request_burst,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Observation) Reset() {
	*x = Observation{}
	mi := &file_conf_v1_conf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Observation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Observation) ProtoMessage() {}

func (x *Observation) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Observation.ProtoReflect.Descriptor instead.
func (*Observation) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{4}
}

func (x *Observation) GetAuditInterval() *durationpb.Duration {
	if x != nil {
		return x.AuditInterval
	}
	return nil
}

func (x *Observation) GetAuditJitter() *durationpb.Duration {
	if x != nil {
		return x.AuditJitter
	}
	return nil
}

func (x *Observation) GetAuditTimeout() *durationpb.Duration {
	if x != nil {
		return x.AuditTimeout
	}
	return nil
}

func (x *Observation) GetFlushInterval() *durationpb.Duration {
	if x != nil {
		return x.FlushInterval
	}
	return nil
}

func (x *Observation) GetQueueCapacity() uint32 {
	if x != nil {
		return x.QueueCapacity
	}
	return 0
}

func (x *Observation) GetWorkersPerKind() uint32 {
	if x != nil {
		return x.WorkersPerKind
	}
	return 0
}

func (x *Observation) GetRequestQps() uint32 {
	if x != nil {
		return x.RequestQps
	}
	return 0
}

func (x *Observation) GetRequestBurst() uint32 {
	if x != nil {
		return x.RequestBurst
	}
	return 0
}

type Worker struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Lease          *durationpb.Duration   `protobuf:"bytes,1,opt,name=lease,proto3" json:"lease,omitempty"`
	RequestTimeout *durationpb.Duration   `protobuf:"bytes,2,opt,name=request_timeout,json=requestTimeout,proto3" json:"request_timeout,omitempty"`
	ObserveEvery   *durationpb.Duration   `protobuf:"bytes,3,opt,name=observe_every,json=observeEvery,proto3" json:"observe_every,omitempty"`
	StaleAfter     *durationpb.Duration   `protobuf:"bytes,4,opt,name=stale_after,json=staleAfter,proto3" json:"stale_after,omitempty"`
	RetryMin       *durationpb.Duration   `protobuf:"bytes,5,opt,name=retry_min,json=retryMin,proto3" json:"retry_min,omitempty"`
	RetryMax       *durationpb.Duration   `protobuf:"bytes,6,opt,name=retry_max,json=retryMax,proto3" json:"retry_max,omitempty"`
	PollInterval   *durationpb.Duration   `protobuf:"bytes,7,opt,name=poll_interval,json=pollInterval,proto3" json:"poll_interval,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Worker) Reset() {
	*x = Worker{}
	mi := &file_conf_v1_conf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Worker) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Worker) ProtoMessage() {}

func (x *Worker) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Worker.ProtoReflect.Descriptor instead.
func (*Worker) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{5}
}

func (x *Worker) GetLease() *durationpb.Duration {
	if x != nil {
		return x.Lease
	}
	return nil
}

func (x *Worker) GetRequestTimeout() *durationpb.Duration {
	if x != nil {
		return x.RequestTimeout
	}
	return nil
}

func (x *Worker) GetObserveEvery() *durationpb.Duration {
	if x != nil {
		return x.ObserveEvery
	}
	return nil
}

func (x *Worker) GetStaleAfter() *durationpb.Duration {
	if x != nil {
		return x.StaleAfter
	}
	return nil
}

func (x *Worker) GetRetryMin() *durationpb.Duration {
	if x != nil {
		return x.RetryMin
	}
	return nil
}

func (x *Worker) GetRetryMax() *durationpb.Duration {
	if x != nil {
		return x.RetryMax
	}
	return nil
}

func (x *Worker) GetPollInterval() *durationpb.Duration {
	if x != nil {
		return x.PollInterval
	}
	return nil
}

type Server struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Grpc            *Server_GRPC           `protobuf:"bytes,1,opt,name=grpc,proto3" json:"grpc,omitempty"`
	Admin           *Server_Admin          `protobuf:"bytes,2,opt,name=admin,proto3" json:"admin,omitempty"`
	ShutdownTimeout *durationpb.Duration   `protobuf:"bytes,3,opt,name=shutdown_timeout,json=shutdownTimeout,proto3" json:"shutdown_timeout,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_conf_v1_conf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{6}
}

func (x *Server) GetGrpc() *Server_GRPC {
	if x != nil {
		return x.Grpc
	}
	return nil
}

func (x *Server) GetAdmin() *Server_Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

func (x *Server) GetShutdownTimeout() *durationpb.Duration {
	if x != nil {
		return x.ShutdownTimeout
	}
	return nil
}

type Server_GRPC struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_GRPC) Reset() {
	*x = Server_GRPC{}
	mi := &file_conf_v1_conf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_GRPC) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_GRPC) ProtoMessage() {}

func (x *Server_GRPC) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_GRPC.ProtoReflect.Descriptor instead.
func (*Server_GRPC) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{6, 0}
}

func (x *Server_GRPC) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_GRPC) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_GRPC) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

type Server_Admin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Network       string                 `protobuf:"bytes,1,opt,name=network,proto3" json:"network,omitempty"`
	Addr          string                 `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Timeout       *durationpb.Duration   `protobuf:"bytes,3,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Server_Admin) Reset() {
	*x = Server_Admin{}
	mi := &file_conf_v1_conf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server_Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server_Admin) ProtoMessage() {}

func (x *Server_Admin) ProtoReflect() protoreflect.Message {
	mi := &file_conf_v1_conf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server_Admin.ProtoReflect.Descriptor instead.
func (*Server_Admin) Descriptor() ([]byte, []int) {
	return file_conf_v1_conf_proto_rawDescGZIP(), []int{6, 1}
}

func (x *Server_Admin) GetNetwork() string {
	if x != nil {
		return x.Network
	}
	return ""
}

func (x *Server_Admin) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *Server_Admin) GetTimeout() *durationpb.Duration {
	if x != nil {
		return x.Timeout
	}
	return nil
}

var File_conf_v1_conf_proto protoreflect.FileDescriptor

const file_conf_v1_conf_proto_rawDesc = "" +
	"\n" +
	"\x12conf/v1/conf.proto\x12\aconf.v1\x1a\x1egoogle/protobuf/duration.proto\"\x86\x01\n" +
	"\tBootstrap\x12'\n" +
	"\x06server\x18\x01 \x01(\v2\x0f.conf.v1.ServerR\x06server\x12*\n" +
	"\anetwork\x18\x02 \x01(\v2\x10.conf.v1.NetworkR\anetwork\x12$\n" +
	"\x05image\x18\x03 \x01(\v2\x0e.conf.v1.ImageR\x05image\"\x8e\x05\n" +
	"\x05Image\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12*\n" +
	"\x11database_dsn_file\x18\x02 \x01(\tR\x0fdatabaseDsnFile\x12'\n" +
	"\x0finstallation_id\x18\x03 \x01(\tR\x0einstallationId\x12\x1d\n" +
	"\n" +
	"harbor_url\x18\x04 \x01(\tR\tharborUrl\x12$\n" +
	"\x0eharbor_ca_file\x18\x05 \x01(\tR\fharborCaFile\x12'\n" +
	"\x0fharbor_username\x18\x06 \x01(\tR\x0eharborUsername\x120\n" +
	"\x14harbor_password_file\x18\a \x01(\tR\x12harborPasswordFile\x12*\n" +
	"\x11robot_name_prefix\x18\b \x01(\tR\x0frobotNamePrefix\x12)\n" +
	"\x10platform_project\x18\t \x01(\tR\x0fplatformProject\x120\n" +
	"\x14encryption_keys_file\x18\n" +
	" \x01(\tR\x12encryptionKeysFile\x125\n" +
	"\x17cursor_signing_key_file\x18\v \x01(\tR\x14cursorSigningKeyFile\x12B\n" +
	"\x0frequest_timeout\x18\f \x01(\v2\x19.google.protobuf.DurationR\x0erequestTimeout\x12%\n" +
	"\x0epublisher_days\x18\r \x01(\x03R\rpublisherDays\x12\x1b\n" +
	"\tpull_days\x18\x0e \x01(\x03R\bpullDays\x12.\n" +
	"\x13allow_never_expires\x18\x0f \x01(\bR\x11allowNeverExpires\"\xc9\x03\n" +
	"\aNetwork\x12!\n" +
	"\fdatabase_dsn\x18\x01 \x01(\tR\vdatabaseDsn\x12\x1e\n" +
	"\n" +
	"kubeconfig\x18\x02 \x01(\tR\n" +
	"kubeconfig\x12\x1d\n" +
	"\n" +
	"cluster_id\x18\x03 \x01(\tR\tclusterId\x12)\n" +
	"\x10namespace_prefix\x18\x04 \x01(\tR\x0fnamespacePrefix\x12,\n" +
	"\x12cursor_signing_key\x18\x05 \x01(\tR\x10cursorSigningKey\x12'\n" +
	"\x06worker\x18\x06 \x01(\v2\x0f.conf.v1.WorkerR\x06worker\x12<\n" +
	"\x1ainstance_consumer_endpoint\x18\a \x01(\tR\x18instanceConsumerEndpoint\x126\n" +
	"\vobservation\x18\b \x01(\v2\x14.conf.v1.ObservationR\vobservation\x12:\n" +
	"\rload_balancer\x18\t \x01(\v2\x15.conf.v1.LoadBalancerR\floadBalancer\x12(\n" +
	"\x10vpc_cidr_presets\x18\n" +
	" \x03(\tR\x0evpcCidrPresets\"\x9b\x02\n" +
	"\fLoadBalancer\x12.\n" +
	"\x13enable_isolated_api\x18\x01 \x01(\bR\x11enableIsolatedApi\x129\n" +
	"\x18installation_fingerprint\x18\x02 \x01(\tR\x17installationFingerprint\x12.\n" +
	"\x13controller_image_id\x18\x03 \x01(\tR\x11controllerImageId\x12$\n" +
	"\x0eenvoy_image_id\x18\x04 \x01(\tR\fenvoyImageId\x12*\n" +
	"\x11shutdown_image_id\x18\x05 \x01(\tR\x0fshutdownImageId\x12\x1e\n" +
	"\vkc_image_id\x18\x06 \x01(\tR\tkcImageId\"\xa6\x03\n" +
	"\vObservation\x12@\n" +
	"\x0eaudit_interval\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\rauditInterval\x12<\n" +
	"\faudit_jitter\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\vauditJitter\x12>\n" +
	"\raudit_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\fauditTimeout\x12@\n" +
	"\x0eflush_interval\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\rflushInterval\x12%\n" +
	"\x0equeue_capacity\x18\x05 \x01(\rR\rqueueCapacity\x12(\n" +
	"\x10workers_per_kind\x18\x06 \x01(\rR\x0eworkersPerKind\x12\x1f\n" +
	"\vrequest_qps\x18\a \x01(\rR\n" +
	"requestQps\x12#\n" +
	"\rrequest_burst\x18\b \x01(\rR\frequestBurst\"\xa9\x03\n" +
	"\x06Worker\x12/\n" +
	"\x05lease\x18\x01 \x01(\v2\x19.google.protobuf.DurationR\x05lease\x12B\n" +
	"\x0frequest_timeout\x18\x02 \x01(\v2\x19.google.protobuf.DurationR\x0erequestTimeout\x12>\n" +
	"\robserve_every\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\fobserveEvery\x12:\n" +
	"\vstale_after\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\n" +
	"staleAfter\x126\n" +
	"\tretry_min\x18\x05 \x01(\v2\x19.google.protobuf.DurationR\bretryMin\x126\n" +
	"\tretry_max\x18\x06 \x01(\v2\x19.google.protobuf.DurationR\bretryMax\x12>\n" +
	"\rpoll_interval\x18\a \x01(\v2\x19.google.protobuf.DurationR\fpollInterval\"\xfc\x02\n" +
	"\x06Server\x12(\n" +
	"\x04grpc\x18\x01 \x01(\v2\x14.conf.v1.Server.GRPCR\x04grpc\x12+\n" +
	"\x05admin\x18\x02 \x01(\v2\x15.conf.v1.Server.AdminR\x05admin\x12D\n" +
	"\x10shutdown_timeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\x0fshutdownTimeout\x1ai\n" +
	"\x04GRPC\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeout\x1aj\n" +
	"\x05Admin\x12\x18\n" +
	"\anetwork\x18\x01 \x01(\tR\anetwork\x12\x12\n" +
	"\x04addr\x18\x02 \x01(\tR\x04addr\x123\n" +
	"\atimeout\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\atimeoutBEZCgithub.com/zhangzhe-ctrl/ani-resource-service/internal/conf/v1;confb\x06proto3"

var (
	file_conf_v1_conf_proto_rawDescOnce sync.Once
	file_conf_v1_conf_proto_rawDescData []byte
)

func file_conf_v1_conf_proto_rawDescGZIP() []byte {
	file_conf_v1_conf_proto_rawDescOnce.Do(func() {
		file_conf_v1_conf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_conf_v1_conf_proto_rawDesc), len(file_conf_v1_conf_proto_rawDesc)))
	})
	return file_conf_v1_conf_proto_rawDescData
}

var file_conf_v1_conf_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_conf_v1_conf_proto_goTypes = []any{
	(*Bootstrap)(nil),           // 0: conf.v1.Bootstrap
	(*Image)(nil),               // 1: conf.v1.Image
	(*Network)(nil),             // 2: conf.v1.Network
	(*LoadBalancer)(nil),        // 3: conf.v1.LoadBalancer
	(*Observation)(nil),         // 4: conf.v1.Observation
	(*Worker)(nil),              // 5: conf.v1.Worker
	(*Server)(nil),              // 6: conf.v1.Server
	(*Server_GRPC)(nil),         // 7: conf.v1.Server.GRPC
	(*Server_Admin)(nil),        // 8: conf.v1.Server.Admin
	(*durationpb.Duration)(nil), // 9: google.protobuf.Duration
}
var file_conf_v1_conf_proto_depIdxs = []int32{
	6,  // 0: conf.v1.Bootstrap.server:type_name -> conf.v1.Server
	2,  // 1: conf.v1.Bootstrap.network:type_name -> conf.v1.Network
	1,  // 2: conf.v1.Bootstrap.image:type_name -> conf.v1.Image
	9,  // 3: conf.v1.Image.request_timeout:type_name -> google.protobuf.Duration
	5,  // 4: conf.v1.Network.worker:type_name -> conf.v1.Worker
	4,  // 5: conf.v1.Network.observation:type_name -> conf.v1.Observation
	3,  // 6: conf.v1.Network.load_balancer:type_name -> conf.v1.LoadBalancer
	9,  // 7: conf.v1.Observation.audit_interval:type_name -> google.protobuf.Duration
	9,  // 8: conf.v1.Observation.audit_jitter:type_name -> google.protobuf.Duration
	9,  // 9: conf.v1.Observation.audit_timeout:type_name -> google.protobuf.Duration
	9,  // 10: conf.v1.Observation.flush_interval:type_name -> google.protobuf.Duration
	9,  // 11: conf.v1.Worker.lease:type_name -> google.protobuf.Duration
	9,  // 12: conf.v1.Worker.request_timeout:type_name -> google.protobuf.Duration
	9,  // 13: conf.v1.Worker.observe_every:type_name -> google.protobuf.Duration
	9,  // 14: conf.v1.Worker.stale_after:type_name -> google.protobuf.Duration
	9,  // 15: conf.v1.Worker.retry_min:type_name -> google.protobuf.Duration
	9,  // 16: conf.v1.Worker.retry_max:type_name -> google.protobuf.Duration
	9,  // 17: conf.v1.Worker.poll_interval:type_name -> google.protobuf.Duration
	7,  // 18: conf.v1.Server.grpc:type_name -> conf.v1.Server.GRPC
	8,  // 19: conf.v1.Server.admin:type_name -> conf.v1.Server.Admin
	9,  // 20: conf.v1.Server.shutdown_timeout:type_name -> google.protobuf.Duration
	9,  // 21: conf.v1.Server.GRPC.timeout:type_name -> google.protobuf.Duration
	9,  // 22: conf.v1.Server.Admin.timeout:type_name -> google.protobuf.Duration
	23, // [23:23] is the sub-list for method output_type
	23, // [23:23] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_conf_v1_conf_proto_init() }
func file_conf_v1_conf_proto_init() {
	if File_conf_v1_conf_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_conf_v1_conf_proto_rawDesc), len(file_conf_v1_conf_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_conf_v1_conf_proto_goTypes,
		DependencyIndexes: file_conf_v1_conf_proto_depIdxs,
		MessageInfos:      file_conf_v1_conf_proto_msgTypes,
	}.Build()
	File_conf_v1_conf_proto = out.File
	file_conf_v1_conf_proto_goTypes = nil
	file_conf_v1_conf_proto_depIdxs = nil
}
