// Design contract v1.0. Generate and validate on Fedora before treating as implementation.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: image/v1/image.proto

package imagev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TenantImageService_EnsureImageSpace_FullMethodName           = "/image.v1.TenantImageService/EnsureImageSpace"
	TenantImageService_GetImageSpace_FullMethodName              = "/image.v1.TenantImageService/GetImageSpace"
	TenantImageService_GetPublisherCredential_FullMethodName     = "/image.v1.TenantImageService/GetPublisherCredential"
	TenantImageService_IssuePublisherCredential_FullMethodName   = "/image.v1.TenantImageService/IssuePublisherCredential"
	TenantImageService_ResetPublisherCredential_FullMethodName   = "/image.v1.TenantImageService/ResetPublisherCredential"
	TenantImageService_DisablePublisherCredential_FullMethodName = "/image.v1.TenantImageService/DisablePublisherCredential"
	TenantImageService_RegisterImage_FullMethodName              = "/image.v1.TenantImageService/RegisterImage"
	TenantImageService_GetImage_FullMethodName                   = "/image.v1.TenantImageService/GetImage"
	TenantImageService_ListImages_FullMethodName                 = "/image.v1.TenantImageService/ListImages"
	TenantImageService_UpdateImage_FullMethodName                = "/image.v1.TenantImageService/UpdateImage"
	TenantImageService_UnregisterImage_FullMethodName            = "/image.v1.TenantImageService/UnregisterImage"
)

// TenantImageServiceClient is the client API for TenantImageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Registered only on the existing authenticated Governance entry.
type TenantImageServiceClient interface {
	EnsureImageSpace(ctx context.Context, in *EnsureImageSpaceRequest, opts ...grpc.CallOption) (*EnsureImageSpaceResponse, error)
	GetImageSpace(ctx context.Context, in *GetImageSpaceRequest, opts ...grpc.CallOption) (*GetImageSpaceResponse, error)
	GetPublisherCredential(ctx context.Context, in *GetPublisherCredentialRequest, opts ...grpc.CallOption) (*GetPublisherCredentialResponse, error)
	IssuePublisherCredential(ctx context.Context, in *IssuePublisherCredentialRequest, opts ...grpc.CallOption) (*IssuePublisherCredentialResponse, error)
	ResetPublisherCredential(ctx context.Context, in *ResetPublisherCredentialRequest, opts ...grpc.CallOption) (*ResetPublisherCredentialResponse, error)
	DisablePublisherCredential(ctx context.Context, in *DisablePublisherCredentialRequest, opts ...grpc.CallOption) (*DisablePublisherCredentialResponse, error)
	RegisterImage(ctx context.Context, in *RegisterImageRequest, opts ...grpc.CallOption) (*RegisterImageResponse, error)
	GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*GetImageResponse, error)
	ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	UpdateImage(ctx context.Context, in *UpdateImageRequest, opts ...grpc.CallOption) (*UpdateImageResponse, error)
	UnregisterImage(ctx context.Context, in *UnregisterImageRequest, opts ...grpc.CallOption) (*UnregisterImageResponse, error)
}

type tenantImageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTenantImageServiceClient(cc grpc.ClientConnInterface) TenantImageServiceClient {
	return &tenantImageServiceClient{cc}
}

func (c *tenantImageServiceClient) EnsureImageSpace(ctx context.Context, in *EnsureImageSpaceRequest, opts ...grpc.CallOption) (*EnsureImageSpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnsureImageSpaceResponse)
	err := c.cc.Invoke(ctx, TenantImageService_EnsureImageSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantImageServiceClient) GetImageSpace(ctx context.Context, in *GetImageSpaceRequest, opts ...grpc.CallOption) (*GetImageSpaceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImageSpaceResponse)
	err := c.cc.Invoke(ctx, TenantImageService_GetImageSpace_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantImageServiceClient) GetPublisherCredential(ctx context.Context, in *GetPublisherCredentialRequest, opts ...grpc.CallOption) (*GetPublisherCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPublisherCredentialResponse)
	err := c.cc.Invoke(ctx, TenantImageService_GetPublisherCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantImageServiceClient) IssuePublisherCredential(ctx context.Context, in *IssuePublisherCredentialRequest, opts ...grpc.CallOption) (*IssuePublisherCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssuePublisherCredentialResponse)
	err := c.cc.Invoke(ctx, TenantImageService_IssuePublisherCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantImageServiceClient) ResetPublisherCredential(ctx context.Context, in *ResetPublisherCredentialRequest, opts ...grpc.CallOption) (*ResetPublisherCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetPublisherCredentialResponse)
	err := c.cc.Invoke(ctx, TenantImageService_ResetPublisherCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantImageServiceClient) DisablePublisherCredential(ctx context.Context, in *DisablePublisherCredentialRequest, opts ...grpc.CallOption) (*DisablePublisherCredentialResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DisablePublisherCredentialResponse)
	err := c.cc.Invoke(ctx, TenantImageService_DisablePublisherCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantImageServiceClient) RegisterImage(ctx context.Context, in *RegisterImageRequest, opts ...grpc.CallOption) (*RegisterImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterImageResponse)
	err := c.cc.Invoke(ctx, TenantImageService_RegisterImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantImageServiceClient) GetImage(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*GetImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetImageResponse)
	err := c.cc.Invoke(ctx, TenantImageService_GetImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantImageServiceClient) ListImages(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListImagesResponse)
	err := c.cc.Invoke(ctx, TenantImageService_ListImages_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantImageServiceClient) UpdateImage(ctx context.Context, in *UpdateImageRequest, opts ...grpc.CallOption) (*UpdateImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateImageResponse)
	err := c.cc.Invoke(ctx, TenantImageService_UpdateImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *tenantImageServiceClient) UnregisterImage(ctx context.Context, in *UnregisterImageRequest, opts ...grpc.CallOption) (*UnregisterImageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnregisterImageResponse)
	err := c.cc.Invoke(ctx, TenantImageService_UnregisterImage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TenantImageServiceServer is the server API for TenantImageService service.
// All implementations must embed UnimplementedTenantImageServiceServer
// for forward compatibility.
//
// Registered only on the existing authenticated Governance entry.
type TenantImageServiceServer interface {
	EnsureImageSpace(context.Context, *EnsureImageSpaceRequest) (*EnsureImageSpaceResponse, error)
	GetImageSpace(context.Context, *GetImageSpaceRequest) (*GetImageSpaceResponse, error)
	GetPublisherCredential(context.Context, *GetPublisherCredentialRequest) (*GetPublisherCredentialResponse, error)
	IssuePublisherCredential(context.Context, *IssuePublisherCredentialRequest) (*IssuePublisherCredentialResponse, error)
	ResetPublisherCredential(context.Context, *ResetPublisherCredentialRequest) (*ResetPublisherCredentialResponse, error)
	DisablePublisherCredential(context.Context, *DisablePublisherCredentialRequest) (*DisablePublisherCredentialResponse, error)
	RegisterImage(context.Context, *RegisterImageRequest) (*RegisterImageResponse, error)
	GetImage(context.Context, *GetImageRequest) (*GetImageResponse, error)
	ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	UpdateImage(context.Context, *UpdateImageRequest) (*UpdateImageResponse, error)
	UnregisterImage(context.Context, *UnregisterImageRequest) (*UnregisterImageResponse, error)
	mustEmbedUnimplementedTenantImageServiceServer()
}

// UnimplementedTenantImageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTenantImageServiceServer struct{}

func (UnimplementedTenantImageServiceServer) EnsureImageSpace(context.Context, *EnsureImageSpaceRequest) (*EnsureImageSpaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnsureImageSpace not implemented")
}
func (UnimplementedTenantImageServiceServer) GetImageSpace(context.Context, *GetImageSpaceRequest) (*GetImageSpaceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImageSpace not implemented")
}
func (UnimplementedTenantImageServiceServer) GetPublisherCredential(context.Context, *GetPublisherCredentialRequest) (*GetPublisherCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPublisherCredential not implemented")
}
func (UnimplementedTenantImageServiceServer) IssuePublisherCredential(context.Context, *IssuePublisherCredentialRequest) (*IssuePublisherCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IssuePublisherCredential not implemented")
}
func (UnimplementedTenantImageServiceServer) ResetPublisherCredential(context.Context, *ResetPublisherCredentialRequest) (*ResetPublisherCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResetPublisherCredential not implemented")
}
func (UnimplementedTenantImageServiceServer) DisablePublisherCredential(context.Context, *DisablePublisherCredentialRequest) (*DisablePublisherCredentialResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisablePublisherCredential not implemented")
}
func (UnimplementedTenantImageServiceServer) RegisterImage(context.Context, *RegisterImageRequest) (*RegisterImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterImage not implemented")
}
func (UnimplementedTenantImageServiceServer) GetImage(context.Context, *GetImageRequest) (*GetImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetImage not implemented")
}
func (UnimplementedTenantImageServiceServer) ListImages(context.Context, *ListImagesRequest) (*ListImagesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListImages not implemented")
}
func (UnimplementedTenantImageServiceServer) UpdateImage(context.Context, *UpdateImageRequest) (*UpdateImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateImage not implemented")
}
func (UnimplementedTenantImageServiceServer) UnregisterImage(context.Context, *UnregisterImageRequest) (*UnregisterImageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterImage not implemented")
}
func (UnimplementedTenantImageServiceServer) mustEmbedUnimplementedTenantImageServiceServer() {}
func (UnimplementedTenantImageServiceServer) testEmbeddedByValue()                            {}

// UnsafeTenantImageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TenantImageServiceServer will
// result in compilation errors.
type UnsafeTenantImageServiceServer interface {
	mustEmbedUnimplementedTenantImageServiceServer()
}

func RegisterTenantImageServiceServer(s grpc.ServiceRegistrar, srv TenantImageServiceServer) {
	// If the following call pancis, it indicates UnimplementedTenantImageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TenantImageService_ServiceDesc, srv)
}

func _TenantImageService_EnsureImageSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnsureImageSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantImageServiceServer).EnsureImageSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantImageService_EnsureImageSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantImageServiceServer).EnsureImageSpace(ctx, req.(*EnsureImageSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantImageService_GetImageSpace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageSpaceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantImageServiceServer).GetImageSpace(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantImageService_GetImageSpace_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantImageServiceServer).GetImageSpace(ctx, req.(*GetImageSpaceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantImageService_GetPublisherCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPublisherCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantImageServiceServer).GetPublisherCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantImageService_GetPublisherCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantImageServiceServer).GetPublisherCredential(ctx, req.(*GetPublisherCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantImageService_IssuePublisherCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssuePublisherCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantImageServiceServer).IssuePublisherCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantImageService_IssuePublisherCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantImageServiceServer).IssuePublisherCredential(ctx, req.(*IssuePublisherCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantImageService_ResetPublisherCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPublisherCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantImageServiceServer).ResetPublisherCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantImageService_ResetPublisherCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantImageServiceServer).ResetPublisherCredential(ctx, req.(*ResetPublisherCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantImageService_DisablePublisherCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisablePublisherCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantImageServiceServer).DisablePublisherCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantImageService_DisablePublisherCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantImageServiceServer).DisablePublisherCredential(ctx, req.(*DisablePublisherCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantImageService_RegisterImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantImageServiceServer).RegisterImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantImageService_RegisterImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantImageServiceServer).RegisterImage(ctx, req.(*RegisterImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantImageService_GetImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantImageServiceServer).GetImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantImageService_GetImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantImageServiceServer).GetImage(ctx, req.(*GetImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantImageService_ListImages_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantImageServiceServer).ListImages(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantImageService_ListImages_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantImageServiceServer).ListImages(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantImageService_UpdateImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantImageServiceServer).UpdateImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantImageService_UpdateImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantImageServiceServer).UpdateImage(ctx, req.(*UpdateImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TenantImageService_UnregisterImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnregisterImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TenantImageServiceServer).UnregisterImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TenantImageService_UnregisterImage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TenantImageServiceServer).UnregisterImage(ctx, req.(*UnregisterImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TenantImageService_ServiceDesc is the grpc.ServiceDesc for TenantImageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TenantImageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "image.v1.TenantImageService",
	HandlerType: (*TenantImageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EnsureImageSpace",
			Handler:    _TenantImageService_EnsureImageSpace_Handler,
		},
		{
			MethodName: "GetImageSpace",
			Handler:    _TenantImageService_GetImageSpace_Handler,
		},
		{
			MethodName: "GetPublisherCredential",
			Handler:    _TenantImageService_GetPublisherCredential_Handler,
		},
		{
			MethodName: "IssuePublisherCredential",
			Handler:    _TenantImageService_IssuePublisherCredential_Handler,
		},
		{
			MethodName: "ResetPublisherCredential",
			Handler:    _TenantImageService_ResetPublisherCredential_Handler,
		},
		{
			MethodName: "DisablePublisherCredential",
			Handler:    _TenantImageService_DisablePublisherCredential_Handler,
		},
		{
			MethodName: "RegisterImage",
			Handler:    _TenantImageService_RegisterImage_Handler,
		},
		{
			MethodName: "GetImage",
			Handler:    _TenantImageService_GetImage_Handler,
		},
		{
			MethodName: "ListImages",
			Handler:    _TenantImageService_ListImages_Handler,
		},
		{
			MethodName: "UpdateImage",
			Handler:    _TenantImageService_UpdateImage_Handler,
		},
		{
			MethodName: "UnregisterImage",
			Handler:    _TenantImageService_UnregisterImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "image/v1/image.proto",
}
