// Design contract v1.0. Generate and validate on Fedora before treating as implementation.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: image/v1/image.proto

package imagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ImageScope int32

const (
	ImageScope_IMAGE_SCOPE_UNSPECIFIED ImageScope = 0
	ImageScope_IMAGE_SCOPE_TENANT      ImageScope = 1
	ImageScope_IMAGE_SCOPE_PLATFORM    ImageScope = 2
)

// Enum value maps for ImageScope.
var (
	ImageScope_name = map[int32]string{
		0: "IMAGE_SCOPE_UNSPECIFIED",
		1: "IMAGE_SCOPE_TENANT",
		2: "IMAGE_SCOPE_PLATFORM",
	}
	ImageScope_value = map[string]int32{
		"IMAGE_SCOPE_UNSPECIFIED": 0,
		"IMAGE_SCOPE_TENANT":      1,
		"IMAGE_SCOPE_PLATFORM":    2,
	}
)

func (x ImageScope) Enum() *ImageScope {
	p := new(ImageScope)
	*p = x
	return p
}

func (x ImageScope) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImageScope) Descriptor() protoreflect.EnumDescriptor {
	return file_image_v1_image_proto_enumTypes[0].Descriptor()
}

func (ImageScope) Type() protoreflect.EnumType {
	return &file_image_v1_image_proto_enumTypes[0]
}

func (x ImageScope) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImageScope.Descriptor instead.
func (ImageScope) EnumDescriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{0}
}

type ImagePurpose int32

const (
	ImagePurpose_IMAGE_PURPOSE_UNSPECIFIED ImagePurpose = 0
	ImagePurpose_IMAGE_PURPOSE_CONTAINER   ImagePurpose = 1
	ImagePurpose_IMAGE_PURPOSE_DEVELOPMENT ImagePurpose = 2
	ImagePurpose_IMAGE_PURPOSE_INFERENCE   ImagePurpose = 3
	ImagePurpose_IMAGE_PURPOSE_FINETUNING  ImagePurpose = 4
	ImagePurpose_IMAGE_PURPOSE_TRAINING    ImagePurpose = 5
)

// Enum value maps for ImagePurpose.
var (
	ImagePurpose_name = map[int32]string{
		0: "IMAGE_PURPOSE_UNSPECIFIED",
		1: "IMAGE_PURPOSE_CONTAINER",
		2: "IMAGE_PURPOSE_DEVELOPMENT",
		3: "IMAGE_PURPOSE_INFERENCE",
		4: "IMAGE_PURPOSE_FINETUNING",
		5: "IMAGE_PURPOSE_TRAINING",
	}
	ImagePurpose_value = map[string]int32{
		"IMAGE_PURPOSE_UNSPECIFIED": 0,
		"IMAGE_PURPOSE_CONTAINER":   1,
		"IMAGE_PURPOSE_DEVELOPMENT": 2,
		"IMAGE_PURPOSE_INFERENCE":   3,
		"IMAGE_PURPOSE_FINETUNING":  4,
		"IMAGE_PURPOSE_TRAINING":    5,
	}
)

func (x ImagePurpose) Enum() *ImagePurpose {
	p := new(ImagePurpose)
	*p = x
	return p
}

func (x ImagePurpose) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ImagePurpose) Descriptor() protoreflect.EnumDescriptor {
	return file_image_v1_image_proto_enumTypes[1].Descriptor()
}

func (ImagePurpose) Type() protoreflect.EnumType {
	return &file_image_v1_image_proto_enumTypes[1]
}

func (x ImagePurpose) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ImagePurpose.Descriptor instead.
func (ImagePurpose) EnumDescriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{1}
}

type AcceleratorKind int32

const (
	AcceleratorKind_ACCELERATOR_KIND_UNSPECIFIED AcceleratorKind = 0
	AcceleratorKind_ACCELERATOR_KIND_NONE        AcceleratorKind = 1
	AcceleratorKind_ACCELERATOR_KIND_NVIDIA      AcceleratorKind = 2
	AcceleratorKind_ACCELERATOR_KIND_AMD         AcceleratorKind = 3
	AcceleratorKind_ACCELERATOR_KIND_ASCEND      AcceleratorKind = 4
	AcceleratorKind_ACCELERATOR_KIND_OTHER       AcceleratorKind = 5
)

// Enum value maps for AcceleratorKind.
var (
	AcceleratorKind_name = map[int32]string{
		0: "ACCELERATOR_KIND_UNSPECIFIED",
		1: "ACCELERATOR_KIND_NONE",
		2: "ACCELERATOR_KIND_NVIDIA",
		3: "ACCELERATOR_KIND_AMD",
		4: "ACCELERATOR_KIND_ASCEND",
		5: "ACCELERATOR_KIND_OTHER",
	}
	AcceleratorKind_value = map[string]int32{
		"ACCELERATOR_KIND_UNSPECIFIED": 0,
		"ACCELERATOR_KIND_NONE":        1,
		"ACCELERATOR_KIND_NVIDIA":      2,
		"ACCELERATOR_KIND_AMD":         3,
		"ACCELERATOR_KIND_ASCEND":      4,
		"ACCELERATOR_KIND_OTHER":       5,
	}
)

func (x AcceleratorKind) Enum() *AcceleratorKind {
	p := new(AcceleratorKind)
	*p = x
	return p
}

func (x AcceleratorKind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AcceleratorKind) Descriptor() protoreflect.EnumDescriptor {
	return file_image_v1_image_proto_enumTypes[2].Descriptor()
}

func (AcceleratorKind) Type() protoreflect.EnumType {
	return &file_image_v1_image_proto_enumTypes[2]
}

func (x AcceleratorKind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AcceleratorKind.Descriptor instead.
func (AcceleratorKind) EnumDescriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{2}
}

type ImagePlatform struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Architecture  string                 `protobuf:"bytes,2,opt,name=architecture,proto3" json:"architecture,omitempty"`
	Variant       string                 `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ImagePlatform) Reset() {
	*x = ImagePlatform{}
	mi := &file_image_v1_image_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImagePlatform) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImagePlatform) ProtoMessage() {}

func (x *ImagePlatform) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImagePlatform.ProtoReflect.Descriptor instead.
func (*ImagePlatform) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{0}
}

func (x *ImagePlatform) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *ImagePlatform) GetArchitecture() string {
	if x != nil {
		return x.Architecture
	}
	return ""
}

func (x *ImagePlatform) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

type ImageSpace struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	SpaceId                  string                 `protobuf:"bytes,1,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	TenantId                 string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ProjectName              string                 `protobuf:"bytes,3,opt,name=project_name,json=projectName,proto3" json:"project_name,omitempty"`
	RegistryAuthority        string                 `protobuf:"bytes,4,opt,name=registry_authority,json=registryAuthority,proto3" json:"registry_authority,omitempty"`
	State                    string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Reason                   string                 `protobuf:"bytes,6,opt,name=reason,proto3" json:"reason,omitempty"`
	Version                  int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	PullCredentialGeneration int64                  `protobuf:"varint,8,opt,name=pull_credential_generation,json=pullCredentialGeneration,proto3" json:"pull_credential_generation,omitempty"`
	CreatedAt                *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt                *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ImageSpace) Reset() {
	*x = ImageSpace{}
	mi := &file_image_v1_image_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageSpace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageSpace) ProtoMessage() {}

func (x *ImageSpace) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageSpace.ProtoReflect.Descriptor instead.
func (*ImageSpace) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{1}
}

func (x *ImageSpace) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ImageSpace) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ImageSpace) GetProjectName() string {
	if x != nil {
		return x.ProjectName
	}
	return ""
}

func (x *ImageSpace) GetRegistryAuthority() string {
	if x != nil {
		return x.RegistryAuthority
	}
	return ""
}

func (x *ImageSpace) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *ImageSpace) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *ImageSpace) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ImageSpace) GetPullCredentialGeneration() int64 {
	if x != nil {
		return x.PullCredentialGeneration
	}
	return 0
}

func (x *ImageSpace) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ImageSpace) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type PublisherCredential struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SpaceId       string                 `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	Generation    int64                  `protobuf:"varint,3,opt,name=generation,proto3" json:"generation,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	State         string                 `protobuf:"bytes,5,opt,name=state,proto3" json:"state,omitempty"`
	Version       int64                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublisherCredential) Reset() {
	*x = PublisherCredential{}
	mi := &file_image_v1_image_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublisherCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublisherCredential) ProtoMessage() {}

func (x *PublisherCredential) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublisherCredential.ProtoReflect.Descriptor instead.
func (*PublisherCredential) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{2}
}

func (x *PublisherCredential) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *PublisherCredential) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *PublisherCredential) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *PublisherCredential) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PublisherCredential) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *PublisherCredential) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *PublisherCredential) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *PublisherCredential) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type ImageRegistration struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ImageId           string                 `protobuf:"bytes,1,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	TenantId          string                 `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scope             ImageScope             `protobuf:"varint,3,opt,name=scope,proto3,enum=image.v1.ImageScope" json:"scope,omitempty"`
	SpaceId           string                 `protobuf:"bytes,4,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	DisplayName       string                 `protobuf:"bytes,5,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description       string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Repository        string                 `protobuf:"bytes,7,opt,name=repository,proto3" json:"repository,omitempty"`
	SourceReference   string                 `protobuf:"bytes,8,opt,name=source_reference,json=sourceReference,proto3" json:"source_reference,omitempty"`
	Digest            string                 `protobuf:"bytes,9,opt,name=digest,proto3" json:"digest,omitempty"`
	ResolvedReference string                 `protobuf:"bytes,10,opt,name=resolved_reference,json=resolvedReference,proto3" json:"resolved_reference,omitempty"`
	Platforms         []*ImagePlatform       `protobuf:"bytes,11,rep,name=platforms,proto3" json:"platforms,omitempty"`
	Purposes          []ImagePurpose         `protobuf:"varint,12,rep,packed,name=purposes,proto3,enum=image.v1.ImagePurpose" json:"purposes,omitempty"`
	Accelerator       AcceleratorKind        `protobuf:"varint,13,opt,name=accelerator,proto3,enum=image.v1.AcceleratorKind" json:"accelerator,omitempty"`
	Version           int64                  `protobuf:"varint,14,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt         *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt         *timestamppb.Timestamp `protobuf:"bytes,16,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UnregisteredAt    *timestamppb.Timestamp `protobuf:"bytes,17,opt,name=unregistered_at,json=unregisteredAt,proto3" json:"unregistered_at,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ImageRegistration) Reset() {
	*x = ImageRegistration{}
	mi := &file_image_v1_image_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ImageRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ImageRegistration) ProtoMessage() {}

func (x *ImageRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ImageRegistration.ProtoReflect.Descriptor instead.
func (*ImageRegistration) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{3}
}

func (x *ImageRegistration) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ImageRegistration) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ImageRegistration) GetScope() ImageScope {
	if x != nil {
		return x.Scope
	}
	return ImageScope_IMAGE_SCOPE_UNSPECIFIED
}

func (x *ImageRegistration) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *ImageRegistration) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *ImageRegistration) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ImageRegistration) GetRepository() string {
	if x != nil {
		return x.Repository
	}
	return ""
}

func (x *ImageRegistration) GetSourceReference() string {
	if x != nil {
		return x.SourceReference
	}
	return ""
}

func (x *ImageRegistration) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ImageRegistration) GetResolvedReference() string {
	if x != nil {
		return x.ResolvedReference
	}
	return ""
}

func (x *ImageRegistration) GetPlatforms() []*ImagePlatform {
	if x != nil {
		return x.Platforms
	}
	return nil
}

func (x *ImageRegistration) GetPurposes() []ImagePurpose {
	if x != nil {
		return x.Purposes
	}
	return nil
}

func (x *ImageRegistration) GetAccelerator() AcceleratorKind {
	if x != nil {
		return x.Accelerator
	}
	return AcceleratorKind_ACCELERATOR_KIND_UNSPECIFIED
}

func (x *ImageRegistration) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *ImageRegistration) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ImageRegistration) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *ImageRegistration) GetUnregisteredAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UnregisteredAt
	}
	return nil
}

type EnsureImageSpaceRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Slug           string                 `protobuf:"bytes,2,opt,name=slug,proto3" json:"slug,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnsureImageSpaceRequest) Reset() {
	*x = EnsureImageSpaceRequest{}
	mi := &file_image_v1_image_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureImageSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureImageSpaceRequest) ProtoMessage() {}

func (x *EnsureImageSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureImageSpaceRequest.ProtoReflect.Descriptor instead.
func (*EnsureImageSpaceRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{4}
}

func (x *EnsureImageSpaceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EnsureImageSpaceRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *EnsureImageSpaceRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type EnsureImageSpaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Space         *ImageSpace            `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnsureImageSpaceResponse) Reset() {
	*x = EnsureImageSpaceResponse{}
	mi := &file_image_v1_image_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnsureImageSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnsureImageSpaceResponse) ProtoMessage() {}

func (x *EnsureImageSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnsureImageSpaceResponse.ProtoReflect.Descriptor instead.
func (*EnsureImageSpaceResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{5}
}

func (x *EnsureImageSpaceResponse) GetSpace() *ImageSpace {
	if x != nil {
		return x.Space
	}
	return nil
}

type GetImageSpaceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageSpaceRequest) Reset() {
	*x = GetImageSpaceRequest{}
	mi := &file_image_v1_image_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageSpaceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageSpaceRequest) ProtoMessage() {}

func (x *GetImageSpaceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageSpaceRequest.ProtoReflect.Descriptor instead.
func (*GetImageSpaceRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{6}
}

func (x *GetImageSpaceRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetImageSpaceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Space         *ImageSpace            `protobuf:"bytes,1,opt,name=space,proto3" json:"space,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageSpaceResponse) Reset() {
	*x = GetImageSpaceResponse{}
	mi := &file_image_v1_image_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageSpaceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageSpaceResponse) ProtoMessage() {}

func (x *GetImageSpaceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageSpaceResponse.ProtoReflect.Descriptor instead.
func (*GetImageSpaceResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{7}
}

func (x *GetImageSpaceResponse) GetSpace() *ImageSpace {
	if x != nil {
		return x.Space
	}
	return nil
}

type GetPublisherCredentialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublisherCredentialRequest) Reset() {
	*x = GetPublisherCredentialRequest{}
	mi := &file_image_v1_image_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublisherCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublisherCredentialRequest) ProtoMessage() {}

func (x *GetPublisherCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublisherCredentialRequest.ProtoReflect.Descriptor instead.
func (*GetPublisherCredentialRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{8}
}

func (x *GetPublisherCredentialRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetPublisherCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *PublisherCredential   `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPublisherCredentialResponse) Reset() {
	*x = GetPublisherCredentialResponse{}
	mi := &file_image_v1_image_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPublisherCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPublisherCredentialResponse) ProtoMessage() {}

func (x *GetPublisherCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPublisherCredentialResponse.ProtoReflect.Descriptor instead.
func (*GetPublisherCredentialResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{9}
}

func (x *GetPublisherCredentialResponse) GetCredential() *PublisherCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type IssuePublisherCredentialRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IssuePublisherCredentialRequest) Reset() {
	*x = IssuePublisherCredentialRequest{}
	mi := &file_image_v1_image_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePublisherCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePublisherCredentialRequest) ProtoMessage() {}

func (x *IssuePublisherCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePublisherCredentialRequest.ProtoReflect.Descriptor instead.
func (*IssuePublisherCredentialRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{10}
}

func (x *IssuePublisherCredentialRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *IssuePublisherCredentialRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *IssuePublisherCredentialRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type IssuePublisherCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *PublisherCredential   `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	ReplayUntil   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=replay_until,json=replayUntil,proto3" json:"replay_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssuePublisherCredentialResponse) Reset() {
	*x = IssuePublisherCredentialResponse{}
	mi := &file_image_v1_image_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssuePublisherCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssuePublisherCredentialResponse) ProtoMessage() {}

func (x *IssuePublisherCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssuePublisherCredentialResponse.ProtoReflect.Descriptor instead.
func (*IssuePublisherCredentialResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{11}
}

func (x *IssuePublisherCredentialResponse) GetCredential() *PublisherCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *IssuePublisherCredentialResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *IssuePublisherCredentialResponse) GetReplayUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ReplayUntil
	}
	return nil
}

type ResetPublisherCredentialRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ResetPublisherCredentialRequest) Reset() {
	*x = ResetPublisherCredentialRequest{}
	mi := &file_image_v1_image_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPublisherCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPublisherCredentialRequest) ProtoMessage() {}

func (x *ResetPublisherCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPublisherCredentialRequest.ProtoReflect.Descriptor instead.
func (*ResetPublisherCredentialRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{12}
}

func (x *ResetPublisherCredentialRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResetPublisherCredentialRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ResetPublisherCredentialRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

type ResetPublisherCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *PublisherCredential   `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	Secret        string                 `protobuf:"bytes,2,opt,name=secret,proto3" json:"secret,omitempty"`
	ReplayUntil   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=replay_until,json=replayUntil,proto3" json:"replay_until,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPublisherCredentialResponse) Reset() {
	*x = ResetPublisherCredentialResponse{}
	mi := &file_image_v1_image_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPublisherCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPublisherCredentialResponse) ProtoMessage() {}

func (x *ResetPublisherCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPublisherCredentialResponse.ProtoReflect.Descriptor instead.
func (*ResetPublisherCredentialResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{13}
}

func (x *ResetPublisherCredentialResponse) GetCredential() *PublisherCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *ResetPublisherCredentialResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *ResetPublisherCredentialResponse) GetReplayUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ReplayUntil
	}
	return nil
}

type DisablePublisherCredentialRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,2,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,3,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DisablePublisherCredentialRequest) Reset() {
	*x = DisablePublisherCredentialRequest{}
	mi := &file_image_v1_image_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePublisherCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePublisherCredentialRequest) ProtoMessage() {}

func (x *DisablePublisherCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisablePublisherCredentialRequest.ProtoReflect.Descriptor instead.
func (*DisablePublisherCredentialRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{14}
}

func (x *DisablePublisherCredentialRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DisablePublisherCredentialRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *DisablePublisherCredentialRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type DisablePublisherCredentialResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Credential    *PublisherCredential   `protobuf:"bytes,1,opt,name=credential,proto3" json:"credential,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DisablePublisherCredentialResponse) Reset() {
	*x = DisablePublisherCredentialResponse{}
	mi := &file_image_v1_image_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DisablePublisherCredentialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisablePublisherCredentialResponse) ProtoMessage() {}

func (x *DisablePublisherCredentialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisablePublisherCredentialResponse.ProtoReflect.Descriptor instead.
func (*DisablePublisherCredentialResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{15}
}

func (x *DisablePublisherCredentialResponse) GetCredential() *PublisherCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

type RegisterImageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ImageReference string                 `protobuf:"bytes,2,opt,name=image_reference,json=imageReference,proto3" json:"image_reference,omitempty"`
	DisplayName    string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description    string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Purposes       []ImagePurpose         `protobuf:"varint,5,rep,packed,name=purposes,proto3,enum=image.v1.ImagePurpose" json:"purposes,omitempty"`
	Accelerator    AcceleratorKind        `protobuf:"varint,6,opt,name=accelerator,proto3,enum=image.v1.AcceleratorKind" json:"accelerator,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RegisterImageRequest) Reset() {
	*x = RegisterImageRequest{}
	mi := &file_image_v1_image_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterImageRequest) ProtoMessage() {}

func (x *RegisterImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterImageRequest.ProtoReflect.Descriptor instead.
func (*RegisterImageRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{16}
}

func (x *RegisterImageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RegisterImageRequest) GetImageReference() string {
	if x != nil {
		return x.ImageReference
	}
	return ""
}

func (x *RegisterImageRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *RegisterImageRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RegisterImageRequest) GetPurposes() []ImagePurpose {
	if x != nil {
		return x.Purposes
	}
	return nil
}

func (x *RegisterImageRequest) GetAccelerator() AcceleratorKind {
	if x != nil {
		return x.Accelerator
	}
	return AcceleratorKind_ACCELERATOR_KIND_UNSPECIFIED
}

func (x *RegisterImageRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type RegisterImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImageRegistration     `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterImageResponse) Reset() {
	*x = RegisterImageResponse{}
	mi := &file_image_v1_image_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterImageResponse) ProtoMessage() {}

func (x *RegisterImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterImageResponse.ProtoReflect.Descriptor instead.
func (*RegisterImageResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{17}
}

func (x *RegisterImageResponse) GetImage() *ImageRegistration {
	if x != nil {
		return x.Image
	}
	return nil
}

type GetImageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scope         ImageScope             `protobuf:"varint,2,opt,name=scope,proto3,enum=image.v1.ImageScope" json:"scope,omitempty"`
	ImageId       string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageRequest) Reset() {
	*x = GetImageRequest{}
	mi := &file_image_v1_image_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageRequest) ProtoMessage() {}

func (x *GetImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageRequest.ProtoReflect.Descriptor instead.
func (*GetImageRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{18}
}

func (x *GetImageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetImageRequest) GetScope() ImageScope {
	if x != nil {
		return x.Scope
	}
	return ImageScope_IMAGE_SCOPE_UNSPECIFIED
}

func (x *GetImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

type GetImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImageRegistration     `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetImageResponse) Reset() {
	*x = GetImageResponse{}
	mi := &file_image_v1_image_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetImageResponse) ProtoMessage() {}

func (x *GetImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetImageResponse.ProtoReflect.Descriptor instead.
func (*GetImageResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{19}
}

func (x *GetImageResponse) GetImage() *ImageRegistration {
	if x != nil {
		return x.Image
	}
	return nil
}

type ListImagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scope         ImageScope             `protobuf:"varint,2,opt,name=scope,proto3,enum=image.v1.ImageScope" json:"scope,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Purposes      []ImagePurpose         `protobuf:"varint,4,rep,packed,name=purposes,proto3,enum=image.v1.ImagePurpose" json:"purposes,omitempty"`
	Accelerator   AcceleratorKind        `protobuf:"varint,5,opt,name=accelerator,proto3,enum=image.v1.AcceleratorKind" json:"accelerator,omitempty"`
	Limit         int32                  `protobuf:"varint,6,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,7,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesRequest) Reset() {
	*x = ListImagesRequest{}
	mi := &file_image_v1_image_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesRequest) ProtoMessage() {}

func (x *ListImagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesRequest.ProtoReflect.Descriptor instead.
func (*ListImagesRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{20}
}

func (x *ListImagesRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ListImagesRequest) GetScope() ImageScope {
	if x != nil {
		return x.Scope
	}
	return ImageScope_IMAGE_SCOPE_UNSPECIFIED
}

func (x *ListImagesRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListImagesRequest) GetPurposes() []ImagePurpose {
	if x != nil {
		return x.Purposes
	}
	return nil
}

func (x *ListImagesRequest) GetAccelerator() AcceleratorKind {
	if x != nil {
		return x.Accelerator
	}
	return AcceleratorKind_ACCELERATOR_KIND_UNSPECIFIED
}

func (x *ListImagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListImagesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListImagesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ImageRegistration   `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListImagesResponse) Reset() {
	*x = ListImagesResponse{}
	mi := &file_image_v1_image_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListImagesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListImagesResponse) ProtoMessage() {}

func (x *ListImagesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListImagesResponse.ProtoReflect.Descriptor instead.
func (*ListImagesResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{21}
}

func (x *ListImagesResponse) GetItems() []*ImageRegistration {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListImagesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListImagesResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateImageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ImageId         string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	DisplayName     string                 `protobuf:"bytes,3,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Description     string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Purposes        []ImagePurpose         `protobuf:"varint,5,rep,packed,name=purposes,proto3,enum=image.v1.ImagePurpose" json:"purposes,omitempty"`
	Accelerator     AcceleratorKind        `protobuf:"varint,6,opt,name=accelerator,proto3,enum=image.v1.AcceleratorKind" json:"accelerator,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,7,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,8,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateImageRequest) Reset() {
	*x = UpdateImageRequest{}
	mi := &file_image_v1_image_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateImageRequest) ProtoMessage() {}

func (x *UpdateImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateImageRequest.ProtoReflect.Descriptor instead.
func (*UpdateImageRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{22}
}

func (x *UpdateImageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UpdateImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *UpdateImageRequest) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UpdateImageRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateImageRequest) GetPurposes() []ImagePurpose {
	if x != nil {
		return x.Purposes
	}
	return nil
}

func (x *UpdateImageRequest) GetAccelerator() AcceleratorKind {
	if x != nil {
		return x.Accelerator
	}
	return AcceleratorKind_ACCELERATOR_KIND_UNSPECIFIED
}

func (x *UpdateImageRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *UpdateImageRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UpdateImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImageRegistration     `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateImageResponse) Reset() {
	*x = UpdateImageResponse{}
	mi := &file_image_v1_image_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateImageResponse) ProtoMessage() {}

func (x *UpdateImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateImageResponse.ProtoReflect.Descriptor instead.
func (*UpdateImageResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateImageResponse) GetImage() *ImageRegistration {
	if x != nil {
		return x.Image
	}
	return nil
}

type UnregisterImageRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	TenantId        string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ImageId         string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	ExpectedVersion int64                  `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	IdempotencyKey  string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UnregisterImageRequest) Reset() {
	*x = UnregisterImageRequest{}
	mi := &file_image_v1_image_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterImageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterImageRequest) ProtoMessage() {}

func (x *UnregisterImageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterImageRequest.ProtoReflect.Descriptor instead.
func (*UnregisterImageRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{24}
}

func (x *UnregisterImageRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *UnregisterImageRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *UnregisterImageRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *UnregisterImageRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type UnregisterImageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Image         *ImageRegistration     `protobuf:"bytes,1,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnregisterImageResponse) Reset() {
	*x = UnregisterImageResponse{}
	mi := &file_image_v1_image_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnregisterImageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnregisterImageResponse) ProtoMessage() {}

func (x *UnregisterImageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_image_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnregisterImageResponse.ProtoReflect.Descriptor instead.
func (*UnregisterImageResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_image_proto_rawDescGZIP(), []int{25}
}

func (x *UnregisterImageResponse) GetImage() *ImageRegistration {
	if x != nil {
		return x.Image
	}
	return nil
}

var File_image_v1_image_proto protoreflect.FileDescriptor

const file_image_v1_image_proto_rawDesc = "" +
	"\n" +
	"\x14image/v1/image.proto\x12\bimage.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"]\n" +
	"\rImagePlatform\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\"\n" +
	"\farchitecture\x18\x02 \x01(\tR\farchitecture\x12\x18\n" +
	"\avariant\x18\x03 \x01(\tR\avariant\"\x92\x03\n" +
	"\n" +
	"ImageSpace\x12\x19\n" +
	"\bspace_id\x18\x01 \x01(\tR\aspaceId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12!\n" +
	"\fproject_name\x18\x03 \x01(\tR\vprojectName\x12-\n" +
	"\x12registry_authority\x18\x04 \x01(\tR\x11registryAuthority\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x16\n" +
	"\x06reason\x18\x06 \x01(\tR\x06reason\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\x12<\n" +
	"\x1apull_credential_generation\x18\b \x01(\x03R\x18pullCredentialGeneration\x129\n" +
	"\n" +
	"created_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xaf\x02\n" +
	"\x13PublisherCredential\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x12\x1e\n" +
	"\n" +
	"generation\x18\x03 \x01(\x03R\n" +
	"generation\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x14\n" +
	"\x05state\x18\x05 \x01(\tR\x05state\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x03R\aversion\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\n" +
	"updated_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xe6\x05\n" +
	"\x11ImageRegistration\x12\x19\n" +
	"\bimage_id\x18\x01 \x01(\tR\aimageId\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12*\n" +
	"\x05scope\x18\x03 \x01(\x0e2\x14.image.v1.ImageScopeR\x05scope\x12\x19\n" +
	"\bspace_id\x18\x04 \x01(\tR\aspaceId\x12!\n" +
	"\fdisplay_name\x18\x05 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12\x1e\n" +
	"\n" +
	"repository\x18\a \x01(\tR\n" +
	"repository\x12)\n" +
	"\x10source_reference\x18\b \x01(\tR\x0fsourceReference\x12\x16\n" +
	"\x06digest\x18\t \x01(\tR\x06digest\x12-\n" +
	"\x12resolved_reference\x18\n" +
	" \x01(\tR\x11resolvedReference\x125\n" +
	"\tplatforms\x18\v \x03(\v2\x17.image.v1.ImagePlatformR\tplatforms\x122\n" +
	"\bpurposes\x18\f \x03(\x0e2\x16.image.v1.ImagePurposeR\bpurposes\x12;\n" +
	"\vaccelerator\x18\r \x01(\x0e2\x19.image.v1.AcceleratorKindR\vaccelerator\x12\x18\n" +
	"\aversion\x18\x0e \x01(\x03R\aversion\x129\n" +
	"\n" +
	"created_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x10 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12C\n" +
	"\x0funregistered_at\x18\x11 \x01(\v2\x1a.google.protobuf.TimestampR\x0eunregisteredAt\"s\n" +
	"\x17EnsureImageSpaceRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x12\n" +
	"\x04slug\x18\x02 \x01(\tR\x04slug\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"F\n" +
	"\x18EnsureImageSpaceResponse\x12*\n" +
	"\x05space\x18\x01 \x01(\v2\x14.image.v1.ImageSpaceR\x05space\"3\n" +
	"\x14GetImageSpaceRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"C\n" +
	"\x15GetImageSpaceResponse\x12*\n" +
	"\x05space\x18\x01 \x01(\v2\x14.image.v1.ImageSpaceR\x05space\"<\n" +
	"\x1dGetPublisherCredentialRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"_\n" +
	"\x1eGetPublisherCredentialResponse\x12=\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x1d.image.v1.PublisherCredentialR\n" +
	"credential\"\x92\x01\n" +
	"\x1fIssuePublisherCredentialRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\"\xb8\x01\n" +
	" IssuePublisherCredentialResponse\x12=\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x1d.image.v1.PublisherCredentialR\n" +
	"credential\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12=\n" +
	"\freplay_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vreplayUntil\"\x92\x01\n" +
	"\x1fResetPublisherCredentialRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\"\xb8\x01\n" +
	" ResetPublisherCredentialResponse\x12=\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x1d.image.v1.PublisherCredentialR\n" +
	"credential\x12\x16\n" +
	"\x06secret\x18\x02 \x01(\tR\x06secret\x12=\n" +
	"\freplay_until\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vreplayUntil\"\x94\x01\n" +
	"!DisablePublisherCredentialRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12)\n" +
	"\x10expected_version\x18\x02 \x01(\x03R\x0fexpectedVersion\x12'\n" +
	"\x0fidempotency_key\x18\x03 \x01(\tR\x0eidempotencyKey\"c\n" +
	"\"DisablePublisherCredentialResponse\x12=\n" +
	"\n" +
	"credential\x18\x01 \x01(\v2\x1d.image.v1.PublisherCredentialR\n" +
	"credential\"\xbb\x02\n" +
	"\x14RegisterImageRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12'\n" +
	"\x0fimage_reference\x18\x02 \x01(\tR\x0eimageReference\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x122\n" +
	"\bpurposes\x18\x05 \x03(\x0e2\x16.image.v1.ImagePurposeR\bpurposes\x12;\n" +
	"\vaccelerator\x18\x06 \x01(\x0e2\x19.image.v1.AcceleratorKindR\vaccelerator\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"J\n" +
	"\x15RegisterImageResponse\x121\n" +
	"\x05image\x18\x01 \x01(\v2\x1b.image.v1.ImageRegistrationR\x05image\"u\n" +
	"\x0fGetImageRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12*\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x14.image.v1.ImageScopeR\x05scope\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\"E\n" +
	"\x10GetImageResponse\x121\n" +
	"\x05image\x18\x01 \x01(\v2\x1b.image.v1.ImageRegistrationR\x05image\"\x93\x02\n" +
	"\x11ListImagesRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12*\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x14.image.v1.ImageScopeR\x05scope\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x122\n" +
	"\bpurposes\x18\x04 \x03(\x0e2\x16.image.v1.ImagePurposeR\bpurposes\x12;\n" +
	"\vaccelerator\x18\x05 \x01(\x0e2\x19.image.v1.AcceleratorKindR\vaccelerator\x12\x14\n" +
	"\x05limit\x18\x06 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\a \x01(\tR\x06cursor\"~\n" +
	"\x12ListImagesResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.image.v1.ImageRegistrationR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\xd6\x02\n" +
	"\x12UpdateImageRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12!\n" +
	"\fdisplay_name\x18\x03 \x01(\tR\vdisplayName\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x122\n" +
	"\bpurposes\x18\x05 \x03(\x0e2\x16.image.v1.ImagePurposeR\bpurposes\x12;\n" +
	"\vaccelerator\x18\x06 \x01(\x0e2\x19.image.v1.AcceleratorKindR\vaccelerator\x12)\n" +
	"\x10expected_version\x18\a \x01(\x03R\x0fexpectedVersion\x12'\n" +
	"\x0fidempotency_key\x18\b \x01(\tR\x0eidempotencyKey\"H\n" +
	"\x13UpdateImageResponse\x121\n" +
	"\x05image\x18\x01 \x01(\v2\x1b.image.v1.ImageRegistrationR\x05image\"\xa4\x01\n" +
	"\x16UnregisterImageRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"L\n" +
	"\x17UnregisterImageResponse\x121\n" +
	"\x05image\x18\x01 \x01(\v2\x1b.image.v1.ImageRegistrationR\x05image*[\n" +
	"\n" +
	"ImageScope\x12\x1b\n" +
	"\x17IMAGE_SCOPE_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12IMAGE_SCOPE_TENANT\x10\x01\x12\x18\n" +
	"\x14IMAGE_SCOPE_PLATFORM\x10\x02*\xc0\x01\n" +
	"\fImagePurpose\x12\x1d\n" +
	"\x19IMAGE_PURPOSE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17IMAGE_PURPOSE_CONTAINER\x10\x01\x12\x1d\n" +
	"\x19IMAGE_PURPOSE_DEVELOPMENT\x10\x02\x12\x1b\n" +
	"\x17IMAGE_PURPOSE_INFERENCE\x10\x03\x12\x1c\n" +
	"\x18IMAGE_PURPOSE_FINETUNING\x10\x04\x12\x1a\n" +
	"\x16IMAGE_PURPOSE_TRAINING\x10\x05*\xbe\x01\n" +
	"\x0fAcceleratorKind\x12 \n" +
	"\x1cACCELERATOR_KIND_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15ACCELERATOR_KIND_NONE\x10\x01\x12\x1b\n" +
	"\x17ACCELERATOR_KIND_NVIDIA\x10\x02\x12\x18\n" +
	"\x14ACCELERATOR_KIND_AMD\x10\x03\x12\x1b\n" +
	"\x17ACCELERATOR_KIND_ASCEND\x10\x04\x12\x1a\n" +
	"\x16ACCELERATOR_KIND_OTHER\x10\x052\x8f\b\n" +
	"\x12TenantImageService\x12Y\n" +
	"\x10EnsureImageSpace\x12!.image.v1.EnsureImageSpaceRequest\x1a\".image.v1.EnsureImageSpaceResponse\x12P\n" +
	"\rGetImageSpace\x12\x1e.image.v1.GetImageSpaceRequest\x1a\x1f.image.v1.GetImageSpaceResponse\x12k\n" +
	"\x16GetPublisherCredential\x12'.image.v1.GetPublisherCredentialRequest\x1a(.image.v1.GetPublisherCredentialResponse\x12q\n" +
	"\x18IssuePublisherCredential\x12).image.v1.IssuePublisherCredentialRequest\x1a*.image.v1.IssuePublisherCredentialResponse\x12q\n" +
	"\x18ResetPublisherCredential\x12).image.v1.ResetPublisherCredentialRequest\x1a*.image.v1.ResetPublisherCredentialResponse\x12w\n" +
	"\x1aDisablePublisherCredential\x12+.image.v1.DisablePublisherCredentialRequest\x1a,.image.v1.DisablePublisherCredentialResponse\x12P\n" +
	"\rRegisterImage\x12\x1e.image.v1.RegisterImageRequest\x1a\x1f.image.v1.RegisterImageResponse\x12A\n" +
	"\bGetImage\x12\x19.image.v1.GetImageRequest\x1a\x1a.image.v1.GetImageResponse\x12G\n" +
	"\n" +
	"ListImages\x12\x1b.image.v1.ListImagesRequest\x1a\x1c.image.v1.ListImagesResponse\x12J\n" +
	"\vUpdateImage\x12\x1c.image.v1.UpdateImageRequest\x1a\x1d.image.v1.UpdateImageResponse\x12V\n" +
	"\x0fUnregisterImage\x12 .image.v1.UnregisterImageRequest\x1a!.image.v1.UnregisterImageResponseBDZBgithub.com/zhangzhe-ctrl/ani-resource-service/api/image/v1;imagev1b\x06proto3"

var (
	file_image_v1_image_proto_rawDescOnce sync.Once
	file_image_v1_image_proto_rawDescData []byte
)

func file_image_v1_image_proto_rawDescGZIP() []byte {
	file_image_v1_image_proto_rawDescOnce.Do(func() {
		file_image_v1_image_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_image_v1_image_proto_rawDesc), len(file_image_v1_image_proto_rawDesc)))
	})
	return file_image_v1_image_proto_rawDescData
}

var file_image_v1_image_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_image_v1_image_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_image_v1_image_proto_goTypes = []any{
	(ImageScope)(0),                            // 0: image.v1.ImageScope
	(ImagePurpose)(0),                          // 1: image.v1.ImagePurpose
	(AcceleratorKind)(0),                       // 2: image.v1.AcceleratorKind
	(*ImagePlatform)(nil),                      // 3: image.v1.ImagePlatform
	(*ImageSpace)(nil),                         // 4: image.v1.ImageSpace
	(*PublisherCredential)(nil),                // 5: image.v1.PublisherCredential
	(*ImageRegistration)(nil),                  // 6: image.v1.ImageRegistration
	(*EnsureImageSpaceRequest)(nil),            // 7: image.v1.EnsureImageSpaceRequest
	(*EnsureImageSpaceResponse)(nil),           // 8: image.v1.EnsureImageSpaceResponse
	(*GetImageSpaceRequest)(nil),               // 9: image.v1.GetImageSpaceRequest
	(*GetImageSpaceResponse)(nil),              // 10: image.v1.GetImageSpaceResponse
	(*GetPublisherCredentialRequest)(nil),      // 11: image.v1.GetPublisherCredentialRequest
	(*GetPublisherCredentialResponse)(nil),     // 12: image.v1.GetPublisherCredentialResponse
	(*IssuePublisherCredentialRequest)(nil),    // 13: image.v1.IssuePublisherCredentialRequest
	(*IssuePublisherCredentialResponse)(nil),   // 14: image.v1.IssuePublisherCredentialResponse
	(*ResetPublisherCredentialRequest)(nil),    // 15: image.v1.ResetPublisherCredentialRequest
	(*ResetPublisherCredentialResponse)(nil),   // 16: image.v1.ResetPublisherCredentialResponse
	(*DisablePublisherCredentialRequest)(nil),  // 17: image.v1.DisablePublisherCredentialRequest
	(*DisablePublisherCredentialResponse)(nil), // 18: image.v1.DisablePublisherCredentialResponse
	(*RegisterImageRequest)(nil),               // 19: image.v1.RegisterImageRequest
	(*RegisterImageResponse)(nil),              // 20: image.v1.RegisterImageResponse
	(*GetImageRequest)(nil),                    // 21: image.v1.GetImageRequest
	(*GetImageResponse)(nil),                   // 22: image.v1.GetImageResponse
	(*ListImagesRequest)(nil),                  // 23: image.v1.ListImagesRequest
	(*ListImagesResponse)(nil),                 // 24: image.v1.ListImagesResponse
	(*UpdateImageRequest)(nil),                 // 25: image.v1.UpdateImageRequest
	(*UpdateImageResponse)(nil),                // 26: image.v1.UpdateImageResponse
	(*UnregisterImageRequest)(nil),             // 27: image.v1.UnregisterImageRequest
	(*UnregisterImageResponse)(nil),            // 28: image.v1.UnregisterImageResponse
	(*timestamppb.Timestamp)(nil),              // 29: google.protobuf.Timestamp
}
var file_image_v1_image_proto_depIdxs = []int32{
	29, // 0: image.v1.ImageSpace.created_at:type_name -> google.protobuf.Timestamp
	29, // 1: image.v1.ImageSpace.updated_at:type_name -> google.protobuf.Timestamp
	29, // 2: image.v1.PublisherCredential.expires_at:type_name -> google.protobuf.Timestamp
	29, // 3: image.v1.PublisherCredential.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 4: image.v1.ImageRegistration.scope:type_name -> image.v1.ImageScope
	3,  // 5: image.v1.ImageRegistration.platforms:type_name -> image.v1.ImagePlatform
	1,  // 6: image.v1.ImageRegistration.purposes:type_name -> image.v1.ImagePurpose
	2,  // 7: image.v1.ImageRegistration.accelerator:type_name -> image.v1.AcceleratorKind
	29, // 8: image.v1.ImageRegistration.created_at:type_name -> google.protobuf.Timestamp
	29, // 9: image.v1.ImageRegistration.updated_at:type_name -> google.protobuf.Timestamp
	29, // 10: image.v1.ImageRegistration.unregistered_at:type_name -> google.protobuf.Timestamp
	4,  // 11: image.v1.EnsureImageSpaceResponse.space:type_name -> image.v1.ImageSpace
	4,  // 12: image.v1.GetImageSpaceResponse.space:type_name -> image.v1.ImageSpace
	5,  // 13: image.v1.GetPublisherCredentialResponse.credential:type_name -> image.v1.PublisherCredential
	5,  // 14: image.v1.IssuePublisherCredentialResponse.credential:type_name -> image.v1.PublisherCredential
	29, // 15: image.v1.IssuePublisherCredentialResponse.replay_until:type_name -> google.protobuf.Timestamp
	5,  // 16: image.v1.ResetPublisherCredentialResponse.credential:type_name -> image.v1.PublisherCredential
	29, // 17: image.v1.ResetPublisherCredentialResponse.replay_until:type_name -> google.protobuf.Timestamp
	5,  // 18: image.v1.DisablePublisherCredentialResponse.credential:type_name -> image.v1.PublisherCredential
	1,  // 19: image.v1.RegisterImageRequest.purposes:type_name -> image.v1.ImagePurpose
	2,  // 20: image.v1.RegisterImageRequest.accelerator:type_name -> image.v1.AcceleratorKind
	6,  // 21: image.v1.RegisterImageResponse.image:type_name -> image.v1.ImageRegistration
	0,  // 22: image.v1.GetImageRequest.scope:type_name -> image.v1.ImageScope
	6,  // 23: image.v1.GetImageResponse.image:type_name -> image.v1.ImageRegistration
	0,  // 24: image.v1.ListImagesRequest.scope:type_name -> image.v1.ImageScope
	1,  // 25: image.v1.ListImagesRequest.purposes:type_name -> image.v1.ImagePurpose
	2,  // 26: image.v1.ListImagesRequest.accelerator:type_name -> image.v1.AcceleratorKind
	6,  // 27: image.v1.ListImagesResponse.items:type_name -> image.v1.ImageRegistration
	1,  // 28: image.v1.UpdateImageRequest.purposes:type_name -> image.v1.ImagePurpose
	2,  // 29: image.v1.UpdateImageRequest.accelerator:type_name -> image.v1.AcceleratorKind
	6,  // 30: image.v1.UpdateImageResponse.image:type_name -> image.v1.ImageRegistration
	6,  // 31: image.v1.UnregisterImageResponse.image:type_name -> image.v1.ImageRegistration
	7,  // 32: image.v1.TenantImageService.EnsureImageSpace:input_type -> image.v1.EnsureImageSpaceRequest
	9,  // 33: image.v1.TenantImageService.GetImageSpace:input_type -> image.v1.GetImageSpaceRequest
	11, // 34: image.v1.TenantImageService.GetPublisherCredential:input_type -> image.v1.GetPublisherCredentialRequest
	13, // 35: image.v1.TenantImageService.IssuePublisherCredential:input_type -> image.v1.IssuePublisherCredentialRequest
	15, // 36: image.v1.TenantImageService.ResetPublisherCredential:input_type -> image.v1.ResetPublisherCredentialRequest
	17, // 37: image.v1.TenantImageService.DisablePublisherCredential:input_type -> image.v1.DisablePublisherCredentialRequest
	19, // 38: image.v1.TenantImageService.RegisterImage:input_type -> image.v1.RegisterImageRequest
	21, // 39: image.v1.TenantImageService.GetImage:input_type -> image.v1.GetImageRequest
	23, // 40: image.v1.TenantImageService.ListImages:input_type -> image.v1.ListImagesRequest
	25, // 41: image.v1.TenantImageService.UpdateImage:input_type -> image.v1.UpdateImageRequest
	27, // 42: image.v1.TenantImageService.UnregisterImage:input_type -> image.v1.UnregisterImageRequest
	8,  // 43: image.v1.TenantImageService.EnsureImageSpace:output_type -> image.v1.EnsureImageSpaceResponse
	10, // 44: image.v1.TenantImageService.GetImageSpace:output_type -> image.v1.GetImageSpaceResponse
	12, // 45: image.v1.TenantImageService.GetPublisherCredential:output_type -> image.v1.GetPublisherCredentialResponse
	14, // 46: image.v1.TenantImageService.IssuePublisherCredential:output_type -> image.v1.IssuePublisherCredentialResponse
	16, // 47: image.v1.TenantImageService.ResetPublisherCredential:output_type -> image.v1.ResetPublisherCredentialResponse
	18, // 48: image.v1.TenantImageService.DisablePublisherCredential:output_type -> image.v1.DisablePublisherCredentialResponse
	20, // 49: image.v1.TenantImageService.RegisterImage:output_type -> image.v1.RegisterImageResponse
	22, // 50: image.v1.TenantImageService.GetImage:output_type -> image.v1.GetImageResponse
	24, // 51: image.v1.TenantImageService.ListImages:output_type -> image.v1.ListImagesResponse
	26, // 52: image.v1.TenantImageService.UpdateImage:output_type -> image.v1.UpdateImageResponse
	28, // 53: image.v1.TenantImageService.UnregisterImage:output_type -> image.v1.UnregisterImageResponse
	43, // [43:54] is the sub-list for method output_type
	32, // [32:43] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_image_v1_image_proto_init() }
func file_image_v1_image_proto_init() {
	if File_image_v1_image_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_image_v1_image_proto_rawDesc), len(file_image_v1_image_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_v1_image_proto_goTypes,
		DependencyIndexes: file_image_v1_image_proto_depIdxs,
		EnumInfos:         file_image_v1_image_proto_enumTypes,
		MessageInfos:      file_image_v1_image_proto_msgTypes,
	}.Build()
	File_image_v1_image_proto = out.File
	file_image_v1_image_proto_goTypes = nil
	file_image_v1_image_proto_depIdxs = nil
}
