// Internal-only contract. NEVER expose through public HTTP or tenant allowlist.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: image/v1/runtime.proto

package imagev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResolveImageForWorkloadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TenantId       string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	Scope          ImageScope             `protobuf:"varint,2,opt,name=scope,proto3,enum=image.v1.ImageScope" json:"scope,omitempty"`
	ImageId        string                 `protobuf:"bytes,3,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	TargetPlatform *ImagePlatform         `protobuf:"bytes,4,opt,name=target_platform,json=targetPlatform,proto3" json:"target_platform,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveImageForWorkloadRequest) Reset() {
	*x = ResolveImageForWorkloadRequest{}
	mi := &file_image_v1_runtime_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveImageForWorkloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveImageForWorkloadRequest) ProtoMessage() {}

func (x *ResolveImageForWorkloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_runtime_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveImageForWorkloadRequest.ProtoReflect.Descriptor instead.
func (*ResolveImageForWorkloadRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_runtime_proto_rawDescGZIP(), []int{0}
}

func (x *ResolveImageForWorkloadRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResolveImageForWorkloadRequest) GetScope() ImageScope {
	if x != nil {
		return x.Scope
	}
	return ImageScope_IMAGE_SCOPE_UNSPECIFIED
}

func (x *ResolveImageForWorkloadRequest) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ResolveImageForWorkloadRequest) GetTargetPlatform() *ImagePlatform {
	if x != nil {
		return x.TargetPlatform
	}
	return nil
}

type ResolveImageForWorkloadResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // requesting tenant, including platform-image use
	ImageId           string                 `protobuf:"bytes,2,opt,name=image_id,json=imageId,proto3" json:"image_id,omitempty"`
	Scope             ImageScope             `protobuf:"varint,3,opt,name=scope,proto3,enum=image.v1.ImageScope" json:"scope,omitempty"`
	ResolvedReference string                 `protobuf:"bytes,4,opt,name=resolved_reference,json=resolvedReference,proto3" json:"resolved_reference,omitempty"`
	Digest            string                 `protobuf:"bytes,5,opt,name=digest,proto3" json:"digest,omitempty"`
	ImageVersion      int64                  `protobuf:"varint,6,opt,name=image_version,json=imageVersion,proto3" json:"image_version,omitempty"`
	SelectedPlatform  *ImagePlatform         `protobuf:"bytes,7,opt,name=selected_platform,json=selectedPlatform,proto3" json:"selected_platform,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ResolveImageForWorkloadResponse) Reset() {
	*x = ResolveImageForWorkloadResponse{}
	mi := &file_image_v1_runtime_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveImageForWorkloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveImageForWorkloadResponse) ProtoMessage() {}

func (x *ResolveImageForWorkloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_runtime_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveImageForWorkloadResponse.ProtoReflect.Descriptor instead.
func (*ResolveImageForWorkloadResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_runtime_proto_rawDescGZIP(), []int{1}
}

func (x *ResolveImageForWorkloadResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ResolveImageForWorkloadResponse) GetImageId() string {
	if x != nil {
		return x.ImageId
	}
	return ""
}

func (x *ResolveImageForWorkloadResponse) GetScope() ImageScope {
	if x != nil {
		return x.Scope
	}
	return ImageScope_IMAGE_SCOPE_UNSPECIFIED
}

func (x *ResolveImageForWorkloadResponse) GetResolvedReference() string {
	if x != nil {
		return x.ResolvedReference
	}
	return ""
}

func (x *ResolveImageForWorkloadResponse) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *ResolveImageForWorkloadResponse) GetImageVersion() int64 {
	if x != nil {
		return x.ImageVersion
	}
	return 0
}

func (x *ResolveImageForWorkloadResponse) GetSelectedPlatform() *ImagePlatform {
	if x != nil {
		return x.SelectedPlatform
	}
	return nil
}

type GetTenantPullMaterialRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTenantPullMaterialRequest) Reset() {
	*x = GetTenantPullMaterialRequest{}
	mi := &file_image_v1_runtime_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantPullMaterialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantPullMaterialRequest) ProtoMessage() {}

func (x *GetTenantPullMaterialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_runtime_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantPullMaterialRequest.ProtoReflect.Descriptor instead.
func (*GetTenantPullMaterialRequest) Descriptor() ([]byte, []int) {
	return file_image_v1_runtime_proto_rawDescGZIP(), []int{2}
}

func (x *GetTenantPullMaterialRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

type GetTenantPullMaterialResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	SpaceId           string                 `protobuf:"bytes,2,opt,name=space_id,json=spaceId,proto3" json:"space_id,omitempty"`
	RegistryAuthority string                 `protobuf:"bytes,3,opt,name=registry_authority,json=registryAuthority,proto3" json:"registry_authority,omitempty"`
	Username          string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Secret            string                 `protobuf:"bytes,5,opt,name=secret,proto3" json:"secret,omitempty"` // Sensitive: no logs/traces/public response/cache.
	Generation        int64                  `protobuf:"varint,6,opt,name=generation,proto3" json:"generation,omitempty"`
	ExpiresAt         *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // absent only for explicitly never-expiring identity
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTenantPullMaterialResponse) Reset() {
	*x = GetTenantPullMaterialResponse{}
	mi := &file_image_v1_runtime_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTenantPullMaterialResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTenantPullMaterialResponse) ProtoMessage() {}

func (x *GetTenantPullMaterialResponse) ProtoReflect() protoreflect.Message {
	mi := &file_image_v1_runtime_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTenantPullMaterialResponse.ProtoReflect.Descriptor instead.
func (*GetTenantPullMaterialResponse) Descriptor() ([]byte, []int) {
	return file_image_v1_runtime_proto_rawDescGZIP(), []int{3}
}

func (x *GetTenantPullMaterialResponse) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetTenantPullMaterialResponse) GetSpaceId() string {
	if x != nil {
		return x.SpaceId
	}
	return ""
}

func (x *GetTenantPullMaterialResponse) GetRegistryAuthority() string {
	if x != nil {
		return x.RegistryAuthority
	}
	return ""
}

func (x *GetTenantPullMaterialResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetTenantPullMaterialResponse) GetSecret() string {
	if x != nil {
		return x.Secret
	}
	return ""
}

func (x *GetTenantPullMaterialResponse) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *GetTenantPullMaterialResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

var File_image_v1_runtime_proto protoreflect.FileDescriptor

const file_image_v1_runtime_proto_rawDesc = "" +
	"\n" +
	"\x16image/v1/runtime.proto\x12\bimage.v1\x1a\x14image/v1/image.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x01\n" +
	"\x1eResolveImageForWorkloadRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12*\n" +
	"\x05scope\x18\x02 \x01(\x0e2\x14.image.v1.ImageScopeR\x05scope\x12\x19\n" +
	"\bimage_id\x18\x03 \x01(\tR\aimageId\x12@\n" +
	"\x0ftarget_platform\x18\x04 \x01(\v2\x17.image.v1.ImagePlatformR\x0etargetPlatform\"\xb7\x02\n" +
	"\x1fResolveImageForWorkloadResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bimage_id\x18\x02 \x01(\tR\aimageId\x12*\n" +
	"\x05scope\x18\x03 \x01(\x0e2\x14.image.v1.ImageScopeR\x05scope\x12-\n" +
	"\x12resolved_reference\x18\x04 \x01(\tR\x11resolvedReference\x12\x16\n" +
	"\x06digest\x18\x05 \x01(\tR\x06digest\x12#\n" +
	"\rimage_version\x18\x06 \x01(\x03R\fimageVersion\x12D\n" +
	"\x11selected_platform\x18\a \x01(\v2\x17.image.v1.ImagePlatformR\x10selectedPlatform\";\n" +
	"\x1cGetTenantPullMaterialRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\"\x95\x02\n" +
	"\x1dGetTenantPullMaterialResponse\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bspace_id\x18\x02 \x01(\tR\aspaceId\x12-\n" +
	"\x12registry_authority\x18\x03 \x01(\tR\x11registryAuthority\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x16\n" +
	"\x06secret\x18\x05 \x01(\tR\x06secret\x12\x1e\n" +
	"\n" +
	"generation\x18\x06 \x01(\x03R\n" +
	"generation\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt2\xef\x01\n" +
	"\x13ImageRuntimeService\x12n\n" +
	"\x17ResolveImageForWorkload\x12(.image.v1.ResolveImageForWorkloadRequest\x1a).image.v1.ResolveImageForWorkloadResponse\x12h\n" +
	"\x15GetTenantPullMaterial\x12&.image.v1.GetTenantPullMaterialRequest\x1a'.image.v1.GetTenantPullMaterialResponseBDZBgithub.com/zhangzhe-ctrl/ani-resource-service/api/image/v1;imagev1b\x06proto3"

var (
	file_image_v1_runtime_proto_rawDescOnce sync.Once
	file_image_v1_runtime_proto_rawDescData []byte
)

func file_image_v1_runtime_proto_rawDescGZIP() []byte {
	file_image_v1_runtime_proto_rawDescOnce.Do(func() {
		file_image_v1_runtime_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_image_v1_runtime_proto_rawDesc), len(file_image_v1_runtime_proto_rawDesc)))
	})
	return file_image_v1_runtime_proto_rawDescData
}

var file_image_v1_runtime_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_image_v1_runtime_proto_goTypes = []any{
	(*ResolveImageForWorkloadRequest)(nil),  // 0: image.v1.ResolveImageForWorkloadRequest
	(*ResolveImageForWorkloadResponse)(nil), // 1: image.v1.ResolveImageForWorkloadResponse
	(*GetTenantPullMaterialRequest)(nil),    // 2: image.v1.GetTenantPullMaterialRequest
	(*GetTenantPullMaterialResponse)(nil),   // 3: image.v1.GetTenantPullMaterialResponse
	(ImageScope)(0),                         // 4: image.v1.ImageScope
	(*ImagePlatform)(nil),                   // 5: image.v1.ImagePlatform
	(*timestamppb.Timestamp)(nil),           // 6: google.protobuf.Timestamp
}
var file_image_v1_runtime_proto_depIdxs = []int32{
	4, // 0: image.v1.ResolveImageForWorkloadRequest.scope:type_name -> image.v1.ImageScope
	5, // 1: image.v1.ResolveImageForWorkloadRequest.target_platform:type_name -> image.v1.ImagePlatform
	4, // 2: image.v1.ResolveImageForWorkloadResponse.scope:type_name -> image.v1.ImageScope
	5, // 3: image.v1.ResolveImageForWorkloadResponse.selected_platform:type_name -> image.v1.ImagePlatform
	6, // 4: image.v1.GetTenantPullMaterialResponse.expires_at:type_name -> google.protobuf.Timestamp
	0, // 5: image.v1.ImageRuntimeService.ResolveImageForWorkload:input_type -> image.v1.ResolveImageForWorkloadRequest
	2, // 6: image.v1.ImageRuntimeService.GetTenantPullMaterial:input_type -> image.v1.GetTenantPullMaterialRequest
	1, // 7: image.v1.ImageRuntimeService.ResolveImageForWorkload:output_type -> image.v1.ResolveImageForWorkloadResponse
	3, // 8: image.v1.ImageRuntimeService.GetTenantPullMaterial:output_type -> image.v1.GetTenantPullMaterialResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_image_v1_runtime_proto_init() }
func file_image_v1_runtime_proto_init() {
	if File_image_v1_runtime_proto != nil {
		return
	}
	file_image_v1_image_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_image_v1_runtime_proto_rawDesc), len(file_image_v1_runtime_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_image_v1_runtime_proto_goTypes,
		DependencyIndexes: file_image_v1_runtime_proto_depIdxs,
		MessageInfos:      file_image_v1_runtime_proto_msgTypes,
	}.Build()
	File_image_v1_runtime_proto = out.File
	file_image_v1_runtime_proto_goTypes = nil
	file_image_v1_runtime_proto_depIdxs = nil
}
