// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: commands.sql

package sqlcgen

import (
	"context"
	"time"
)

const completePlatformCommand = `-- name: CompletePlatformCommand :one
UPDATE image.commands SET state='succeeded',phase='completed',result=$1,reason='',
 secret_replay_until=$2,completed_at=clock_timestamp(),updated_at=clock_timestamp(),version=version+1
WHERE owner_scope='platform' AND tenant_id IS NULL AND space_id=$3 AND command_id=$4
 AND version=$5 AND state IN ('pending','running','retryable','blocked')
RETURNING command_id, space_id, owner_scope, tenant_id, idempotency_key, kind, actor, fingerprint_version, fingerprint, state, phase, candidate, result, secret_ciphertext, secret_key_id, secret_replay_until, reason, version, created_at, updated_at, completed_at
`

type CompletePlatformCommandParams struct {
	Result            []byte
	SecretReplayUntil *time.Time
	SpaceID           string
	CommandID         string
	ExpectedVersion   int64
}

func (q *Queries) CompletePlatformCommand(ctx context.Context, arg CompletePlatformCommandParams) (ImageCommand, error) {
	row := q.db.QueryRow(ctx, completePlatformCommand,
		arg.Result,
		arg.SecretReplayUntil,
		arg.SpaceID,
		arg.CommandID,
		arg.ExpectedVersion,
	)
	var i ImageCommand
	err := row.Scan(
		&i.CommandID,
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Actor,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.State,
		&i.Phase,
		&i.Candidate,
		&i.Result,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.SecretReplayUntil,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const completeTenantCommand = `-- name: CompleteTenantCommand :one
UPDATE image.commands SET state='succeeded',phase='completed',result=$1,reason='',
 secret_replay_until=$2,completed_at=clock_timestamp(),updated_at=clock_timestamp(),version=version+1
WHERE owner_scope='tenant' AND tenant_id=$3 AND space_id=$4 AND command_id=$5
 AND version=$6 AND state IN ('pending','running','retryable','blocked')
RETURNING command_id, space_id, owner_scope, tenant_id, idempotency_key, kind, actor, fingerprint_version, fingerprint, state, phase, candidate, result, secret_ciphertext, secret_key_id, secret_replay_until, reason, version, created_at, updated_at, completed_at
`

type CompleteTenantCommandParams struct {
	Result            []byte
	SecretReplayUntil *time.Time
	TenantID          *string
	SpaceID           string
	CommandID         string
	ExpectedVersion   int64
}

func (q *Queries) CompleteTenantCommand(ctx context.Context, arg CompleteTenantCommandParams) (ImageCommand, error) {
	row := q.db.QueryRow(ctx, completeTenantCommand,
		arg.Result,
		arg.SecretReplayUntil,
		arg.TenantID,
		arg.SpaceID,
		arg.CommandID,
		arg.ExpectedVersion,
	)
	var i ImageCommand
	err := row.Scan(
		&i.CommandID,
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Actor,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.State,
		&i.Phase,
		&i.Candidate,
		&i.Result,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.SecretReplayUntil,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failPlatformCommand = `-- name: FailPlatformCommand :one
UPDATE image.commands SET state='failed',reason=$1,secret_ciphertext=NULL,secret_key_id=NULL,secret_replay_until=NULL,
 completed_at=clock_timestamp(),updated_at=clock_timestamp(),version=version+1
WHERE owner_scope='platform' AND tenant_id IS NULL AND space_id=$2 AND command_id=$3
 AND version=$4 AND state IN ('pending','running','retryable','blocked')
RETURNING command_id, space_id, owner_scope, tenant_id, idempotency_key, kind, actor, fingerprint_version, fingerprint, state, phase, candidate, result, secret_ciphertext, secret_key_id, secret_replay_until, reason, version, created_at, updated_at, completed_at
`

type FailPlatformCommandParams struct {
	Reason          string
	SpaceID         string
	CommandID       string
	ExpectedVersion int64
}

func (q *Queries) FailPlatformCommand(ctx context.Context, arg FailPlatformCommandParams) (ImageCommand, error) {
	row := q.db.QueryRow(ctx, failPlatformCommand,
		arg.Reason,
		arg.SpaceID,
		arg.CommandID,
		arg.ExpectedVersion,
	)
	var i ImageCommand
	err := row.Scan(
		&i.CommandID,
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Actor,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.State,
		&i.Phase,
		&i.Candidate,
		&i.Result,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.SecretReplayUntil,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const failTenantCommand = `-- name: FailTenantCommand :one
UPDATE image.commands SET state='failed',reason=$1,secret_ciphertext=NULL,secret_key_id=NULL,secret_replay_until=NULL,
 completed_at=clock_timestamp(),updated_at=clock_timestamp(),version=version+1
WHERE owner_scope='tenant' AND tenant_id=$2 AND space_id=$3 AND command_id=$4
 AND version=$5 AND state IN ('pending','running','retryable','blocked')
RETURNING command_id, space_id, owner_scope, tenant_id, idempotency_key, kind, actor, fingerprint_version, fingerprint, state, phase, candidate, result, secret_ciphertext, secret_key_id, secret_replay_until, reason, version, created_at, updated_at, completed_at
`

type FailTenantCommandParams struct {
	Reason          string
	TenantID        *string
	SpaceID         string
	CommandID       string
	ExpectedVersion int64
}

func (q *Queries) FailTenantCommand(ctx context.Context, arg FailTenantCommandParams) (ImageCommand, error) {
	row := q.db.QueryRow(ctx, failTenantCommand,
		arg.Reason,
		arg.TenantID,
		arg.SpaceID,
		arg.CommandID,
		arg.ExpectedVersion,
	)
	var i ImageCommand
	err := row.Scan(
		&i.CommandID,
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Actor,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.State,
		&i.Phase,
		&i.Candidate,
		&i.Result,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.SecretReplayUntil,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOpenPlatformExternalCommand = `-- name: GetOpenPlatformExternalCommand :one
SELECT command_id, space_id, owner_scope, tenant_id, idempotency_key, kind, actor, fingerprint_version, fingerprint, state, phase, candidate, result, secret_ciphertext, secret_key_id, secret_replay_until, reason, version, created_at, updated_at, completed_at FROM image.commands WHERE owner_scope='platform' AND tenant_id IS NULL AND space_id=$1
 AND kind IN ('enable_space','issue_publisher','reset_publisher','disable_publisher')
 AND state IN ('pending','running','retryable','blocked')
`

type GetOpenPlatformExternalCommandParams struct {
	SpaceID string
}

func (q *Queries) GetOpenPlatformExternalCommand(ctx context.Context, arg GetOpenPlatformExternalCommandParams) (ImageCommand, error) {
	row := q.db.QueryRow(ctx, getOpenPlatformExternalCommand, arg.SpaceID)
	var i ImageCommand
	err := row.Scan(
		&i.CommandID,
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Actor,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.State,
		&i.Phase,
		&i.Candidate,
		&i.Result,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.SecretReplayUntil,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getOpenTenantExternalCommand = `-- name: GetOpenTenantExternalCommand :one
SELECT command_id, space_id, owner_scope, tenant_id, idempotency_key, kind, actor, fingerprint_version, fingerprint, state, phase, candidate, result, secret_ciphertext, secret_key_id, secret_replay_until, reason, version, created_at, updated_at, completed_at FROM image.commands WHERE owner_scope='tenant' AND tenant_id=$1 AND space_id=$2
 AND kind IN ('enable_space','issue_publisher','reset_publisher','disable_publisher')
 AND state IN ('pending','running','retryable','blocked')
`

type GetOpenTenantExternalCommandParams struct {
	TenantID *string
	SpaceID  string
}

func (q *Queries) GetOpenTenantExternalCommand(ctx context.Context, arg GetOpenTenantExternalCommandParams) (ImageCommand, error) {
	row := q.db.QueryRow(ctx, getOpenTenantExternalCommand, arg.TenantID, arg.SpaceID)
	var i ImageCommand
	err := row.Scan(
		&i.CommandID,
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Actor,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.State,
		&i.Phase,
		&i.Candidate,
		&i.Result,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.SecretReplayUntil,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getPlatformCommand = `-- name: GetPlatformCommand :one
SELECT command_id, space_id, owner_scope, tenant_id, idempotency_key, kind, actor, fingerprint_version, fingerprint, state, phase, candidate, result, secret_ciphertext, secret_key_id, secret_replay_until, reason, version, created_at, updated_at, completed_at FROM image.commands WHERE owner_scope='platform' AND tenant_id IS NULL
 AND space_id=$1 AND idempotency_key=$2
`

type GetPlatformCommandParams struct {
	SpaceID        string
	IdempotencyKey string
}

func (q *Queries) GetPlatformCommand(ctx context.Context, arg GetPlatformCommandParams) (ImageCommand, error) {
	row := q.db.QueryRow(ctx, getPlatformCommand, arg.SpaceID, arg.IdempotencyKey)
	var i ImageCommand
	err := row.Scan(
		&i.CommandID,
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Actor,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.State,
		&i.Phase,
		&i.Candidate,
		&i.Result,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.SecretReplayUntil,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getTenantCommand = `-- name: GetTenantCommand :one
SELECT command_id, space_id, owner_scope, tenant_id, idempotency_key, kind, actor, fingerprint_version, fingerprint, state, phase, candidate, result, secret_ciphertext, secret_key_id, secret_replay_until, reason, version, created_at, updated_at, completed_at FROM image.commands WHERE owner_scope='tenant' AND tenant_id=$1
 AND space_id=$2 AND idempotency_key=$3
`

type GetTenantCommandParams struct {
	TenantID       *string
	SpaceID        string
	IdempotencyKey string
}

func (q *Queries) GetTenantCommand(ctx context.Context, arg GetTenantCommandParams) (ImageCommand, error) {
	row := q.db.QueryRow(ctx, getTenantCommand, arg.TenantID, arg.SpaceID, arg.IdempotencyKey)
	var i ImageCommand
	err := row.Scan(
		&i.CommandID,
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Actor,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.State,
		&i.Phase,
		&i.Candidate,
		&i.Result,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.SecretReplayUntil,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertPlatformCommand = `-- name: InsertPlatformCommand :one
INSERT INTO image.commands(command_id,space_id,owner_scope,tenant_id,idempotency_key,kind,actor,fingerprint,state)
VALUES($1,$2,'platform',NULL,$3,$4,$5,$6,'pending')
RETURNING command_id, space_id, owner_scope, tenant_id, idempotency_key, kind, actor, fingerprint_version, fingerprint, state, phase, candidate, result, secret_ciphertext, secret_key_id, secret_replay_until, reason, version, created_at, updated_at, completed_at
`

type InsertPlatformCommandParams struct {
	CommandID      string
	SpaceID        string
	IdempotencyKey string
	Kind           string
	Actor          string
	Fingerprint    string
}

func (q *Queries) InsertPlatformCommand(ctx context.Context, arg InsertPlatformCommandParams) (ImageCommand, error) {
	row := q.db.QueryRow(ctx, insertPlatformCommand,
		arg.CommandID,
		arg.SpaceID,
		arg.IdempotencyKey,
		arg.Kind,
		arg.Actor,
		arg.Fingerprint,
	)
	var i ImageCommand
	err := row.Scan(
		&i.CommandID,
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Actor,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.State,
		&i.Phase,
		&i.Candidate,
		&i.Result,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.SecretReplayUntil,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const insertTenantCommand = `-- name: InsertTenantCommand :one
INSERT INTO image.commands(command_id,space_id,owner_scope,tenant_id,idempotency_key,kind,actor,fingerprint,state)
VALUES($1,$2,'tenant',$3,$4,$5,$6,$7,'pending')
RETURNING command_id, space_id, owner_scope, tenant_id, idempotency_key, kind, actor, fingerprint_version, fingerprint, state, phase, candidate, result, secret_ciphertext, secret_key_id, secret_replay_until, reason, version, created_at, updated_at, completed_at
`

type InsertTenantCommandParams struct {
	CommandID      string
	SpaceID        string
	TenantID       *string
	IdempotencyKey string
	Kind           string
	Actor          string
	Fingerprint    string
}

func (q *Queries) InsertTenantCommand(ctx context.Context, arg InsertTenantCommandParams) (ImageCommand, error) {
	row := q.db.QueryRow(ctx, insertTenantCommand,
		arg.CommandID,
		arg.SpaceID,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.Kind,
		arg.Actor,
		arg.Fingerprint,
	)
	var i ImageCommand
	err := row.Scan(
		&i.CommandID,
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Actor,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.State,
		&i.Phase,
		&i.Candidate,
		&i.Result,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.SecretReplayUntil,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const scrubExpiredDeliverySecrets = `-- name: ScrubExpiredDeliverySecrets :execrows
UPDATE image.commands SET secret_ciphertext=NULL,secret_key_id=NULL,updated_at=clock_timestamp(),version=version+1
WHERE state='succeeded' AND secret_replay_until IS NOT NULL AND secret_replay_until<=$1
 AND secret_ciphertext IS NOT NULL
`

type ScrubExpiredDeliverySecretsParams struct {
	NowAt *time.Time
}

func (q *Queries) ScrubExpiredDeliverySecrets(ctx context.Context, arg ScrubExpiredDeliverySecretsParams) (int64, error) {
	result, err := q.db.Exec(ctx, scrubExpiredDeliverySecrets, arg.NowAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePlatformCommandPhase = `-- name: UpdatePlatformCommandPhase :one
UPDATE image.commands SET phase=$1,candidate=$2,state=$3,reason=$4,
 secret_ciphertext=$5,secret_key_id=$6,version=version+1,updated_at=clock_timestamp()
WHERE owner_scope='platform' AND tenant_id IS NULL AND space_id=$7 AND command_id=$8
 AND version=$9 AND state IN ('pending','running','retryable','blocked')
RETURNING command_id, space_id, owner_scope, tenant_id, idempotency_key, kind, actor, fingerprint_version, fingerprint, state, phase, candidate, result, secret_ciphertext, secret_key_id, secret_replay_until, reason, version, created_at, updated_at, completed_at
`

type UpdatePlatformCommandPhaseParams struct {
	Phase            string
	Candidate        []byte
	State            string
	Reason           string
	SecretCiphertext []byte
	SecretKeyID      *string
	SpaceID          string
	CommandID        string
	ExpectedVersion  int64
}

func (q *Queries) UpdatePlatformCommandPhase(ctx context.Context, arg UpdatePlatformCommandPhaseParams) (ImageCommand, error) {
	row := q.db.QueryRow(ctx, updatePlatformCommandPhase,
		arg.Phase,
		arg.Candidate,
		arg.State,
		arg.Reason,
		arg.SecretCiphertext,
		arg.SecretKeyID,
		arg.SpaceID,
		arg.CommandID,
		arg.ExpectedVersion,
	)
	var i ImageCommand
	err := row.Scan(
		&i.CommandID,
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Actor,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.State,
		&i.Phase,
		&i.Candidate,
		&i.Result,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.SecretReplayUntil,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateTenantCommandPhase = `-- name: UpdateTenantCommandPhase :one
UPDATE image.commands SET phase=$1,candidate=$2,state=$3,reason=$4,
 secret_ciphertext=$5,secret_key_id=$6,version=version+1,updated_at=clock_timestamp()
WHERE owner_scope='tenant' AND tenant_id=$7 AND space_id=$8 AND command_id=$9
 AND version=$10 AND state IN ('pending','running','retryable','blocked')
RETURNING command_id, space_id, owner_scope, tenant_id, idempotency_key, kind, actor, fingerprint_version, fingerprint, state, phase, candidate, result, secret_ciphertext, secret_key_id, secret_replay_until, reason, version, created_at, updated_at, completed_at
`

type UpdateTenantCommandPhaseParams struct {
	Phase            string
	Candidate        []byte
	State            string
	Reason           string
	SecretCiphertext []byte
	SecretKeyID      *string
	TenantID         *string
	SpaceID          string
	CommandID        string
	ExpectedVersion  int64
}

func (q *Queries) UpdateTenantCommandPhase(ctx context.Context, arg UpdateTenantCommandPhaseParams) (ImageCommand, error) {
	row := q.db.QueryRow(ctx, updateTenantCommandPhase,
		arg.Phase,
		arg.Candidate,
		arg.State,
		arg.Reason,
		arg.SecretCiphertext,
		arg.SecretKeyID,
		arg.TenantID,
		arg.SpaceID,
		arg.CommandID,
		arg.ExpectedVersion,
	)
	var i ImageCommand
	err := row.Scan(
		&i.CommandID,
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Kind,
		&i.Actor,
		&i.FingerprintVersion,
		&i.Fingerprint,
		&i.State,
		&i.Phase,
		&i.Candidate,
		&i.Result,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.SecretReplayUntil,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
