// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: credentials.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const activatePlatformCredential = `-- name: ActivatePlatformCredential :one
UPDATE image.credentials SET state='active',generation=$1,version=version+1,
 robot_id=$2,robot_name=$3,username=$4,
 expires_at=$5,never_expires=$6,updated_at=clock_timestamp()
WHERE owner_scope='platform' AND tenant_id IS NULL AND space_id=$7 AND purpose='publisher'
 AND version=$8 AND generation<$1
RETURNING space_id, owner_scope, tenant_id, purpose, state, generation, version, robot_id, robot_name, username, expires_at, never_expires, secret_ciphertext, secret_key_id, created_at, updated_at
`

type ActivatePlatformCredentialParams struct {
	Generation      int64
	RobotID         pgtype.Int8
	RobotName       *string
	Username        *string
	ExpiresAt       *time.Time
	NeverExpires    bool
	SpaceID         string
	ExpectedVersion int64
}

func (q *Queries) ActivatePlatformCredential(ctx context.Context, arg ActivatePlatformCredentialParams) (ImageCredential, error) {
	row := q.db.QueryRow(ctx, activatePlatformCredential,
		arg.Generation,
		arg.RobotID,
		arg.RobotName,
		arg.Username,
		arg.ExpiresAt,
		arg.NeverExpires,
		arg.SpaceID,
		arg.ExpectedVersion,
	)
	var i ImageCredential
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.Purpose,
		&i.State,
		&i.Generation,
		&i.Version,
		&i.RobotID,
		&i.RobotName,
		&i.Username,
		&i.ExpiresAt,
		&i.NeverExpires,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const activateTenantCredential = `-- name: ActivateTenantCredential :one
UPDATE image.credentials SET state='active',generation=$1,version=version+1,
 robot_id=$2,robot_name=$3,username=$4,
 expires_at=$5,never_expires=$6,
 secret_ciphertext=$7,secret_key_id=$8,updated_at=clock_timestamp()
WHERE owner_scope='tenant' AND tenant_id=$9 AND space_id=$10 AND purpose=$11
 AND version=$12 AND generation<$1
RETURNING space_id, owner_scope, tenant_id, purpose, state, generation, version, robot_id, robot_name, username, expires_at, never_expires, secret_ciphertext, secret_key_id, created_at, updated_at
`

type ActivateTenantCredentialParams struct {
	Generation       int64
	RobotID          pgtype.Int8
	RobotName        *string
	Username         *string
	ExpiresAt        *time.Time
	NeverExpires     bool
	SecretCiphertext []byte
	SecretKeyID      *string
	TenantID         *string
	SpaceID          string
	Purpose          string
	ExpectedVersion  int64
}

func (q *Queries) ActivateTenantCredential(ctx context.Context, arg ActivateTenantCredentialParams) (ImageCredential, error) {
	row := q.db.QueryRow(ctx, activateTenantCredential,
		arg.Generation,
		arg.RobotID,
		arg.RobotName,
		arg.Username,
		arg.ExpiresAt,
		arg.NeverExpires,
		arg.SecretCiphertext,
		arg.SecretKeyID,
		arg.TenantID,
		arg.SpaceID,
		arg.Purpose,
		arg.ExpectedVersion,
	)
	var i ImageCredential
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.Purpose,
		&i.State,
		&i.Generation,
		&i.Version,
		&i.RobotID,
		&i.RobotName,
		&i.Username,
		&i.ExpiresAt,
		&i.NeverExpires,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disablePlatformCredential = `-- name: DisablePlatformCredential :one
UPDATE image.credentials SET state='disabled',version=version+1,updated_at=clock_timestamp()
WHERE owner_scope='platform' AND tenant_id IS NULL AND space_id=$1 AND purpose='publisher'
 AND version=$2 AND generation=$3
RETURNING space_id, owner_scope, tenant_id, purpose, state, generation, version, robot_id, robot_name, username, expires_at, never_expires, secret_ciphertext, secret_key_id, created_at, updated_at
`

type DisablePlatformCredentialParams struct {
	SpaceID         string
	ExpectedVersion int64
	Generation      int64
}

func (q *Queries) DisablePlatformCredential(ctx context.Context, arg DisablePlatformCredentialParams) (ImageCredential, error) {
	row := q.db.QueryRow(ctx, disablePlatformCredential, arg.SpaceID, arg.ExpectedVersion, arg.Generation)
	var i ImageCredential
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.Purpose,
		&i.State,
		&i.Generation,
		&i.Version,
		&i.RobotID,
		&i.RobotName,
		&i.Username,
		&i.ExpiresAt,
		&i.NeverExpires,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const disableTenantCredential = `-- name: DisableTenantCredential :one
UPDATE image.credentials SET state='disabled',secret_ciphertext=NULL,secret_key_id=NULL,version=version+1,updated_at=clock_timestamp()
WHERE owner_scope='tenant' AND tenant_id=$1 AND space_id=$2 AND purpose=$3
 AND version=$4 AND generation=$5
RETURNING space_id, owner_scope, tenant_id, purpose, state, generation, version, robot_id, robot_name, username, expires_at, never_expires, secret_ciphertext, secret_key_id, created_at, updated_at
`

type DisableTenantCredentialParams struct {
	TenantID        *string
	SpaceID         string
	Purpose         string
	ExpectedVersion int64
	Generation      int64
}

func (q *Queries) DisableTenantCredential(ctx context.Context, arg DisableTenantCredentialParams) (ImageCredential, error) {
	row := q.db.QueryRow(ctx, disableTenantCredential,
		arg.TenantID,
		arg.SpaceID,
		arg.Purpose,
		arg.ExpectedVersion,
		arg.Generation,
	)
	var i ImageCredential
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.Purpose,
		&i.State,
		&i.Generation,
		&i.Version,
		&i.RobotID,
		&i.RobotName,
		&i.Username,
		&i.ExpiresAt,
		&i.NeverExpires,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformPublisherCredential = `-- name: GetPlatformPublisherCredential :one
SELECT space_id, owner_scope, tenant_id, purpose, state, generation, version, robot_id, robot_name, username, expires_at, never_expires, secret_ciphertext, secret_key_id, created_at, updated_at FROM image.credentials WHERE owner_scope='platform' AND tenant_id IS NULL
 AND space_id=$1 AND purpose='publisher'
`

type GetPlatformPublisherCredentialParams struct {
	SpaceID string
}

func (q *Queries) GetPlatformPublisherCredential(ctx context.Context, arg GetPlatformPublisherCredentialParams) (ImageCredential, error) {
	row := q.db.QueryRow(ctx, getPlatformPublisherCredential, arg.SpaceID)
	var i ImageCredential
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.Purpose,
		&i.State,
		&i.Generation,
		&i.Version,
		&i.RobotID,
		&i.RobotName,
		&i.Username,
		&i.ExpiresAt,
		&i.NeverExpires,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantPublisherCredential = `-- name: GetTenantPublisherCredential :one
SELECT space_id, owner_scope, tenant_id, purpose, state, generation, version, robot_id, robot_name, username, expires_at, never_expires, secret_ciphertext, secret_key_id, created_at, updated_at FROM image.credentials WHERE owner_scope='tenant' AND tenant_id=$1
 AND space_id=$2 AND purpose='publisher'
`

type GetTenantPublisherCredentialParams struct {
	TenantID *string
	SpaceID  string
}

func (q *Queries) GetTenantPublisherCredential(ctx context.Context, arg GetTenantPublisherCredentialParams) (ImageCredential, error) {
	row := q.db.QueryRow(ctx, getTenantPublisherCredential, arg.TenantID, arg.SpaceID)
	var i ImageCredential
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.Purpose,
		&i.State,
		&i.Generation,
		&i.Version,
		&i.RobotID,
		&i.RobotName,
		&i.Username,
		&i.ExpiresAt,
		&i.NeverExpires,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantPullCredential = `-- name: GetTenantPullCredential :one
SELECT space_id, owner_scope, tenant_id, purpose, state, generation, version, robot_id, robot_name, username, expires_at, never_expires, secret_ciphertext, secret_key_id, created_at, updated_at FROM image.credentials WHERE owner_scope='tenant' AND tenant_id=$1
 AND space_id=$2 AND purpose='pull'
`

type GetTenantPullCredentialParams struct {
	TenantID *string
	SpaceID  string
}

func (q *Queries) GetTenantPullCredential(ctx context.Context, arg GetTenantPullCredentialParams) (ImageCredential, error) {
	row := q.db.QueryRow(ctx, getTenantPullCredential, arg.TenantID, arg.SpaceID)
	var i ImageCredential
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.Purpose,
		&i.State,
		&i.Generation,
		&i.Version,
		&i.RobotID,
		&i.RobotName,
		&i.Username,
		&i.ExpiresAt,
		&i.NeverExpires,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const putPlatformCandidateState = `-- name: PutPlatformCandidateState :one
INSERT INTO image.credentials(space_id,owner_scope,tenant_id,purpose,state)
VALUES($1,'platform',NULL,'publisher','issuing')
ON CONFLICT(space_id,purpose) DO UPDATE SET state='issuing',updated_at=clock_timestamp()
WHERE image.credentials.owner_scope='platform' AND image.credentials.tenant_id IS NULL
 AND image.credentials.generation=0 AND image.credentials.state='issuing'
RETURNING space_id, owner_scope, tenant_id, purpose, state, generation, version, robot_id, robot_name, username, expires_at, never_expires, secret_ciphertext, secret_key_id, created_at, updated_at
`

type PutPlatformCandidateStateParams struct {
	SpaceID string
}

func (q *Queries) PutPlatformCandidateState(ctx context.Context, arg PutPlatformCandidateStateParams) (ImageCredential, error) {
	row := q.db.QueryRow(ctx, putPlatformCandidateState, arg.SpaceID)
	var i ImageCredential
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.Purpose,
		&i.State,
		&i.Generation,
		&i.Version,
		&i.RobotID,
		&i.RobotName,
		&i.Username,
		&i.ExpiresAt,
		&i.NeverExpires,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const putTenantCandidateState = `-- name: PutTenantCandidateState :one
INSERT INTO image.credentials(space_id,owner_scope,tenant_id,purpose,state)
VALUES($1,'tenant',$2,$3,'issuing')
ON CONFLICT(space_id,purpose) DO UPDATE SET state='issuing',updated_at=clock_timestamp()
WHERE image.credentials.owner_scope='tenant' AND image.credentials.tenant_id=$2
 AND image.credentials.generation=0 AND image.credentials.state='issuing'
RETURNING space_id, owner_scope, tenant_id, purpose, state, generation, version, robot_id, robot_name, username, expires_at, never_expires, secret_ciphertext, secret_key_id, created_at, updated_at
`

type PutTenantCandidateStateParams struct {
	SpaceID  string
	TenantID *string
	Purpose  string
}

func (q *Queries) PutTenantCandidateState(ctx context.Context, arg PutTenantCandidateStateParams) (ImageCredential, error) {
	row := q.db.QueryRow(ctx, putTenantCandidateState, arg.SpaceID, arg.TenantID, arg.Purpose)
	var i ImageCredential
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.Purpose,
		&i.State,
		&i.Generation,
		&i.Version,
		&i.RobotID,
		&i.RobotName,
		&i.Username,
		&i.ExpiresAt,
		&i.NeverExpires,
		&i.SecretCiphertext,
		&i.SecretKeyID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
