// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ImageCommand struct {
	CommandID          string
	SpaceID            string
	OwnerScope         string
	TenantID           *string
	IdempotencyKey     string
	Kind               string
	Actor              string
	FingerprintVersion int32
	Fingerprint        string
	State              string
	Phase              string
	Candidate          []byte
	Result             []byte
	SecretCiphertext   []byte
	SecretKeyID        *string
	SecretReplayUntil  *time.Time
	Reason             string
	Version            int64
	CreatedAt          time.Time
	UpdatedAt          time.Time
	CompletedAt        *time.Time
}

type ImageCredential struct {
	SpaceID          string
	OwnerScope       string
	TenantID         *string
	Purpose          string
	State            string
	Generation       int64
	Version          int64
	RobotID          pgtype.Int8
	RobotName        *string
	Username         *string
	ExpiresAt        *time.Time
	NeverExpires     bool
	SecretCiphertext []byte
	SecretKeyID      *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type ImageRegistration struct {
	ImageID         string
	SpaceID         string
	OwnerScope      string
	TenantID        *string
	DisplayName     string
	Description     string
	Repository      string
	SourceReference string
	Digest          string
	MediaType       string
	Platforms       []byte
	Purposes        []string
	Accelerator     string
	Version         int64
	CreatedBy       string
	UpdatedBy       string
	CreatedAt       time.Time
	UpdatedAt       time.Time
	UnregisteredAt  *time.Time
}

type ImageSchemaVersion struct {
	Version   int32
	Checksum  string
	AppliedAt time.Time
}

type ImageSpace struct {
	SpaceID           string
	OwnerScope        string
	TenantID          *string
	InstallationID    string
	RegistryAuthority string
	ProjectName       string
	HarborProjectID   pgtype.Int8
	State             string
	Reason            string
	Version           int64
	CreatedAt         time.Time
	UpdatedAt         time.Time
}
