// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spaces.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindPlatformProject = `-- name: BindPlatformProject :one
UPDATE image.spaces SET harbor_project_id=$1,version=version+1,updated_at=clock_timestamp()
WHERE owner_scope='platform' AND tenant_id IS NULL AND space_id=$2
 AND version=$3 AND (harbor_project_id IS NULL OR harbor_project_id=$1)
RETURNING space_id, owner_scope, tenant_id, installation_id, registry_authority, project_name, harbor_project_id, state, reason, version, created_at, updated_at
`

type BindPlatformProjectParams struct {
	ProjectID       pgtype.Int8
	SpaceID         string
	ExpectedVersion int64
}

func (q *Queries) BindPlatformProject(ctx context.Context, arg BindPlatformProjectParams) (ImageSpace, error) {
	row := q.db.QueryRow(ctx, bindPlatformProject, arg.ProjectID, arg.SpaceID, arg.ExpectedVersion)
	var i ImageSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.InstallationID,
		&i.RegistryAuthority,
		&i.ProjectName,
		&i.HarborProjectID,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const bindTenantProject = `-- name: BindTenantProject :one
UPDATE image.spaces SET harbor_project_id=$1,version=version+1,updated_at=clock_timestamp()
WHERE owner_scope='tenant' AND tenant_id=$2 AND space_id=$3
 AND version=$4 AND (harbor_project_id IS NULL OR harbor_project_id=$1)
RETURNING space_id, owner_scope, tenant_id, installation_id, registry_authority, project_name, harbor_project_id, state, reason, version, created_at, updated_at
`

type BindTenantProjectParams struct {
	ProjectID       pgtype.Int8
	TenantID        *string
	SpaceID         string
	ExpectedVersion int64
}

func (q *Queries) BindTenantProject(ctx context.Context, arg BindTenantProjectParams) (ImageSpace, error) {
	row := q.db.QueryRow(ctx, bindTenantProject,
		arg.ProjectID,
		arg.TenantID,
		arg.SpaceID,
		arg.ExpectedVersion,
	)
	var i ImageSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.InstallationID,
		&i.RegistryAuthority,
		&i.ProjectName,
		&i.HarborProjectID,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPlatformSpace = `-- name: GetPlatformSpace :one
SELECT space_id, owner_scope, tenant_id, installation_id, registry_authority, project_name, harbor_project_id, state, reason, version, created_at, updated_at FROM image.spaces WHERE owner_scope='platform' AND tenant_id IS NULL
`

func (q *Queries) GetPlatformSpace(ctx context.Context) (ImageSpace, error) {
	row := q.db.QueryRow(ctx, getPlatformSpace)
	var i ImageSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.InstallationID,
		&i.RegistryAuthority,
		&i.ProjectName,
		&i.HarborProjectID,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantSpace = `-- name: GetTenantSpace :one
SELECT space_id, owner_scope, tenant_id, installation_id, registry_authority, project_name, harbor_project_id, state, reason, version, created_at, updated_at FROM image.spaces WHERE owner_scope='tenant' AND tenant_id=$1
`

type GetTenantSpaceParams struct {
	TenantID *string
}

func (q *Queries) GetTenantSpace(ctx context.Context, arg GetTenantSpaceParams) (ImageSpace, error) {
	row := q.db.QueryRow(ctx, getTenantSpace, arg.TenantID)
	var i ImageSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.InstallationID,
		&i.RegistryAuthority,
		&i.ProjectName,
		&i.HarborProjectID,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const inspectSpaceForOperator = `-- name: InspectSpaceForOperator :one
SELECT space_id, owner_scope, tenant_id, installation_id, registry_authority, project_name, harbor_project_id, state, reason, version, created_at, updated_at FROM image.spaces WHERE space_id=$1
`

type InspectSpaceForOperatorParams struct {
	SpaceID string
}

// Local operator mode only; never used by tenant RPC paths.
func (q *Queries) InspectSpaceForOperator(ctx context.Context, arg InspectSpaceForOperatorParams) (ImageSpace, error) {
	row := q.db.QueryRow(ctx, inspectSpaceForOperator, arg.SpaceID)
	var i ImageSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.InstallationID,
		&i.RegistryAuthority,
		&i.ProjectName,
		&i.HarborProjectID,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockPlatformSpace = `-- name: LockPlatformSpace :exec
SELECT pg_advisory_xact_lock(hashtextextended('image.platform', 0))
`

func (q *Queries) LockPlatformSpace(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockPlatformSpace)
	return err
}

const lockTenantSpace = `-- name: LockTenantSpace :exec
SELECT pg_advisory_xact_lock(hashtextextended('image.tenant:' || $1::text, 0))
`

type LockTenantSpaceParams struct {
	TenantID string
}

func (q *Queries) LockTenantSpace(ctx context.Context, arg LockTenantSpaceParams) error {
	_, err := q.db.Exec(ctx, lockTenantSpace, arg.TenantID)
	return err
}

const reservePlatformSpace = `-- name: ReservePlatformSpace :one
INSERT INTO image.spaces(space_id,owner_scope,tenant_id,installation_id,registry_authority,project_name)
VALUES($1,'platform',NULL,$2,$3,$4)
RETURNING space_id, owner_scope, tenant_id, installation_id, registry_authority, project_name, harbor_project_id, state, reason, version, created_at, updated_at
`

type ReservePlatformSpaceParams struct {
	SpaceID           string
	InstallationID    string
	RegistryAuthority string
	ProjectName       string
}

func (q *Queries) ReservePlatformSpace(ctx context.Context, arg ReservePlatformSpaceParams) (ImageSpace, error) {
	row := q.db.QueryRow(ctx, reservePlatformSpace,
		arg.SpaceID,
		arg.InstallationID,
		arg.RegistryAuthority,
		arg.ProjectName,
	)
	var i ImageSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.InstallationID,
		&i.RegistryAuthority,
		&i.ProjectName,
		&i.HarborProjectID,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const reserveTenantSpace = `-- name: ReserveTenantSpace :one
INSERT INTO image.spaces(space_id,owner_scope,tenant_id,installation_id,registry_authority,project_name)
VALUES($1,'tenant',$2,$3,$4,$5)
RETURNING space_id, owner_scope, tenant_id, installation_id, registry_authority, project_name, harbor_project_id, state, reason, version, created_at, updated_at
`

type ReserveTenantSpaceParams struct {
	SpaceID           string
	TenantID          *string
	InstallationID    string
	RegistryAuthority string
	ProjectName       string
}

func (q *Queries) ReserveTenantSpace(ctx context.Context, arg ReserveTenantSpaceParams) (ImageSpace, error) {
	row := q.db.QueryRow(ctx, reserveTenantSpace,
		arg.SpaceID,
		arg.TenantID,
		arg.InstallationID,
		arg.RegistryAuthority,
		arg.ProjectName,
	)
	var i ImageSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.InstallationID,
		&i.RegistryAuthority,
		&i.ProjectName,
		&i.HarborProjectID,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPlatformSpaceAvailable = `-- name: SetPlatformSpaceAvailable :one
UPDATE image.spaces SET state='available',reason='',version=version+1,updated_at=clock_timestamp()
WHERE owner_scope='platform' AND tenant_id IS NULL AND space_id=$1
 AND version=$2 AND harbor_project_id IS NOT NULL
RETURNING space_id, owner_scope, tenant_id, installation_id, registry_authority, project_name, harbor_project_id, state, reason, version, created_at, updated_at
`

type SetPlatformSpaceAvailableParams struct {
	SpaceID         string
	ExpectedVersion int64
}

func (q *Queries) SetPlatformSpaceAvailable(ctx context.Context, arg SetPlatformSpaceAvailableParams) (ImageSpace, error) {
	row := q.db.QueryRow(ctx, setPlatformSpaceAvailable, arg.SpaceID, arg.ExpectedVersion)
	var i ImageSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.InstallationID,
		&i.RegistryAuthority,
		&i.ProjectName,
		&i.HarborProjectID,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setPlatformSpaceReason = `-- name: SetPlatformSpaceReason :one
UPDATE image.spaces SET state=$1,reason=$2,version=version+1,updated_at=clock_timestamp()
WHERE owner_scope='platform' AND tenant_id IS NULL AND space_id=$3 AND version=$4
RETURNING space_id, owner_scope, tenant_id, installation_id, registry_authority, project_name, harbor_project_id, state, reason, version, created_at, updated_at
`

type SetPlatformSpaceReasonParams struct {
	State           string
	Reason          string
	SpaceID         string
	ExpectedVersion int64
}

func (q *Queries) SetPlatformSpaceReason(ctx context.Context, arg SetPlatformSpaceReasonParams) (ImageSpace, error) {
	row := q.db.QueryRow(ctx, setPlatformSpaceReason,
		arg.State,
		arg.Reason,
		arg.SpaceID,
		arg.ExpectedVersion,
	)
	var i ImageSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.InstallationID,
		&i.RegistryAuthority,
		&i.ProjectName,
		&i.HarborProjectID,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTenantSpaceAvailable = `-- name: SetTenantSpaceAvailable :one
UPDATE image.spaces s SET state='available',reason='',version=s.version+1,updated_at=clock_timestamp()
WHERE s.owner_scope='tenant' AND s.tenant_id=$1 AND s.space_id=$2
 AND s.version=$3 AND s.harbor_project_id IS NOT NULL
 AND EXISTS (SELECT 1 FROM image.credentials c WHERE c.owner_scope='tenant' AND c.tenant_id=$1
  AND c.space_id=s.space_id AND c.purpose='pull' AND c.state='active' AND (c.never_expires OR c.expires_at>clock_timestamp()))
RETURNING s.space_id, s.owner_scope, s.tenant_id, s.installation_id, s.registry_authority, s.project_name, s.harbor_project_id, s.state, s.reason, s.version, s.created_at, s.updated_at
`

type SetTenantSpaceAvailableParams struct {
	TenantID        *string
	SpaceID         string
	ExpectedVersion int64
}

func (q *Queries) SetTenantSpaceAvailable(ctx context.Context, arg SetTenantSpaceAvailableParams) (ImageSpace, error) {
	row := q.db.QueryRow(ctx, setTenantSpaceAvailable, arg.TenantID, arg.SpaceID, arg.ExpectedVersion)
	var i ImageSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.InstallationID,
		&i.RegistryAuthority,
		&i.ProjectName,
		&i.HarborProjectID,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const setTenantSpaceReason = `-- name: SetTenantSpaceReason :one
UPDATE image.spaces SET state=$1,reason=$2,version=version+1,updated_at=clock_timestamp()
WHERE owner_scope='tenant' AND tenant_id=$3 AND space_id=$4 AND version=$5
RETURNING space_id, owner_scope, tenant_id, installation_id, registry_authority, project_name, harbor_project_id, state, reason, version, created_at, updated_at
`

type SetTenantSpaceReasonParams struct {
	State           string
	Reason          string
	TenantID        *string
	SpaceID         string
	ExpectedVersion int64
}

func (q *Queries) SetTenantSpaceReason(ctx context.Context, arg SetTenantSpaceReasonParams) (ImageSpace, error) {
	row := q.db.QueryRow(ctx, setTenantSpaceReason,
		arg.State,
		arg.Reason,
		arg.TenantID,
		arg.SpaceID,
		arg.ExpectedVersion,
	)
	var i ImageSpace
	err := row.Scan(
		&i.SpaceID,
		&i.OwnerScope,
		&i.TenantID,
		&i.InstallationID,
		&i.RegistryAuthority,
		&i.ProjectName,
		&i.HarborProjectID,
		&i.State,
		&i.Reason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
