// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: network/v1/load_balancer.proto

package networkv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	fieldmaskpb "google.golang.org/protobuf/types/known/fieldmaskpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LoadBalancerExposure int32

const (
	LoadBalancerExposure_LOAD_BALANCER_EXPOSURE_UNSPECIFIED    LoadBalancerExposure = 0
	LoadBalancerExposure_LOAD_BALANCER_EXPOSURE_PRIVATE        LoadBalancerExposure = 1
	LoadBalancerExposure_LOAD_BALANCER_EXPOSURE_PUBLIC         LoadBalancerExposure = 2
	LoadBalancerExposure_LOAD_BALANCER_EXPOSURE_PUBLIC_PRIVATE LoadBalancerExposure = 3
)

// Enum value maps for LoadBalancerExposure.
var (
	LoadBalancerExposure_name = map[int32]string{
		0: "LOAD_BALANCER_EXPOSURE_UNSPECIFIED",
		1: "LOAD_BALANCER_EXPOSURE_PRIVATE",
		2: "LOAD_BALANCER_EXPOSURE_PUBLIC",
		3: "LOAD_BALANCER_EXPOSURE_PUBLIC_PRIVATE",
	}
	LoadBalancerExposure_value = map[string]int32{
		"LOAD_BALANCER_EXPOSURE_UNSPECIFIED":    0,
		"LOAD_BALANCER_EXPOSURE_PRIVATE":        1,
		"LOAD_BALANCER_EXPOSURE_PUBLIC":         2,
		"LOAD_BALANCER_EXPOSURE_PUBLIC_PRIVATE": 3,
	}
)

func (x LoadBalancerExposure) Enum() *LoadBalancerExposure {
	p := new(LoadBalancerExposure)
	*p = x
	return p
}

func (x LoadBalancerExposure) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadBalancerExposure) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_load_balancer_proto_enumTypes[0].Descriptor()
}

func (LoadBalancerExposure) Type() protoreflect.EnumType {
	return &file_network_v1_load_balancer_proto_enumTypes[0]
}

func (x LoadBalancerExposure) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadBalancerExposure.Descriptor instead.
func (LoadBalancerExposure) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{0}
}

type LoadBalancerListenerProtocol int32

const (
	LoadBalancerListenerProtocol_LOAD_BALANCER_LISTENER_PROTOCOL_UNSPECIFIED LoadBalancerListenerProtocol = 0
	LoadBalancerListenerProtocol_LOAD_BALANCER_LISTENER_PROTOCOL_HTTP        LoadBalancerListenerProtocol = 1
)

// Enum value maps for LoadBalancerListenerProtocol.
var (
	LoadBalancerListenerProtocol_name = map[int32]string{
		0: "LOAD_BALANCER_LISTENER_PROTOCOL_UNSPECIFIED",
		1: "LOAD_BALANCER_LISTENER_PROTOCOL_HTTP",
	}
	LoadBalancerListenerProtocol_value = map[string]int32{
		"LOAD_BALANCER_LISTENER_PROTOCOL_UNSPECIFIED": 0,
		"LOAD_BALANCER_LISTENER_PROTOCOL_HTTP":        1,
	}
)

func (x LoadBalancerListenerProtocol) Enum() *LoadBalancerListenerProtocol {
	p := new(LoadBalancerListenerProtocol)
	*p = x
	return p
}

func (x LoadBalancerListenerProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadBalancerListenerProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_load_balancer_proto_enumTypes[1].Descriptor()
}

func (LoadBalancerListenerProtocol) Type() protoreflect.EnumType {
	return &file_network_v1_load_balancer_proto_enumTypes[1]
}

func (x LoadBalancerListenerProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadBalancerListenerProtocol.Descriptor instead.
func (LoadBalancerListenerProtocol) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{1}
}

type LoadBalancerAlgorithm int32

const (
	LoadBalancerAlgorithm_LOAD_BALANCER_ALGORITHM_UNSPECIFIED LoadBalancerAlgorithm = 0
	LoadBalancerAlgorithm_LOAD_BALANCER_ALGORITHM_ROUND_ROBIN LoadBalancerAlgorithm = 1
)

// Enum value maps for LoadBalancerAlgorithm.
var (
	LoadBalancerAlgorithm_name = map[int32]string{
		0: "LOAD_BALANCER_ALGORITHM_UNSPECIFIED",
		1: "LOAD_BALANCER_ALGORITHM_ROUND_ROBIN",
	}
	LoadBalancerAlgorithm_value = map[string]int32{
		"LOAD_BALANCER_ALGORITHM_UNSPECIFIED": 0,
		"LOAD_BALANCER_ALGORITHM_ROUND_ROBIN": 1,
	}
)

func (x LoadBalancerAlgorithm) Enum() *LoadBalancerAlgorithm {
	p := new(LoadBalancerAlgorithm)
	*p = x
	return p
}

func (x LoadBalancerAlgorithm) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadBalancerAlgorithm) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_load_balancer_proto_enumTypes[2].Descriptor()
}

func (LoadBalancerAlgorithm) Type() protoreflect.EnumType {
	return &file_network_v1_load_balancer_proto_enumTypes[2]
}

func (x LoadBalancerAlgorithm) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadBalancerAlgorithm.Descriptor instead.
func (LoadBalancerAlgorithm) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{2}
}

type LoadBalancerHealthCheckProtocol int32

const (
	LoadBalancerHealthCheckProtocol_LOAD_BALANCER_HEALTH_CHECK_PROTOCOL_UNSPECIFIED LoadBalancerHealthCheckProtocol = 0
	LoadBalancerHealthCheckProtocol_LOAD_BALANCER_HEALTH_CHECK_PROTOCOL_TCP         LoadBalancerHealthCheckProtocol = 1
)

// Enum value maps for LoadBalancerHealthCheckProtocol.
var (
	LoadBalancerHealthCheckProtocol_name = map[int32]string{
		0: "LOAD_BALANCER_HEALTH_CHECK_PROTOCOL_UNSPECIFIED",
		1: "LOAD_BALANCER_HEALTH_CHECK_PROTOCOL_TCP",
	}
	LoadBalancerHealthCheckProtocol_value = map[string]int32{
		"LOAD_BALANCER_HEALTH_CHECK_PROTOCOL_UNSPECIFIED": 0,
		"LOAD_BALANCER_HEALTH_CHECK_PROTOCOL_TCP":         1,
	}
)

func (x LoadBalancerHealthCheckProtocol) Enum() *LoadBalancerHealthCheckProtocol {
	p := new(LoadBalancerHealthCheckProtocol)
	*p = x
	return p
}

func (x LoadBalancerHealthCheckProtocol) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadBalancerHealthCheckProtocol) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_load_balancer_proto_enumTypes[3].Descriptor()
}

func (LoadBalancerHealthCheckProtocol) Type() protoreflect.EnumType {
	return &file_network_v1_load_balancer_proto_enumTypes[3]
}

func (x LoadBalancerHealthCheckProtocol) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadBalancerHealthCheckProtocol.Descriptor instead.
func (LoadBalancerHealthCheckProtocol) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{3}
}

// Configuration completion and observed traffic health are independent of the
// resource lifecycle and operation history. UNSPECIFIED is never a ready result.
type LoadBalancerConfigurationState int32

const (
	LoadBalancerConfigurationState_LOAD_BALANCER_CONFIGURATION_STATE_UNSPECIFIED LoadBalancerConfigurationState = 0
	LoadBalancerConfigurationState_LOAD_BALANCER_CONFIGURATION_STATE_PENDING     LoadBalancerConfigurationState = 1
	LoadBalancerConfigurationState_LOAD_BALANCER_CONFIGURATION_STATE_APPLYING    LoadBalancerConfigurationState = 2
	LoadBalancerConfigurationState_LOAD_BALANCER_CONFIGURATION_STATE_CONFIGURED  LoadBalancerConfigurationState = 3
	LoadBalancerConfigurationState_LOAD_BALANCER_CONFIGURATION_STATE_DEGRADED    LoadBalancerConfigurationState = 4
	LoadBalancerConfigurationState_LOAD_BALANCER_CONFIGURATION_STATE_UNKNOWN     LoadBalancerConfigurationState = 5
)

// Enum value maps for LoadBalancerConfigurationState.
var (
	LoadBalancerConfigurationState_name = map[int32]string{
		0: "LOAD_BALANCER_CONFIGURATION_STATE_UNSPECIFIED",
		1: "LOAD_BALANCER_CONFIGURATION_STATE_PENDING",
		2: "LOAD_BALANCER_CONFIGURATION_STATE_APPLYING",
		3: "LOAD_BALANCER_CONFIGURATION_STATE_CONFIGURED",
		4: "LOAD_BALANCER_CONFIGURATION_STATE_DEGRADED",
		5: "LOAD_BALANCER_CONFIGURATION_STATE_UNKNOWN",
	}
	LoadBalancerConfigurationState_value = map[string]int32{
		"LOAD_BALANCER_CONFIGURATION_STATE_UNSPECIFIED": 0,
		"LOAD_BALANCER_CONFIGURATION_STATE_PENDING":     1,
		"LOAD_BALANCER_CONFIGURATION_STATE_APPLYING":    2,
		"LOAD_BALANCER_CONFIGURATION_STATE_CONFIGURED":  3,
		"LOAD_BALANCER_CONFIGURATION_STATE_DEGRADED":    4,
		"LOAD_BALANCER_CONFIGURATION_STATE_UNKNOWN":     5,
	}
)

func (x LoadBalancerConfigurationState) Enum() *LoadBalancerConfigurationState {
	p := new(LoadBalancerConfigurationState)
	*p = x
	return p
}

func (x LoadBalancerConfigurationState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadBalancerConfigurationState) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_load_balancer_proto_enumTypes[4].Descriptor()
}

func (LoadBalancerConfigurationState) Type() protoreflect.EnumType {
	return &file_network_v1_load_balancer_proto_enumTypes[4]
}

func (x LoadBalancerConfigurationState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadBalancerConfigurationState.Descriptor instead.
func (LoadBalancerConfigurationState) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{4}
}

type LoadBalancerDataPlaneState int32

const (
	LoadBalancerDataPlaneState_LOAD_BALANCER_DATA_PLANE_STATE_UNSPECIFIED LoadBalancerDataPlaneState = 0
	LoadBalancerDataPlaneState_LOAD_BALANCER_DATA_PLANE_STATE_UNKNOWN     LoadBalancerDataPlaneState = 1
	LoadBalancerDataPlaneState_LOAD_BALANCER_DATA_PLANE_STATE_HEALTHY     LoadBalancerDataPlaneState = 2
	LoadBalancerDataPlaneState_LOAD_BALANCER_DATA_PLANE_STATE_UNHEALTHY   LoadBalancerDataPlaneState = 3
)

// Enum value maps for LoadBalancerDataPlaneState.
var (
	LoadBalancerDataPlaneState_name = map[int32]string{
		0: "LOAD_BALANCER_DATA_PLANE_STATE_UNSPECIFIED",
		1: "LOAD_BALANCER_DATA_PLANE_STATE_UNKNOWN",
		2: "LOAD_BALANCER_DATA_PLANE_STATE_HEALTHY",
		3: "LOAD_BALANCER_DATA_PLANE_STATE_UNHEALTHY",
	}
	LoadBalancerDataPlaneState_value = map[string]int32{
		"LOAD_BALANCER_DATA_PLANE_STATE_UNSPECIFIED": 0,
		"LOAD_BALANCER_DATA_PLANE_STATE_UNKNOWN":     1,
		"LOAD_BALANCER_DATA_PLANE_STATE_HEALTHY":     2,
		"LOAD_BALANCER_DATA_PLANE_STATE_UNHEALTHY":   3,
	}
)

func (x LoadBalancerDataPlaneState) Enum() *LoadBalancerDataPlaneState {
	p := new(LoadBalancerDataPlaneState)
	*p = x
	return p
}

func (x LoadBalancerDataPlaneState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LoadBalancerDataPlaneState) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_load_balancer_proto_enumTypes[5].Descriptor()
}

func (LoadBalancerDataPlaneState) Type() protoreflect.EnumType {
	return &file_network_v1_load_balancer_proto_enumTypes[5]
}

func (x LoadBalancerDataPlaneState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LoadBalancerDataPlaneState.Descriptor instead.
func (LoadBalancerDataPlaneState) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{5}
}

// Each HTTP listener uses the default Prefix("/") route. The legacy singular
// field defaults to HTTP/8080. The listener set permits port/backend/health
// changes, with stable retained IDs and names and unique listener ports.
type LoadBalancerListenerInput struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Protocol      LoadBalancerListenerProtocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=network.v1.LoadBalancerListenerProtocol" json:"protocol,omitempty"`
	Port          *uint32                      `protobuf:"varint,2,opt,name=port,proto3,oneof" json:"port,omitempty"`
	Id            string                       `protobuf:"bytes,3,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Backends      []*LoadBalancerBackendInput  `protobuf:"bytes,5,rep,name=backends,proto3" json:"backends,omitempty"`
	HealthCheck   *LoadBalancerHealthCheck     `protobuf:"bytes,6,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadBalancerListenerInput) Reset() {
	*x = LoadBalancerListenerInput{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerListenerInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerListenerInput) ProtoMessage() {}

func (x *LoadBalancerListenerInput) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerListenerInput.ProtoReflect.Descriptor instead.
func (*LoadBalancerListenerInput) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{0}
}

func (x *LoadBalancerListenerInput) GetProtocol() LoadBalancerListenerProtocol {
	if x != nil {
		return x.Protocol
	}
	return LoadBalancerListenerProtocol_LOAD_BALANCER_LISTENER_PROTOCOL_UNSPECIFIED
}

func (x *LoadBalancerListenerInput) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *LoadBalancerListenerInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoadBalancerListenerInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadBalancerListenerInput) GetBackends() []*LoadBalancerBackendInput {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *LoadBalancerListenerInput) GetHealthCheck() *LoadBalancerHealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

type LoadBalancerListener struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Id            string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Protocol      LoadBalancerListenerProtocol `protobuf:"varint,2,opt,name=protocol,proto3,enum=network.v1.LoadBalancerListenerProtocol" json:"protocol,omitempty"`
	Port          uint32                       `protobuf:"varint,3,opt,name=port,proto3" json:"port,omitempty"`
	Name          string                       `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Backends      []*LoadBalancerBackendMember `protobuf:"bytes,5,rep,name=backends,proto3" json:"backends,omitempty"`
	HealthCheck   *LoadBalancerHealthCheck     `protobuf:"bytes,6,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadBalancerListener) Reset() {
	*x = LoadBalancerListener{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerListener) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerListener) ProtoMessage() {}

func (x *LoadBalancerListener) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerListener.ProtoReflect.Descriptor instead.
func (*LoadBalancerListener) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{1}
}

func (x *LoadBalancerListener) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoadBalancerListener) GetProtocol() LoadBalancerListenerProtocol {
	if x != nil {
		return x.Protocol
	}
	return LoadBalancerListenerProtocol_LOAD_BALANCER_LISTENER_PROTOCOL_UNSPECIFIED
}

func (x *LoadBalancerListener) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *LoadBalancerListener) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadBalancerListener) GetBackends() []*LoadBalancerBackendMember {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *LoadBalancerListener) GetHealthCheck() *LoadBalancerHealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

// The backend must resolve to a current, allocated business address in this VPC
// using Attachment plus Provider identity facts. CIDR membership alone is not
// sufficient. ID is empty for new members; update can retain an existing member
// ID only with the same subnet/address/port identity. An endpoint change replaces
// the member. Network neither creates nor deletes the business workload.
type LoadBalancerBackendInput struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Id       string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubnetId string                 `protobuf:"bytes,2,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	Address  string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port     uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	// Absent defaults to 1. Zero retains the member with no traffic weight.
	Weight        *uint32 `protobuf:"varint,5,opt,name=weight,proto3,oneof" json:"weight,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadBalancerBackendInput) Reset() {
	*x = LoadBalancerBackendInput{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerBackendInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerBackendInput) ProtoMessage() {}

func (x *LoadBalancerBackendInput) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerBackendInput.ProtoReflect.Descriptor instead.
func (*LoadBalancerBackendInput) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{2}
}

func (x *LoadBalancerBackendInput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoadBalancerBackendInput) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *LoadBalancerBackendInput) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *LoadBalancerBackendInput) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *LoadBalancerBackendInput) GetWeight() uint32 {
	if x != nil && x.Weight != nil {
		return *x.Weight
	}
	return 0
}

type LoadBalancerBackendMember struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Id           string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SubnetId     string                 `protobuf:"bytes,2,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	Address      string                 `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Port         uint32                 `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	Weight       uint32                 `protobuf:"varint,5,opt,name=weight,proto3" json:"weight,omitempty"`
	AttachmentId string                 `protobuf:"bytes,6,opt,name=attachment_id,json=attachmentId,proto3" json:"attachment_id,omitempty"`
	// unknown, available or unavailable, based on this member's identity facts.
	State            string                 `protobuf:"bytes,7,opt,name=state,proto3" json:"state,omitempty"`
	Reason           string                 `protobuf:"bytes,8,opt,name=reason,proto3" json:"reason,omitempty"`
	ObservedAt       *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	ObservationStale bool                   `protobuf:"varint,10,opt,name=observation_stale,json=observationStale,proto3" json:"observation_stale,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LoadBalancerBackendMember) Reset() {
	*x = LoadBalancerBackendMember{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerBackendMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerBackendMember) ProtoMessage() {}

func (x *LoadBalancerBackendMember) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerBackendMember.ProtoReflect.Descriptor instead.
func (*LoadBalancerBackendMember) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{3}
}

func (x *LoadBalancerBackendMember) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoadBalancerBackendMember) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *LoadBalancerBackendMember) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *LoadBalancerBackendMember) GetPort() uint32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *LoadBalancerBackendMember) GetWeight() uint32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *LoadBalancerBackendMember) GetAttachmentId() string {
	if x != nil {
		return x.AttachmentId
	}
	return ""
}

func (x *LoadBalancerBackendMember) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *LoadBalancerBackendMember) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LoadBalancerBackendMember) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *LoadBalancerBackendMember) GetObservationStale() bool {
	if x != nil {
		return x.ObservationStale
	}
	return false
}

// First release: TCP active health checking, defaults 5s interval, 3s timeout,
// unhealthy threshold 3 and healthy threshold 1. Explicit values must be positive
// and timeout_seconds must be less than interval_seconds. The algorithm is
// RoundRobin and panicThreshold=0; neither is an arbitrary Provider policy.
type LoadBalancerHealthCheck struct {
	state              protoimpl.MessageState          `protogen:"open.v1"`
	Protocol           LoadBalancerHealthCheckProtocol `protobuf:"varint,1,opt,name=protocol,proto3,enum=network.v1.LoadBalancerHealthCheckProtocol" json:"protocol,omitempty"`
	IntervalSeconds    *uint32                         `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3,oneof" json:"interval_seconds,omitempty"`
	TimeoutSeconds     *uint32                         `protobuf:"varint,3,opt,name=timeout_seconds,json=timeoutSeconds,proto3,oneof" json:"timeout_seconds,omitempty"`
	UnhealthyThreshold *uint32                         `protobuf:"varint,4,opt,name=unhealthy_threshold,json=unhealthyThreshold,proto3,oneof" json:"unhealthy_threshold,omitempty"`
	HealthyThreshold   *uint32                         `protobuf:"varint,5,opt,name=healthy_threshold,json=healthyThreshold,proto3,oneof" json:"healthy_threshold,omitempty"`
	// Required on create/update: 1..65535, equal to every backend service port.
	// Absent on legacy records that use the endpoint serving port.
	Port          *uint32 `protobuf:"varint,6,opt,name=port,proto3,oneof" json:"port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadBalancerHealthCheck) Reset() {
	*x = LoadBalancerHealthCheck{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerHealthCheck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerHealthCheck) ProtoMessage() {}

func (x *LoadBalancerHealthCheck) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerHealthCheck.ProtoReflect.Descriptor instead.
func (*LoadBalancerHealthCheck) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{4}
}

func (x *LoadBalancerHealthCheck) GetProtocol() LoadBalancerHealthCheckProtocol {
	if x != nil {
		return x.Protocol
	}
	return LoadBalancerHealthCheckProtocol_LOAD_BALANCER_HEALTH_CHECK_PROTOCOL_UNSPECIFIED
}

func (x *LoadBalancerHealthCheck) GetIntervalSeconds() uint32 {
	if x != nil && x.IntervalSeconds != nil {
		return *x.IntervalSeconds
	}
	return 0
}

func (x *LoadBalancerHealthCheck) GetTimeoutSeconds() uint32 {
	if x != nil && x.TimeoutSeconds != nil {
		return *x.TimeoutSeconds
	}
	return 0
}

func (x *LoadBalancerHealthCheck) GetUnhealthyThreshold() uint32 {
	if x != nil && x.UnhealthyThreshold != nil {
		return *x.UnhealthyThreshold
	}
	return 0
}

func (x *LoadBalancerHealthCheck) GetHealthyThreshold() uint32 {
	if x != nil && x.HealthyThreshold != nil {
		return *x.HealthyThreshold
	}
	return 0
}

func (x *LoadBalancerHealthCheck) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

type LoadBalancer struct {
	state          protoimpl.MessageState       `protogen:"open.v1"`
	Id             string                       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TenantId       string                       `protobuf:"bytes,2,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	VpcId          string                       `protobuf:"bytes,3,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	SubnetId       string                       `protobuf:"bytes,4,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	Name           string                       `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                       `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Exposure       LoadBalancerExposure         `protobuf:"varint,7,opt,name=exposure,proto3,enum=network.v1.LoadBalancerExposure" json:"exposure,omitempty"`
	Flavor         string                       `protobuf:"bytes,8,opt,name=flavor,proto3" json:"flavor,omitempty"`
	PublicEipId    string                       `protobuf:"bytes,9,opt,name=public_eip_id,json=publicEipId,proto3" json:"public_eip_id,omitempty"`
	PrivateIp      string                       `protobuf:"bytes,10,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`
	Listener       *LoadBalancerListener        `protobuf:"bytes,11,opt,name=listener,proto3" json:"listener,omitempty"`
	Backends       []*LoadBalancerBackendMember `protobuf:"bytes,12,rep,name=backends,proto3" json:"backends,omitempty"`
	HealthCheck    *LoadBalancerHealthCheck     `protobuf:"bytes,13,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Algorithm      LoadBalancerAlgorithm        `protobuf:"varint,14,opt,name=algorithm,proto3,enum=network.v1.LoadBalancerAlgorithm" json:"algorithm,omitempty"`
	State          ResourceState                `protobuf:"varint,15,opt,name=state,proto3,enum=network.v1.ResourceState" json:"state,omitempty"`
	Reason         string                       `protobuf:"bytes,16,opt,name=reason,proto3" json:"reason,omitempty"`
	ReasonMessage  string                       `protobuf:"bytes,17,opt,name=reason_message,json=reasonMessage,proto3" json:"reason_message,omitempty"`
	Version        int64                        `protobuf:"varint,18,opt,name=version,proto3" json:"version,omitempty"`
	DesiredVersion int64                        `protobuf:"varint,19,opt,name=desired_version,json=desiredVersion,proto3" json:"desired_version,omitempty"`
	// Preserved during partially applied or failed updates; never copied from
	// desired_version until the corresponding configuration is verified.
	AppliedVersion     int64                          `protobuf:"varint,20,opt,name=applied_version,json=appliedVersion,proto3" json:"applied_version,omitempty"`
	ConfigurationState LoadBalancerConfigurationState `protobuf:"varint,21,opt,name=configuration_state,json=configurationState,proto3,enum=network.v1.LoadBalancerConfigurationState" json:"configuration_state,omitempty"`
	// unknown without a suitable fresh health source. Gateway/Route/Policy
	// Accepted, Pod Running and operation success cannot imply healthy.
	DataPlaneState   LoadBalancerDataPlaneState `protobuf:"varint,22,opt,name=data_plane_state,json=dataPlaneState,proto3,enum=network.v1.LoadBalancerDataPlaneState" json:"data_plane_state,omitempty"`
	ObservedAt       *timestamppb.Timestamp     `protobuf:"bytes,23,opt,name=observed_at,json=observedAt,proto3" json:"observed_at,omitempty"`
	ObservationStale bool                       `protobuf:"varint,24,opt,name=observation_stale,json=observationStale,proto3" json:"observation_stale,omitempty"`
	CreatedAt        *timestamppb.Timestamp     `protobuf:"bytes,25,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt        *timestamppb.Timestamp     `protobuf:"bytes,26,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	LastOperationId  string                     `protobuf:"bytes,27,opt,name=last_operation_id,json=lastOperationId,proto3" json:"last_operation_id,omitempty"`
	PublicAddress    string                     `protobuf:"bytes,28,opt,name=public_address,json=publicAddress,proto3" json:"public_address,omitempty"`
	// Timestamp of actual data-plane health evidence, independent of configured
	// resources. Absent when unknown; stale evidence forces data_plane_state=unknown.
	DataPlaneObservedAt *timestamppb.Timestamp  `protobuf:"bytes,29,opt,name=data_plane_observed_at,json=dataPlaneObservedAt,proto3" json:"data_plane_observed_at,omitempty"`
	Listeners           []*LoadBalancerListener `protobuf:"bytes,30,rep,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *LoadBalancer) Reset() {
	*x = LoadBalancer{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancer) ProtoMessage() {}

func (x *LoadBalancer) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancer.ProtoReflect.Descriptor instead.
func (*LoadBalancer) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{5}
}

func (x *LoadBalancer) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *LoadBalancer) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *LoadBalancer) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

func (x *LoadBalancer) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *LoadBalancer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadBalancer) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LoadBalancer) GetExposure() LoadBalancerExposure {
	if x != nil {
		return x.Exposure
	}
	return LoadBalancerExposure_LOAD_BALANCER_EXPOSURE_UNSPECIFIED
}

func (x *LoadBalancer) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *LoadBalancer) GetPublicEipId() string {
	if x != nil {
		return x.PublicEipId
	}
	return ""
}

func (x *LoadBalancer) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *LoadBalancer) GetListener() *LoadBalancerListener {
	if x != nil {
		return x.Listener
	}
	return nil
}

func (x *LoadBalancer) GetBackends() []*LoadBalancerBackendMember {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *LoadBalancer) GetHealthCheck() *LoadBalancerHealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *LoadBalancer) GetAlgorithm() LoadBalancerAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return LoadBalancerAlgorithm_LOAD_BALANCER_ALGORITHM_UNSPECIFIED
}

func (x *LoadBalancer) GetState() ResourceState {
	if x != nil {
		return x.State
	}
	return ResourceState_RESOURCE_STATE_UNSPECIFIED
}

func (x *LoadBalancer) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *LoadBalancer) GetReasonMessage() string {
	if x != nil {
		return x.ReasonMessage
	}
	return ""
}

func (x *LoadBalancer) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LoadBalancer) GetDesiredVersion() int64 {
	if x != nil {
		return x.DesiredVersion
	}
	return 0
}

func (x *LoadBalancer) GetAppliedVersion() int64 {
	if x != nil {
		return x.AppliedVersion
	}
	return 0
}

func (x *LoadBalancer) GetConfigurationState() LoadBalancerConfigurationState {
	if x != nil {
		return x.ConfigurationState
	}
	return LoadBalancerConfigurationState_LOAD_BALANCER_CONFIGURATION_STATE_UNSPECIFIED
}

func (x *LoadBalancer) GetDataPlaneState() LoadBalancerDataPlaneState {
	if x != nil {
		return x.DataPlaneState
	}
	return LoadBalancerDataPlaneState_LOAD_BALANCER_DATA_PLANE_STATE_UNSPECIFIED
}

func (x *LoadBalancer) GetObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ObservedAt
	}
	return nil
}

func (x *LoadBalancer) GetObservationStale() bool {
	if x != nil {
		return x.ObservationStale
	}
	return false
}

func (x *LoadBalancer) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *LoadBalancer) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *LoadBalancer) GetLastOperationId() string {
	if x != nil {
		return x.LastOperationId
	}
	return ""
}

func (x *LoadBalancer) GetPublicAddress() string {
	if x != nil {
		return x.PublicAddress
	}
	return ""
}

func (x *LoadBalancer) GetDataPlaneObservedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DataPlaneObservedAt
	}
	return nil
}

func (x *LoadBalancer) GetListeners() []*LoadBalancerListener {
	if x != nil {
		return x.Listeners
	}
	return nil
}

// Creation validates each HTTP listener and its backend/health configuration.
// Flavor is small (the default), medium or large. Private/public_private require a usable private_ip in subnet_id;
// public forbids private_ip. Public/public_private require an allocated, unclaimed
// Public EIP; private forbids public_eip_id. All three require fresh base readiness.
// Accepted intent atomically reserves parents, VIP/EIP and stable child identities.
// Replaying the same key and normalized intent returns the accepted snapshot;
// a changed intent under the same key is IDEMPOTENCY_CONFLICT.
type CreateLoadBalancerRequest struct {
	state          protoimpl.MessageState      `protogen:"open.v1"`
	TargetTenantId string                      `protobuf:"bytes,1,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"`
	Name           string                      `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                      `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	VpcId          string                      `protobuf:"bytes,4,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	SubnetId       string                      `protobuf:"bytes,5,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	Exposure       LoadBalancerExposure        `protobuf:"varint,6,opt,name=exposure,proto3,enum=network.v1.LoadBalancerExposure" json:"exposure,omitempty"`
	Flavor         string                      `protobuf:"bytes,7,opt,name=flavor,proto3" json:"flavor,omitempty"`
	PublicEipId    string                      `protobuf:"bytes,8,opt,name=public_eip_id,json=publicEipId,proto3" json:"public_eip_id,omitempty"`
	PrivateIp      string                      `protobuf:"bytes,9,opt,name=private_ip,json=privateIp,proto3" json:"private_ip,omitempty"`
	Listener       *LoadBalancerListenerInput  `protobuf:"bytes,10,opt,name=listener,proto3" json:"listener,omitempty"`
	Backends       []*LoadBalancerBackendInput `protobuf:"bytes,11,rep,name=backends,proto3" json:"backends,omitempty"`
	HealthCheck    *LoadBalancerHealthCheck    `protobuf:"bytes,12,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	IdempotencyKey string                      `protobuf:"bytes,13,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Listeners      *LoadBalancerListenerSet    `protobuf:"bytes,14,opt,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateLoadBalancerRequest) Reset() {
	*x = CreateLoadBalancerRequest{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoadBalancerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoadBalancerRequest) ProtoMessage() {}

func (x *CreateLoadBalancerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoadBalancerRequest.ProtoReflect.Descriptor instead.
func (*CreateLoadBalancerRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{6}
}

func (x *CreateLoadBalancerRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

func (x *CreateLoadBalancerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateLoadBalancerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateLoadBalancerRequest) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

func (x *CreateLoadBalancerRequest) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *CreateLoadBalancerRequest) GetExposure() LoadBalancerExposure {
	if x != nil {
		return x.Exposure
	}
	return LoadBalancerExposure_LOAD_BALANCER_EXPOSURE_UNSPECIFIED
}

func (x *CreateLoadBalancerRequest) GetFlavor() string {
	if x != nil {
		return x.Flavor
	}
	return ""
}

func (x *CreateLoadBalancerRequest) GetPublicEipId() string {
	if x != nil {
		return x.PublicEipId
	}
	return ""
}

func (x *CreateLoadBalancerRequest) GetPrivateIp() string {
	if x != nil {
		return x.PrivateIp
	}
	return ""
}

func (x *CreateLoadBalancerRequest) GetListener() *LoadBalancerListenerInput {
	if x != nil {
		return x.Listener
	}
	return nil
}

func (x *CreateLoadBalancerRequest) GetBackends() []*LoadBalancerBackendInput {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *CreateLoadBalancerRequest) GetHealthCheck() *LoadBalancerHealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *CreateLoadBalancerRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateLoadBalancerRequest) GetListeners() *LoadBalancerListenerSet {
	if x != nil {
		return x.Listeners
	}
	return nil
}

// Mutations return accepted resource/operation snapshots. Acceptance is not
// asynchronous configuration completion. GetLoadBalancerOperation polls the
// durable result; all GET/List methods are pure reads and never repair resources.
type CreateLoadBalancerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoadBalancer  *LoadBalancer          `protobuf:"bytes,1,opt,name=load_balancer,json=loadBalancer,proto3" json:"load_balancer,omitempty"`
	Operation     *Operation             `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateLoadBalancerResponse) Reset() {
	*x = CreateLoadBalancerResponse{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateLoadBalancerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateLoadBalancerResponse) ProtoMessage() {}

func (x *CreateLoadBalancerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateLoadBalancerResponse.ProtoReflect.Descriptor instead.
func (*CreateLoadBalancerResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{7}
}

func (x *CreateLoadBalancerResponse) GetLoadBalancer() *LoadBalancer {
	if x != nil {
		return x.LoadBalancer
	}
	return nil
}

func (x *CreateLoadBalancerResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

type GetLoadBalancerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetTenantId string                 `protobuf:"bytes,1,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"`
	LoadBalancerId string                 `protobuf:"bytes,2,opt,name=load_balancer_id,json=loadBalancerId,proto3" json:"load_balancer_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLoadBalancerRequest) Reset() {
	*x = GetLoadBalancerRequest{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoadBalancerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoadBalancerRequest) ProtoMessage() {}

func (x *GetLoadBalancerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoadBalancerRequest.ProtoReflect.Descriptor instead.
func (*GetLoadBalancerRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{8}
}

func (x *GetLoadBalancerRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

func (x *GetLoadBalancerRequest) GetLoadBalancerId() string {
	if x != nil {
		return x.LoadBalancerId
	}
	return ""
}

type GetLoadBalancerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoadBalancer  *LoadBalancer          `protobuf:"bytes,1,opt,name=load_balancer,json=loadBalancer,proto3" json:"load_balancer,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoadBalancerResponse) Reset() {
	*x = GetLoadBalancerResponse{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoadBalancerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoadBalancerResponse) ProtoMessage() {}

func (x *GetLoadBalancerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoadBalancerResponse.ProtoReflect.Descriptor instead.
func (*GetLoadBalancerResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{9}
}

func (x *GetLoadBalancerResponse) GetLoadBalancer() *LoadBalancer {
	if x != nil {
		return x.LoadBalancer
	}
	return nil
}

type ListLoadBalancersRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetTenantId string                 `protobuf:"bytes,1,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VpcId          string                 `protobuf:"bytes,3,opt,name=vpc_id,json=vpcId,proto3" json:"vpc_id,omitempty"`
	SubnetId       string                 `protobuf:"bytes,4,opt,name=subnet_id,json=subnetId,proto3" json:"subnet_id,omitempty"`
	Exposure       LoadBalancerExposure   `protobuf:"varint,5,opt,name=exposure,proto3,enum=network.v1.LoadBalancerExposure" json:"exposure,omitempty"`
	State          ResourceState          `protobuf:"varint,6,opt,name=state,proto3,enum=network.v1.ResourceState" json:"state,omitempty"`
	Limit          int32                  `protobuf:"varint,7,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor         string                 `protobuf:"bytes,8,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListLoadBalancersRequest) Reset() {
	*x = ListLoadBalancersRequest{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoadBalancersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoadBalancersRequest) ProtoMessage() {}

func (x *ListLoadBalancersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoadBalancersRequest.ProtoReflect.Descriptor instead.
func (*ListLoadBalancersRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{10}
}

func (x *ListLoadBalancersRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

func (x *ListLoadBalancersRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListLoadBalancersRequest) GetVpcId() string {
	if x != nil {
		return x.VpcId
	}
	return ""
}

func (x *ListLoadBalancersRequest) GetSubnetId() string {
	if x != nil {
		return x.SubnetId
	}
	return ""
}

func (x *ListLoadBalancersRequest) GetExposure() LoadBalancerExposure {
	if x != nil {
		return x.Exposure
	}
	return LoadBalancerExposure_LOAD_BALANCER_EXPOSURE_UNSPECIFIED
}

func (x *ListLoadBalancersRequest) GetState() ResourceState {
	if x != nil {
		return x.State
	}
	return ResourceState_RESOURCE_STATE_UNSPECIFIED
}

func (x *ListLoadBalancersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListLoadBalancersRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ListLoadBalancersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*LoadBalancer        `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Total         int64                  `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListLoadBalancersResponse) Reset() {
	*x = ListLoadBalancersResponse{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListLoadBalancersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListLoadBalancersResponse) ProtoMessage() {}

func (x *ListLoadBalancersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListLoadBalancersResponse.ProtoReflect.Descriptor instead.
func (*ListLoadBalancersResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{11}
}

func (x *ListLoadBalancersResponse) GetItems() []*LoadBalancer {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListLoadBalancersResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListLoadBalancersResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Full replacement of mutable fields only: name, description, backend set and
// supported health check parameters. Immutable placement/exposure/EIP/VIP/flavor/
// placement fields are absent. expected_version is the resource version returned
// by GET. Accepted updates retain the old applied_version until verified.
// Idempotent replay is checked before version conflict; concurrent operations on
// one LB are mutually exclusive and deletion closes admission to new updates.
type UpdateLoadBalancerRequest struct {
	state           protoimpl.MessageState      `protogen:"open.v1"`
	TargetTenantId  string                      `protobuf:"bytes,1,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"`
	LoadBalancerId  string                      `protobuf:"bytes,2,opt,name=load_balancer_id,json=loadBalancerId,proto3" json:"load_balancer_id,omitempty"`
	ExpectedVersion int64                       `protobuf:"varint,3,opt,name=expected_version,json=expectedVersion,proto3" json:"expected_version,omitempty"`
	IdempotencyKey  string                      `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Name            string                      `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                      `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	Backends        []*LoadBalancerBackendInput `protobuf:"bytes,7,rep,name=backends,proto3" json:"backends,omitempty"`
	HealthCheck     *LoadBalancerHealthCheck    `protobuf:"bytes,8,opt,name=health_check,json=healthCheck,proto3" json:"health_check,omitempty"`
	Listeners       *LoadBalancerListenerSet    `protobuf:"bytes,9,opt,name=listeners,proto3" json:"listeners,omitempty"`
	UpdateMask      *fieldmaskpb.FieldMask      `protobuf:"bytes,10,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	Data            *LoadBalancerMutableData    `protobuf:"bytes,11,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateLoadBalancerRequest) Reset() {
	*x = UpdateLoadBalancerRequest{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoadBalancerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoadBalancerRequest) ProtoMessage() {}

func (x *UpdateLoadBalancerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoadBalancerRequest.ProtoReflect.Descriptor instead.
func (*UpdateLoadBalancerRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateLoadBalancerRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

func (x *UpdateLoadBalancerRequest) GetLoadBalancerId() string {
	if x != nil {
		return x.LoadBalancerId
	}
	return ""
}

func (x *UpdateLoadBalancerRequest) GetExpectedVersion() int64 {
	if x != nil {
		return x.ExpectedVersion
	}
	return 0
}

func (x *UpdateLoadBalancerRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *UpdateLoadBalancerRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateLoadBalancerRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateLoadBalancerRequest) GetBackends() []*LoadBalancerBackendInput {
	if x != nil {
		return x.Backends
	}
	return nil
}

func (x *UpdateLoadBalancerRequest) GetHealthCheck() *LoadBalancerHealthCheck {
	if x != nil {
		return x.HealthCheck
	}
	return nil
}

func (x *UpdateLoadBalancerRequest) GetListeners() *LoadBalancerListenerSet {
	if x != nil {
		return x.Listeners
	}
	return nil
}

func (x *UpdateLoadBalancerRequest) GetUpdateMask() *fieldmaskpb.FieldMask {
	if x != nil {
		return x.UpdateMask
	}
	return nil
}

func (x *UpdateLoadBalancerRequest) GetData() *LoadBalancerMutableData {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateLoadBalancerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoadBalancer  *LoadBalancer          `protobuf:"bytes,1,opt,name=load_balancer,json=loadBalancer,proto3" json:"load_balancer,omitempty"`
	Operation     *Operation             `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLoadBalancerResponse) Reset() {
	*x = UpdateLoadBalancerResponse{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLoadBalancerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLoadBalancerResponse) ProtoMessage() {}

func (x *UpdateLoadBalancerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLoadBalancerResponse.ProtoReflect.Descriptor instead.
func (*UpdateLoadBalancerResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{13}
}

func (x *UpdateLoadBalancerResponse) GetLoadBalancer() *LoadBalancer {
	if x != nil {
		return x.LoadBalancer
	}
	return nil
}

func (x *UpdateLoadBalancerResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

// Delete is idempotent by tenant/resource identity, including while deleting or
// after completion, as with existing network deletes. Returns the same delete
// operation. Claims and parent/VIP reservations survive unknown Provider results.
// Completion requires actual release; it retains the independent Public EIP,
// VPC base connectivity and business workloads.
type DeleteLoadBalancerRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetTenantId string                 `protobuf:"bytes,1,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"`
	LoadBalancerId string                 `protobuf:"bytes,2,opt,name=load_balancer_id,json=loadBalancerId,proto3" json:"load_balancer_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteLoadBalancerRequest) Reset() {
	*x = DeleteLoadBalancerRequest{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLoadBalancerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLoadBalancerRequest) ProtoMessage() {}

func (x *DeleteLoadBalancerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLoadBalancerRequest.ProtoReflect.Descriptor instead.
func (*DeleteLoadBalancerRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteLoadBalancerRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

func (x *DeleteLoadBalancerRequest) GetLoadBalancerId() string {
	if x != nil {
		return x.LoadBalancerId
	}
	return ""
}

type DeleteLoadBalancerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LoadBalancer  *LoadBalancer          `protobuf:"bytes,1,opt,name=load_balancer,json=loadBalancer,proto3" json:"load_balancer,omitempty"`
	Operation     *Operation             `protobuf:"bytes,2,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLoadBalancerResponse) Reset() {
	*x = DeleteLoadBalancerResponse{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLoadBalancerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLoadBalancerResponse) ProtoMessage() {}

func (x *DeleteLoadBalancerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLoadBalancerResponse.ProtoReflect.Descriptor instead.
func (*DeleteLoadBalancerResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteLoadBalancerResponse) GetLoadBalancer() *LoadBalancer {
	if x != nil {
		return x.LoadBalancer
	}
	return nil
}

func (x *DeleteLoadBalancerResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

// Only this tenant's load_balancer operations are visible, including deletes.
// Cross-tenant or non-LB IDs return NOT_FOUND, never an operation from another API.
type GetLoadBalancerOperationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TargetTenantId string                 `protobuf:"bytes,1,opt,name=target_tenant_id,json=targetTenantId,proto3" json:"target_tenant_id,omitempty"`
	OperationId    string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetLoadBalancerOperationRequest) Reset() {
	*x = GetLoadBalancerOperationRequest{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoadBalancerOperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoadBalancerOperationRequest) ProtoMessage() {}

func (x *GetLoadBalancerOperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoadBalancerOperationRequest.ProtoReflect.Descriptor instead.
func (*GetLoadBalancerOperationRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{16}
}

func (x *GetLoadBalancerOperationRequest) GetTargetTenantId() string {
	if x != nil {
		return x.TargetTenantId
	}
	return ""
}

func (x *GetLoadBalancerOperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type GetLoadBalancerOperationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Operation     *Operation             `protobuf:"bytes,1,opt,name=operation,proto3" json:"operation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLoadBalancerOperationResponse) Reset() {
	*x = GetLoadBalancerOperationResponse{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLoadBalancerOperationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLoadBalancerOperationResponse) ProtoMessage() {}

func (x *GetLoadBalancerOperationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLoadBalancerOperationResponse.ProtoReflect.Descriptor instead.
func (*GetLoadBalancerOperationResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{17}
}

func (x *GetLoadBalancerOperationResponse) GetOperation() *Operation {
	if x != nil {
		return x.Operation
	}
	return nil
}

// Presence distinguishes omission from an explicitly empty replacement.
type LoadBalancerListenerSet struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Items         []*LoadBalancerListenerInput `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadBalancerListenerSet) Reset() {
	*x = LoadBalancerListenerSet{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerListenerSet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerListenerSet) ProtoMessage() {}

func (x *LoadBalancerListenerSet) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerListenerSet.ProtoReflect.Descriptor instead.
func (*LoadBalancerListenerSet) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{18}
}

func (x *LoadBalancerListenerSet) GetItems() []*LoadBalancerListenerInput {
	if x != nil {
		return x.Items
	}
	return nil
}

type LoadBalancerMutableData struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Name          string                   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Listeners     *LoadBalancerListenerSet `protobuf:"bytes,3,opt,name=listeners,proto3" json:"listeners,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LoadBalancerMutableData) Reset() {
	*x = LoadBalancerMutableData{}
	mi := &file_network_v1_load_balancer_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LoadBalancerMutableData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LoadBalancerMutableData) ProtoMessage() {}

func (x *LoadBalancerMutableData) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_load_balancer_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LoadBalancerMutableData.ProtoReflect.Descriptor instead.
func (*LoadBalancerMutableData) Descriptor() ([]byte, []int) {
	return file_network_v1_load_balancer_proto_rawDescGZIP(), []int{19}
}

func (x *LoadBalancerMutableData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *LoadBalancerMutableData) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *LoadBalancerMutableData) GetListeners() *LoadBalancerListenerSet {
	if x != nil {
		return x.Listeners
	}
	return nil
}

var File_network_v1_load_balancer_proto protoreflect.FileDescriptor

const file_network_v1_load_balancer_proto_rawDesc = "" +
	"\n" +
	"\x1enetwork/v1/load_balancer.proto\x12\n" +
	"network.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a google/protobuf/field_mask.proto\x1a\x18network/v1/network.proto\"\xb1\x02\n" +
	"\x19LoadBalancerListenerInput\x12D\n" +
	"\bprotocol\x18\x01 \x01(\x0e2(.network.v1.LoadBalancerListenerProtocolR\bprotocol\x12\x17\n" +
	"\x04port\x18\x02 \x01(\rH\x00R\x04port\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\x03 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12@\n" +
	"\bbackends\x18\x05 \x03(\v2$.network.v1.LoadBalancerBackendInputR\bbackends\x12F\n" +
	"\fhealth_check\x18\x06 \x01(\v2#.network.v1.LoadBalancerHealthCheckR\vhealthCheckB\a\n" +
	"\x05_port\"\x9f\x02\n" +
	"\x14LoadBalancerListener\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12D\n" +
	"\bprotocol\x18\x02 \x01(\x0e2(.network.v1.LoadBalancerListenerProtocolR\bprotocol\x12\x12\n" +
	"\x04port\x18\x03 \x01(\rR\x04port\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12A\n" +
	"\bbackends\x18\x05 \x03(\v2%.network.v1.LoadBalancerBackendMemberR\bbackends\x12F\n" +
	"\fhealth_check\x18\x06 \x01(\v2#.network.v1.LoadBalancerHealthCheckR\vhealthCheck\"\x9d\x01\n" +
	"\x18LoadBalancerBackendInput\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsubnet_id\x18\x02 \x01(\tR\bsubnetId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x1b\n" +
	"\x06weight\x18\x05 \x01(\rH\x00R\x06weight\x88\x01\x01B\t\n" +
	"\a_weight\"\xcb\x02\n" +
	"\x19LoadBalancerBackendMember\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\tsubnet_id\x18\x02 \x01(\tR\bsubnetId\x12\x18\n" +
	"\aaddress\x18\x03 \x01(\tR\aaddress\x12\x12\n" +
	"\x04port\x18\x04 \x01(\rR\x04port\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\rR\x06weight\x12#\n" +
	"\rattachment_id\x18\x06 \x01(\tR\fattachmentId\x12\x14\n" +
	"\x05state\x18\a \x01(\tR\x05state\x12\x16\n" +
	"\x06reason\x18\b \x01(\tR\x06reason\x12;\n" +
	"\vobserved_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12+\n" +
	"\x11observation_stale\x18\n" +
	" \x01(\bR\x10observationStale\"\xa1\x03\n" +
	"\x17LoadBalancerHealthCheck\x12G\n" +
	"\bprotocol\x18\x01 \x01(\x0e2+.network.v1.LoadBalancerHealthCheckProtocolR\bprotocol\x12.\n" +
	"\x10interval_seconds\x18\x02 \x01(\rH\x00R\x0fintervalSeconds\x88\x01\x01\x12,\n" +
	"\x0ftimeout_seconds\x18\x03 \x01(\rH\x01R\x0etimeoutSeconds\x88\x01\x01\x124\n" +
	"\x13unhealthy_threshold\x18\x04 \x01(\rH\x02R\x12unhealthyThreshold\x88\x01\x01\x120\n" +
	"\x11healthy_threshold\x18\x05 \x01(\rH\x03R\x10healthyThreshold\x88\x01\x01\x12\x17\n" +
	"\x04port\x18\x06 \x01(\rH\x04R\x04port\x88\x01\x01B\x13\n" +
	"\x11_interval_secondsB\x12\n" +
	"\x10_timeout_secondsB\x16\n" +
	"\x14_unhealthy_thresholdB\x14\n" +
	"\x12_healthy_thresholdB\a\n" +
	"\x05_port\"\x97\v\n" +
	"\fLoadBalancer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n" +
	"\ttenant_id\x18\x02 \x01(\tR\btenantId\x12\x15\n" +
	"\x06vpc_id\x18\x03 \x01(\tR\x05vpcId\x12\x1b\n" +
	"\tsubnet_id\x18\x04 \x01(\tR\bsubnetId\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12<\n" +
	"\bexposure\x18\a \x01(\x0e2 .network.v1.LoadBalancerExposureR\bexposure\x12\x16\n" +
	"\x06flavor\x18\b \x01(\tR\x06flavor\x12\"\n" +
	"\rpublic_eip_id\x18\t \x01(\tR\vpublicEipId\x12\x1d\n" +
	"\n" +
	"private_ip\x18\n" +
	" \x01(\tR\tprivateIp\x12<\n" +
	"\blistener\x18\v \x01(\v2 .network.v1.LoadBalancerListenerR\blistener\x12A\n" +
	"\bbackends\x18\f \x03(\v2%.network.v1.LoadBalancerBackendMemberR\bbackends\x12F\n" +
	"\fhealth_check\x18\r \x01(\v2#.network.v1.LoadBalancerHealthCheckR\vhealthCheck\x12?\n" +
	"\talgorithm\x18\x0e \x01(\x0e2!.network.v1.LoadBalancerAlgorithmR\talgorithm\x12/\n" +
	"\x05state\x18\x0f \x01(\x0e2\x19.network.v1.ResourceStateR\x05state\x12\x16\n" +
	"\x06reason\x18\x10 \x01(\tR\x06reason\x12%\n" +
	"\x0ereason_message\x18\x11 \x01(\tR\rreasonMessage\x12\x18\n" +
	"\aversion\x18\x12 \x01(\x03R\aversion\x12'\n" +
	"\x0fdesired_version\x18\x13 \x01(\x03R\x0edesiredVersion\x12'\n" +
	"\x0fapplied_version\x18\x14 \x01(\x03R\x0eappliedVersion\x12[\n" +
	"\x13configuration_state\x18\x15 \x01(\x0e2*.network.v1.LoadBalancerConfigurationStateR\x12configurationState\x12P\n" +
	"\x10data_plane_state\x18\x16 \x01(\x0e2&.network.v1.LoadBalancerDataPlaneStateR\x0edataPlaneState\x12;\n" +
	"\vobserved_at\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"observedAt\x12+\n" +
	"\x11observation_stale\x18\x18 \x01(\bR\x10observationStale\x129\n" +
	"\n" +
	"created_at\x18\x19 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x1a \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12*\n" +
	"\x11last_operation_id\x18\x1b \x01(\tR\x0flastOperationId\x12%\n" +
	"\x0epublic_address\x18\x1c \x01(\tR\rpublicAddress\x12O\n" +
	"\x16data_plane_observed_at\x18\x1d \x01(\v2\x1a.google.protobuf.TimestampR\x13dataPlaneObservedAt\x12>\n" +
	"\tlisteners\x18\x1e \x03(\v2 .network.v1.LoadBalancerListenerR\tlisteners\"\x81\x05\n" +
	"\x19CreateLoadBalancerRequest\x12(\n" +
	"\x10target_tenant_id\x18\x01 \x01(\tR\x0etargetTenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x15\n" +
	"\x06vpc_id\x18\x04 \x01(\tR\x05vpcId\x12\x1b\n" +
	"\tsubnet_id\x18\x05 \x01(\tR\bsubnetId\x12<\n" +
	"\bexposure\x18\x06 \x01(\x0e2 .network.v1.LoadBalancerExposureR\bexposure\x12\x16\n" +
	"\x06flavor\x18\a \x01(\tR\x06flavor\x12\"\n" +
	"\rpublic_eip_id\x18\b \x01(\tR\vpublicEipId\x12\x1d\n" +
	"\n" +
	"private_ip\x18\t \x01(\tR\tprivateIp\x12A\n" +
	"\blistener\x18\n" +
	" \x01(\v2%.network.v1.LoadBalancerListenerInputR\blistener\x12@\n" +
	"\bbackends\x18\v \x03(\v2$.network.v1.LoadBalancerBackendInputR\bbackends\x12F\n" +
	"\fhealth_check\x18\f \x01(\v2#.network.v1.LoadBalancerHealthCheckR\vhealthCheck\x12'\n" +
	"\x0fidempotency_key\x18\r \x01(\tR\x0eidempotencyKey\x12A\n" +
	"\tlisteners\x18\x0e \x01(\v2#.network.v1.LoadBalancerListenerSetR\tlisteners\"\x90\x01\n" +
	"\x1aCreateLoadBalancerResponse\x12=\n" +
	"\rload_balancer\x18\x01 \x01(\v2\x18.network.v1.LoadBalancerR\floadBalancer\x123\n" +
	"\toperation\x18\x02 \x01(\v2\x15.network.v1.OperationR\toperation\"l\n" +
	"\x16GetLoadBalancerRequest\x12(\n" +
	"\x10target_tenant_id\x18\x01 \x01(\tR\x0etargetTenantId\x12(\n" +
	"\x10load_balancer_id\x18\x02 \x01(\tR\x0eloadBalancerId\"X\n" +
	"\x17GetLoadBalancerResponse\x12=\n" +
	"\rload_balancer\x18\x01 \x01(\v2\x18.network.v1.LoadBalancerR\floadBalancer\"\xa9\x02\n" +
	"\x18ListLoadBalancersRequest\x12(\n" +
	"\x10target_tenant_id\x18\x01 \x01(\tR\x0etargetTenantId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x15\n" +
	"\x06vpc_id\x18\x03 \x01(\tR\x05vpcId\x12\x1b\n" +
	"\tsubnet_id\x18\x04 \x01(\tR\bsubnetId\x12<\n" +
	"\bexposure\x18\x05 \x01(\x0e2 .network.v1.LoadBalancerExposureR\bexposure\x12/\n" +
	"\x05state\x18\x06 \x01(\x0e2\x19.network.v1.ResourceStateR\x05state\x12\x14\n" +
	"\x05limit\x18\a \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\b \x01(\tR\x06cursor\"\x82\x01\n" +
	"\x19ListLoadBalancersResponse\x12.\n" +
	"\x05items\x18\x01 \x03(\v2\x18.network.v1.LoadBalancerR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x14\n" +
	"\x05total\x18\x03 \x01(\x03R\x05total\"\xbc\x04\n" +
	"\x19UpdateLoadBalancerRequest\x12(\n" +
	"\x10target_tenant_id\x18\x01 \x01(\tR\x0etargetTenantId\x12(\n" +
	"\x10load_balancer_id\x18\x02 \x01(\tR\x0eloadBalancerId\x12)\n" +
	"\x10expected_version\x18\x03 \x01(\x03R\x0fexpectedVersion\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12@\n" +
	"\bbackends\x18\a \x03(\v2$.network.v1.LoadBalancerBackendInputR\bbackends\x12F\n" +
	"\fhealth_check\x18\b \x01(\v2#.network.v1.LoadBalancerHealthCheckR\vhealthCheck\x12A\n" +
	"\tlisteners\x18\t \x01(\v2#.network.v1.LoadBalancerListenerSetR\tlisteners\x12;\n" +
	"\vupdate_mask\x18\n" +
	" \x01(\v2\x1a.google.protobuf.FieldMaskR\n" +
	"updateMask\x127\n" +
	"\x04data\x18\v \x01(\v2#.network.v1.LoadBalancerMutableDataR\x04data\"\x90\x01\n" +
	"\x1aUpdateLoadBalancerResponse\x12=\n" +
	"\rload_balancer\x18\x01 \x01(\v2\x18.network.v1.LoadBalancerR\floadBalancer\x123\n" +
	"\toperation\x18\x02 \x01(\v2\x15.network.v1.OperationR\toperation\"o\n" +
	"\x19DeleteLoadBalancerRequest\x12(\n" +
	"\x10target_tenant_id\x18\x01 \x01(\tR\x0etargetTenantId\x12(\n" +
	"\x10load_balancer_id\x18\x02 \x01(\tR\x0eloadBalancerId\"\x90\x01\n" +
	"\x1aDeleteLoadBalancerResponse\x12=\n" +
	"\rload_balancer\x18\x01 \x01(\v2\x18.network.v1.LoadBalancerR\floadBalancer\x123\n" +
	"\toperation\x18\x02 \x01(\v2\x15.network.v1.OperationR\toperation\"n\n" +
	"\x1fGetLoadBalancerOperationRequest\x12(\n" +
	"\x10target_tenant_id\x18\x01 \x01(\tR\x0etargetTenantId\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\"W\n" +
	" GetLoadBalancerOperationResponse\x123\n" +
	"\toperation\x18\x01 \x01(\v2\x15.network.v1.OperationR\toperation\"V\n" +
	"\x17LoadBalancerListenerSet\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.network.v1.LoadBalancerListenerInputR\x05items\"\x92\x01\n" +
	"\x17LoadBalancerMutableData\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12A\n" +
	"\tlisteners\x18\x03 \x01(\v2#.network.v1.LoadBalancerListenerSetR\tlisteners*\xb0\x01\n" +
	"\x14LoadBalancerExposure\x12&\n" +
	"\"LOAD_BALANCER_EXPOSURE_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eLOAD_BALANCER_EXPOSURE_PRIVATE\x10\x01\x12!\n" +
	"\x1dLOAD_BALANCER_EXPOSURE_PUBLIC\x10\x02\x12)\n" +
	"%LOAD_BALANCER_EXPOSURE_PUBLIC_PRIVATE\x10\x03*y\n" +
	"\x1cLoadBalancerListenerProtocol\x12/\n" +
	"+LOAD_BALANCER_LISTENER_PROTOCOL_UNSPECIFIED\x10\x00\x12(\n" +
	"$LOAD_BALANCER_LISTENER_PROTOCOL_HTTP\x10\x01*i\n" +
	"\x15LoadBalancerAlgorithm\x12'\n" +
	"#LOAD_BALANCER_ALGORITHM_UNSPECIFIED\x10\x00\x12'\n" +
	"#LOAD_BALANCER_ALGORITHM_ROUND_ROBIN\x10\x01*\x83\x01\n" +
	"\x1fLoadBalancerHealthCheckProtocol\x123\n" +
	"/LOAD_BALANCER_HEALTH_CHECK_PROTOCOL_UNSPECIFIED\x10\x00\x12+\n" +
	"'LOAD_BALANCER_HEALTH_CHECK_PROTOCOL_TCP\x10\x01*\xc3\x02\n" +
	"\x1eLoadBalancerConfigurationState\x121\n" +
	"-LOAD_BALANCER_CONFIGURATION_STATE_UNSPECIFIED\x10\x00\x12-\n" +
	")LOAD_BALANCER_CONFIGURATION_STATE_PENDING\x10\x01\x12.\n" +
	"*LOAD_BALANCER_CONFIGURATION_STATE_APPLYING\x10\x02\x120\n" +
	",LOAD_BALANCER_CONFIGURATION_STATE_CONFIGURED\x10\x03\x12.\n" +
	"*LOAD_BALANCER_CONFIGURATION_STATE_DEGRADED\x10\x04\x12-\n" +
	")LOAD_BALANCER_CONFIGURATION_STATE_UNKNOWN\x10\x05*\xd2\x01\n" +
	"\x1aLoadBalancerDataPlaneState\x12.\n" +
	"*LOAD_BALANCER_DATA_PLANE_STATE_UNSPECIFIED\x10\x00\x12*\n" +
	"&LOAD_BALANCER_DATA_PLANE_STATE_UNKNOWN\x10\x01\x12*\n" +
	"&LOAD_BALANCER_DATA_PLANE_STATE_HEALTHY\x10\x02\x12,\n" +
	"(LOAD_BALANCER_DATA_PLANE_STATE_UNHEALTHY\x10\x032\xff\x04\n" +
	"\x19TenantLoadBalancerService\x12c\n" +
	"\x12CreateLoadBalancer\x12%.network.v1.CreateLoadBalancerRequest\x1a&.network.v1.CreateLoadBalancerResponse\x12Z\n" +
	"\x0fGetLoadBalancer\x12\".network.v1.GetLoadBalancerRequest\x1a#.network.v1.GetLoadBalancerResponse\x12`\n" +
	"\x11ListLoadBalancers\x12$.network.v1.ListLoadBalancersRequest\x1a%.network.v1.ListLoadBalancersResponse\x12c\n" +
	"\x12UpdateLoadBalancer\x12%.network.v1.UpdateLoadBalancerRequest\x1a&.network.v1.UpdateLoadBalancerResponse\x12c\n" +
	"\x12DeleteLoadBalancer\x12%.network.v1.DeleteLoadBalancerRequest\x1a&.network.v1.DeleteLoadBalancerResponse\x12u\n" +
	"\x18GetLoadBalancerOperation\x12+.network.v1.GetLoadBalancerOperationRequest\x1a,.network.v1.GetLoadBalancerOperationResponseBHZFgithub.com/zhangzhe-ctrl/ani-resource-service/api/network/v1;networkv1b\x06proto3"

var (
	file_network_v1_load_balancer_proto_rawDescOnce sync.Once
	file_network_v1_load_balancer_proto_rawDescData []byte
)

func file_network_v1_load_balancer_proto_rawDescGZIP() []byte {
	file_network_v1_load_balancer_proto_rawDescOnce.Do(func() {
		file_network_v1_load_balancer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_v1_load_balancer_proto_rawDesc), len(file_network_v1_load_balancer_proto_rawDesc)))
	})
	return file_network_v1_load_balancer_proto_rawDescData
}

var file_network_v1_load_balancer_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_network_v1_load_balancer_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_network_v1_load_balancer_proto_goTypes = []any{
	(LoadBalancerExposure)(0),                // 0: network.v1.LoadBalancerExposure
	(LoadBalancerListenerProtocol)(0),        // 1: network.v1.LoadBalancerListenerProtocol
	(LoadBalancerAlgorithm)(0),               // 2: network.v1.LoadBalancerAlgorithm
	(LoadBalancerHealthCheckProtocol)(0),     // 3: network.v1.LoadBalancerHealthCheckProtocol
	(LoadBalancerConfigurationState)(0),      // 4: network.v1.LoadBalancerConfigurationState
	(LoadBalancerDataPlaneState)(0),          // 5: network.v1.LoadBalancerDataPlaneState
	(*LoadBalancerListenerInput)(nil),        // 6: network.v1.LoadBalancerListenerInput
	(*LoadBalancerListener)(nil),             // 7: network.v1.LoadBalancerListener
	(*LoadBalancerBackendInput)(nil),         // 8: network.v1.LoadBalancerBackendInput
	(*LoadBalancerBackendMember)(nil),        // 9: network.v1.LoadBalancerBackendMember
	(*LoadBalancerHealthCheck)(nil),          // 10: network.v1.LoadBalancerHealthCheck
	(*LoadBalancer)(nil),                     // 11: network.v1.LoadBalancer
	(*CreateLoadBalancerRequest)(nil),        // 12: network.v1.CreateLoadBalancerRequest
	(*CreateLoadBalancerResponse)(nil),       // 13: network.v1.CreateLoadBalancerResponse
	(*GetLoadBalancerRequest)(nil),           // 14: network.v1.GetLoadBalancerRequest
	(*GetLoadBalancerResponse)(nil),          // 15: network.v1.GetLoadBalancerResponse
	(*ListLoadBalancersRequest)(nil),         // 16: network.v1.ListLoadBalancersRequest
	(*ListLoadBalancersResponse)(nil),        // 17: network.v1.ListLoadBalancersResponse
	(*UpdateLoadBalancerRequest)(nil),        // 18: network.v1.UpdateLoadBalancerRequest
	(*UpdateLoadBalancerResponse)(nil),       // 19: network.v1.UpdateLoadBalancerResponse
	(*DeleteLoadBalancerRequest)(nil),        // 20: network.v1.DeleteLoadBalancerRequest
	(*DeleteLoadBalancerResponse)(nil),       // 21: network.v1.DeleteLoadBalancerResponse
	(*GetLoadBalancerOperationRequest)(nil),  // 22: network.v1.GetLoadBalancerOperationRequest
	(*GetLoadBalancerOperationResponse)(nil), // 23: network.v1.GetLoadBalancerOperationResponse
	(*LoadBalancerListenerSet)(nil),          // 24: network.v1.LoadBalancerListenerSet
	(*LoadBalancerMutableData)(nil),          // 25: network.v1.LoadBalancerMutableData
	(*timestamppb.Timestamp)(nil),            // 26: google.protobuf.Timestamp
	(ResourceState)(0),                       // 27: network.v1.ResourceState
	(*Operation)(nil),                        // 28: network.v1.Operation
	(*fieldmaskpb.FieldMask)(nil),            // 29: google.protobuf.FieldMask
}
var file_network_v1_load_balancer_proto_depIdxs = []int32{
	1,  // 0: network.v1.LoadBalancerListenerInput.protocol:type_name -> network.v1.LoadBalancerListenerProtocol
	8,  // 1: network.v1.LoadBalancerListenerInput.backends:type_name -> network.v1.LoadBalancerBackendInput
	10, // 2: network.v1.LoadBalancerListenerInput.health_check:type_name -> network.v1.LoadBalancerHealthCheck
	1,  // 3: network.v1.LoadBalancerListener.protocol:type_name -> network.v1.LoadBalancerListenerProtocol
	9,  // 4: network.v1.LoadBalancerListener.backends:type_name -> network.v1.LoadBalancerBackendMember
	10, // 5: network.v1.LoadBalancerListener.health_check:type_name -> network.v1.LoadBalancerHealthCheck
	26, // 6: network.v1.LoadBalancerBackendMember.observed_at:type_name -> google.protobuf.Timestamp
	3,  // 7: network.v1.LoadBalancerHealthCheck.protocol:type_name -> network.v1.LoadBalancerHealthCheckProtocol
	0,  // 8: network.v1.LoadBalancer.exposure:type_name -> network.v1.LoadBalancerExposure
	7,  // 9: network.v1.LoadBalancer.listener:type_name -> network.v1.LoadBalancerListener
	9,  // 10: network.v1.LoadBalancer.backends:type_name -> network.v1.LoadBalancerBackendMember
	10, // 11: network.v1.LoadBalancer.health_check:type_name -> network.v1.LoadBalancerHealthCheck
	2,  // 12: network.v1.LoadBalancer.algorithm:type_name -> network.v1.LoadBalancerAlgorithm
	27, // 13: network.v1.LoadBalancer.state:type_name -> network.v1.ResourceState
	4,  // 14: network.v1.LoadBalancer.configuration_state:type_name -> network.v1.LoadBalancerConfigurationState
	5,  // 15: network.v1.LoadBalancer.data_plane_state:type_name -> network.v1.LoadBalancerDataPlaneState
	26, // 16: network.v1.LoadBalancer.observed_at:type_name -> google.protobuf.Timestamp
	26, // 17: network.v1.LoadBalancer.created_at:type_name -> google.protobuf.Timestamp
	26, // 18: network.v1.LoadBalancer.updated_at:type_name -> google.protobuf.Timestamp
	26, // 19: network.v1.LoadBalancer.data_plane_observed_at:type_name -> google.protobuf.Timestamp
	7,  // 20: network.v1.LoadBalancer.listeners:type_name -> network.v1.LoadBalancerListener
	0,  // 21: network.v1.CreateLoadBalancerRequest.exposure:type_name -> network.v1.LoadBalancerExposure
	6,  // 22: network.v1.CreateLoadBalancerRequest.listener:type_name -> network.v1.LoadBalancerListenerInput
	8,  // 23: network.v1.CreateLoadBalancerRequest.backends:type_name -> network.v1.LoadBalancerBackendInput
	10, // 24: network.v1.CreateLoadBalancerRequest.health_check:type_name -> network.v1.LoadBalancerHealthCheck
	24, // 25: network.v1.CreateLoadBalancerRequest.listeners:type_name -> network.v1.LoadBalancerListenerSet
	11, // 26: network.v1.CreateLoadBalancerResponse.load_balancer:type_name -> network.v1.LoadBalancer
	28, // 27: network.v1.CreateLoadBalancerResponse.operation:type_name -> network.v1.Operation
	11, // 28: network.v1.GetLoadBalancerResponse.load_balancer:type_name -> network.v1.LoadBalancer
	0,  // 29: network.v1.ListLoadBalancersRequest.exposure:type_name -> network.v1.LoadBalancerExposure
	27, // 30: network.v1.ListLoadBalancersRequest.state:type_name -> network.v1.ResourceState
	11, // 31: network.v1.ListLoadBalancersResponse.items:type_name -> network.v1.LoadBalancer
	8,  // 32: network.v1.UpdateLoadBalancerRequest.backends:type_name -> network.v1.LoadBalancerBackendInput
	10, // 33: network.v1.UpdateLoadBalancerRequest.health_check:type_name -> network.v1.LoadBalancerHealthCheck
	24, // 34: network.v1.UpdateLoadBalancerRequest.listeners:type_name -> network.v1.LoadBalancerListenerSet
	29, // 35: network.v1.UpdateLoadBalancerRequest.update_mask:type_name -> google.protobuf.FieldMask
	25, // 36: network.v1.UpdateLoadBalancerRequest.data:type_name -> network.v1.LoadBalancerMutableData
	11, // 37: network.v1.UpdateLoadBalancerResponse.load_balancer:type_name -> network.v1.LoadBalancer
	28, // 38: network.v1.UpdateLoadBalancerResponse.operation:type_name -> network.v1.Operation
	11, // 39: network.v1.DeleteLoadBalancerResponse.load_balancer:type_name -> network.v1.LoadBalancer
	28, // 40: network.v1.DeleteLoadBalancerResponse.operation:type_name -> network.v1.Operation
	28, // 41: network.v1.GetLoadBalancerOperationResponse.operation:type_name -> network.v1.Operation
	6,  // 42: network.v1.LoadBalancerListenerSet.items:type_name -> network.v1.LoadBalancerListenerInput
	24, // 43: network.v1.LoadBalancerMutableData.listeners:type_name -> network.v1.LoadBalancerListenerSet
	12, // 44: network.v1.TenantLoadBalancerService.CreateLoadBalancer:input_type -> network.v1.CreateLoadBalancerRequest
	14, // 45: network.v1.TenantLoadBalancerService.GetLoadBalancer:input_type -> network.v1.GetLoadBalancerRequest
	16, // 46: network.v1.TenantLoadBalancerService.ListLoadBalancers:input_type -> network.v1.ListLoadBalancersRequest
	18, // 47: network.v1.TenantLoadBalancerService.UpdateLoadBalancer:input_type -> network.v1.UpdateLoadBalancerRequest
	20, // 48: network.v1.TenantLoadBalancerService.DeleteLoadBalancer:input_type -> network.v1.DeleteLoadBalancerRequest
	22, // 49: network.v1.TenantLoadBalancerService.GetLoadBalancerOperation:input_type -> network.v1.GetLoadBalancerOperationRequest
	13, // 50: network.v1.TenantLoadBalancerService.CreateLoadBalancer:output_type -> network.v1.CreateLoadBalancerResponse
	15, // 51: network.v1.TenantLoadBalancerService.GetLoadBalancer:output_type -> network.v1.GetLoadBalancerResponse
	17, // 52: network.v1.TenantLoadBalancerService.ListLoadBalancers:output_type -> network.v1.ListLoadBalancersResponse
	19, // 53: network.v1.TenantLoadBalancerService.UpdateLoadBalancer:output_type -> network.v1.UpdateLoadBalancerResponse
	21, // 54: network.v1.TenantLoadBalancerService.DeleteLoadBalancer:output_type -> network.v1.DeleteLoadBalancerResponse
	23, // 55: network.v1.TenantLoadBalancerService.GetLoadBalancerOperation:output_type -> network.v1.GetLoadBalancerOperationResponse
	50, // [50:56] is the sub-list for method output_type
	44, // [44:50] is the sub-list for method input_type
	44, // [44:44] is the sub-list for extension type_name
	44, // [44:44] is the sub-list for extension extendee
	0,  // [0:44] is the sub-list for field type_name
}

func init() { file_network_v1_load_balancer_proto_init() }
func file_network_v1_load_balancer_proto_init() {
	if File_network_v1_load_balancer_proto != nil {
		return
	}
	file_network_v1_network_proto_init()
	file_network_v1_load_balancer_proto_msgTypes[0].OneofWrappers = []any{}
	file_network_v1_load_balancer_proto_msgTypes[2].OneofWrappers = []any{}
	file_network_v1_load_balancer_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_v1_load_balancer_proto_rawDesc), len(file_network_v1_load_balancer_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_v1_load_balancer_proto_goTypes,
		DependencyIndexes: file_network_v1_load_balancer_proto_depIdxs,
		EnumInfos:         file_network_v1_load_balancer_proto_enumTypes,
		MessageInfos:      file_network_v1_load_balancer_proto_msgTypes,
	}.Build()
	File_network_v1_load_balancer_proto = out.File
	file_network_v1_load_balancer_proto_goTypes = nil
	file_network_v1_load_balancer_proto_depIdxs = nil
}
